// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { CliStream } from "../../../../cliStream";
import { type CommandExecutor } from "../../../../executor";
import { CliCommandOkSchema, type CliCommandOk } from "../../../../ok";
import { type CliCommandViewerConfigSecretSetRequest } from "../../../../viewer/config/secret/set/request";
import { type CliCommandViewerConfigSecretSetRequestSchemaRequest } from "../../../../viewer/config/secret/set/request_schema/request";
import { type CliCommandViewerConfigSecretSetResponseSchemaRequest } from "../../../../viewer/config/secret/set/response_schema/request";
import { CliErrorSchema, type CliError } from "../../../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../../../jsonValue";

/** `viewer config secret set execute` — unary; first stream item, rest discarded. */
export async function viewerConfigSecretSetExecute(executor: CommandExecutor, request: Omit<CliCommandViewerConfigSecretSetRequest, "path_type">): Promise<CliError | CliCommandOk> {
  const stream = new CliStream(executor.execute({ ...request, path_type: "viewer/config/secret/set" }), z.union([CliErrorSchema, CliCommandOkSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("viewer config secret set: cli produced no output before the end marker");
  }
  return first;
}

/** `viewer config secret set execute_transform` — unary; first stream item, rest discarded. */
export async function viewerConfigSecretSetExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandViewerConfigSecretSetRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, path_type: "viewer/config/secret/set" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("viewer config secret set: cli produced no output before the end marker");
  }
  return first;
}

/** `viewer config secret set request_schema execute` — unary; first stream item, rest discarded. */
export async function viewerConfigSecretSetRequestSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandViewerConfigSecretSetRequestSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "viewer/config/secret/set/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("viewer config secret set request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `viewer config secret set request_schema execute_transform` — unary; first stream item, rest discarded. */
export async function viewerConfigSecretSetRequestSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandViewerConfigSecretSetRequestSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "viewer/config/secret/set/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("viewer config secret set request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `viewer config secret set response_schema execute` — unary; first stream item, rest discarded. */
export async function viewerConfigSecretSetResponseSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandViewerConfigSecretSetResponseSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "viewer/config/secret/set/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("viewer config secret set response_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `viewer config secret set response_schema execute_transform` — unary; first stream item, rest discarded. */
export async function viewerConfigSecretSetResponseSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandViewerConfigSecretSetResponseSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "viewer/config/secret/set/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("viewer config secret set response_schema: cli produced no output before the end marker");
  }
  return first;
}
