// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { JsonValueSchema } from "../../jsonValue";
import { McpToolContentBlockSchema } from "./contentBlock";

export const McpToolCallToolResultSchema = z.object({
  _meta: z.record(z.string(), JsonValueSchema).nullable().describe("Extension metadata.").meta({ omitempty: true }).optional(),
  content: z.array(McpToolContentBlockSchema).default([]).describe("Content blocks representing the result of the tool call."),
  isError: z.boolean().nullable().describe("Whether the tool call ended in an error.").meta({ omitempty: true }).optional(),
  structuredContent: z.record(z.string(), JsonValueSchema).nullable().describe("Structured tool output matching the tool's `outputSchema`.").meta({ omitempty: true }).optional(),
}).describe("The server's response to a `tools/call` request.").meta({ title: "mcp.tool.CallToolResult" });
export type McpToolCallToolResult = z.infer<typeof McpToolCallToolResultSchema>;
