// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandToolsInstallFilesystemRequestSchema } from "./filesystem/request";
import { CliCommandToolsInstallFilesystemRequestSchemaRequestSchema } from "./filesystem/request_schema/request";
import { CliCommandToolsInstallFilesystemResponseSchemaRequestSchema } from "./filesystem/response_schema/request";
import { CliCommandToolsInstallGithubRequestSchema } from "./github/request";
import { CliCommandToolsInstallGithubRequestSchemaRequestSchema } from "./github/request_schema/request";
import { CliCommandToolsInstallGithubResponseSchemaRequestSchema } from "./github/response_schema/request";

export const CliCommandToolsInstallRequestSchema = z.union([CliCommandToolsInstallFilesystemRequestSchema.meta({"title":"cli.command.tools.install.filesystem.Request","variantTitle":"Filesystem"}), CliCommandToolsInstallFilesystemRequestSchemaRequestSchema.meta({"title":"cli.command.tools.install.filesystem.request_schema.Request","variantTitle":"FilesystemRequestSchema"}), CliCommandToolsInstallFilesystemResponseSchemaRequestSchema.meta({"title":"cli.command.tools.install.filesystem.response_schema.Request","variantTitle":"FilesystemResponseSchema"}), CliCommandToolsInstallGithubRequestSchema.meta({"title":"cli.command.tools.install.github.Request","variantTitle":"Github"}), CliCommandToolsInstallGithubRequestSchemaRequestSchema.meta({"title":"cli.command.tools.install.github.request_schema.Request","variantTitle":"GithubRequestSchema"}), CliCommandToolsInstallGithubResponseSchemaRequestSchema.meta({"title":"cli.command.tools.install.github.response_schema.Request","variantTitle":"GithubResponseSchema"})]).meta({ title: "cli.command.tools.install.Request" });
export type CliCommandToolsInstallRequest = z.infer<typeof CliCommandToolsInstallRequestSchema>;
