# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.config.agents.response_item import ResponseItem as CliCommandConfigAgentsResponseItem
from objectiveai_sdk.cli.command.config.functions.response_item import ResponseItem as CliCommandConfigFunctionsResponseItem
from objectiveai_sdk.cli.command.config.mcp.response import Response as CliCommandConfigMcpResponse
from objectiveai_sdk.cli.command.config.swarms.response_item import ResponseItem as CliCommandConfigSwarmsResponseItem
from objectiveai_sdk.cli.command.config.viewer.response import Response as CliCommandConfigViewerResponse


class ResponseItemAgents(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Agents'})

    root: CliCommandConfigAgentsResponseItem


class ResponseItemFunctions(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Functions'})

    root: CliCommandConfigFunctionsResponseItem


class ResponseItemMcp(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Mcp'})

    root: CliCommandConfigMcpResponse


class ResponseItemSwarms(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Swarms'})

    root: CliCommandConfigSwarmsResponseItem


class ResponseItemViewer(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Viewer'})

    root: CliCommandConfigViewerResponse


class ResponseItem(RootModel):
    model_config = ConfigDict(title='cli.command.config.ResponseItem')

    root: Union[ResponseItemAgents, ResponseItemFunctions, ResponseItemMcp, ResponseItemSwarms, ResponseItemViewer]

