# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class Response(BaseModel):
    model_config = ConfigDict(title='cli.command.config.api.commit_author_name.get.Response')

    commit_author_name: Optional[str] = Field(None, json_schema_extra={'omitempty': True})

