// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsInlineProfileSchema, type FunctionsInlineProfile } from "./inlineProfile";
import { RemotePathSchema, type RemotePath } from "../remotePath";

export type FunctionsTaskProfile = RemotePath | FunctionsInlineProfile | Record<string, unknown>;
export const FunctionsTaskProfileSchema: z.ZodType<FunctionsTaskProfile> = z.union([RemotePathSchema.describe("Profile for a nested function task (references another profile).").meta({"title":"RemotePath","variantTitle":"Remote"}), z.lazy(() => FunctionsInlineProfileSchema).describe("Inline profile for a task (tasks-based or auto).").meta({"title":"functions.InlineProfile","variantTitle":"Inline"}), z.object({}).describe("Placeholder task — no configuration needed, output is fixed.").meta({"variantTitle":"Placeholder"})]).describe("Configuration for a single task within a Profile.\n\nEach variant corresponds to a task type in the Function definition.").meta({ title: "functions.TaskProfile" });
