# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_user_reply_outcome_not_found():
    from objectiveai_sdk.cli.user_listener import UserReplyOutcomeNotFound
    schema = UserReplyOutcomeNotFound.model_json_schema()
