// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandConfigApiMcpAuthorizationGetRequestSchemaPathSchema = z.literal("config/api/mcp_authorization/get/request_schema").meta({ title: "cli.command.config.api.mcp_authorization.get.request_schema.Path" });
export type CliCommandConfigApiMcpAuthorizationGetRequestSchemaPath = z.infer<typeof CliCommandConfigApiMcpAuthorizationGetRequestSchemaPathSchema>;
