# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel


class TargetDirect(BaseModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Direct'})

    agent_instance: str = Field(..., description='Leaf id of the target agent.')
    by: Literal['direct']
    parent_agent_instance_hierarchy: Optional[str] = Field(None, description='Lineage prefix to prepend to `agent_instance`. When\n`None`, the CLI substitutes its own\n`Config.agent_instance_hierarchy`.', json_schema_extra={'omitempty': True})


class TargetTag(BaseModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Tag'})

    agent_tag: str
    by: Literal['tag']


class Target(RootModel):
    """Mutually-exclusive target. `Direct` composes
`{parent}/{agent_instance}` at handler time (parent defaults to
the cli's own `Config.agent_instance_hierarchy`). `Tag` stores
the tag name verbatim Ã¢â‚¬â€ no `tags.sqlite` lookup at enqueue time."""
    model_config = ConfigDict(title='cli.command.agents.message_queue.add.Target')

    root: Union[TargetDirect, TargetTag]

