// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsAgentsCompletionsRequestGetRequestSchemaPathSchema = z.literal("logs/agents/completions/request/get/request_schema").meta({ title: "cli.command.logs.agents.completions.request.get.request_schema.Path" });
export type CliCommandLogsAgentsCompletionsRequestGetRequestSchemaPath = z.infer<typeof CliCommandLogsAgentsCompletionsRequestGetRequestSchemaPathSchema>;
