# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class ClientObjectiveaiMcpPluginMcpServer(BaseModel):
    """One `mcp_servers` entry on a
[`ClientObjectiveaiMcpPluginEntry`]: the manifest-declared `name`
the agent wants exposed, plus optional `arguments` the CLI feeds
to the plugin alongside the name when bringing the server up. The
arguments map is sorted by key in [`prepare`] so two equivalent
declarations (same key/value pairs in any order) hash to the same
canonical form."""
    model_config = ConfigDict(title='agent.ClientObjectiveaiMcpPluginMcpServer')

    arguments: Optional[dict[str, Optional[str]]] = Field(None, description='Optional key→value arguments forwarded to the plugin alongside\n`name`. `Some(value)` ⇒ `--key value` on the spawned plugin\'s\nargv; `None` ⇒ a bare `--key` flag with no following token. The\nplugin author decides how to interpret them. [`prepare`]\nnormalizes (`Some("") → None`), sorts the map by key, and\ncollapses an empty map to `None` so two equivalent declarations\ncanonicalize to byte-identical JSON.', json_schema_extra={'omitempty': True})
    name: str = Field(..., description="Author-chosen identifier — must match a `name` in the plugin\nmanifest's `mcp_servers` list. The CLI feeds this as the\nfirst positional arg when starting the plugin.")

