# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from objectiveai_sdk.json_value import JsonValue
from pydantic import BaseModel, ConfigDict, Field


class Plugin(BaseModel):
    """One plugin declaration: the plugin's coordinates plus optional
startup arguments for its MCP server.

NOTE: `name` (the repository segment) is slated for removal in a
later iteration of the plugin model; it remains part of the
identity triple for now."""
    model_config = ConfigDict(title='agent.Plugin')

    arguments: Optional[dict[str, JsonValue]] = Field(None, description="Optional key→value arguments handed to the plugin's MCP server\nat startup. Values are free-form JSON: a string behaves as\n`--key value` and `null` as a bare `--key` flag, but an object,\nan array or a number is equally valid and the plugin author\ndecides how to interpret them.\n\n[`prepare`] normalizes (an empty STRING becomes `null`, so the\ntwo spellings of a valueless flag canonicalize together), sorts\nthe map by key AND every object key nested inside a value at\nany depth, and collapses an empty map to `None` — so two\nequivalent declarations serialize byte-identically, which is\nwhat makes an agent id content-addressable. Array element order\nis left alone: that is data, not spelling.", json_schema_extra={'omitempty': True})
    name: str = Field(..., description='Repository segment.')
    owner: str = Field(..., description='GitHub `<owner>` segment.')
    version: str = Field(..., description='Plugin version.')

