// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandDbConfigUserSetRequestSchemaPathSchema = z.literal("db/config/user/set/request_schema").meta({ title: "cli.command.db.config.user.set.request_schema.Path" });
export type CliCommandDbConfigUserSetRequestSchemaPath = z.infer<typeof CliCommandDbConfigUserSetRequestSchemaPathSchema>;
