// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-listener-execution.cjs from objectiveai-sdk-rs/src/cli/command/.
import { type CliCommandAgentsEnqueueResponseSchemaRequest } from "./request";
import { type CliError } from "../../../../error";
import { type Identity } from "../../../../../identity";
import { type JsonValue } from "../../../../../jsonValue";

/** One `/listen` broadcast run of `agents enqueue response_schema`: the actual request, the producer's identity, and the unary response future. */
export type CliCommandAgentsEnqueueResponseSchemaListenerExecution = {
  request: CliCommandAgentsEnqueueResponseSchemaRequest;
  identity: Identity;
  response: Promise<CliError | JsonValue>;
};
