// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandFunctionsExecutionsCreateRequestSchema } from "./executions/create/request";
import { CliCommandFunctionsGetRequestSchema } from "./get/request";
import { CliCommandFunctionsGetRequestSchemaRequestSchema } from "./get/request_schema/request";
import { CliCommandFunctionsGetResponseSchemaRequestSchema } from "./get/response_schema/request";
import { CliCommandFunctionsInventionsRequestSchema } from "./inventions/request";
import { CliCommandFunctionsListRequestSchema } from "./list/request";
import { CliCommandFunctionsListRequestSchemaRequestSchema } from "./list/request_schema/request";
import { CliCommandFunctionsListResponseSchemaRequestSchema } from "./list/response_schema/request";
import { CliCommandFunctionsProfilesRequestSchema } from "./profiles/request";
import { CliCommandFunctionsPublishRequestSchema } from "./publish/request";
import { CliCommandFunctionsPublishRequestSchemaRequestSchema } from "./publish/request_schema/request";
import { CliCommandFunctionsPublishResponseSchemaRequestSchema } from "./publish/response_schema/request";

export const CliCommandFunctionsRequestSchema = z.union([CliCommandFunctionsExecutionsCreateRequestSchema.meta({"title":"cli.command.functions.executions.create.Request","variantTitle":"Executions"}), CliCommandFunctionsGetRequestSchema.meta({"title":"cli.command.functions.get.Request","variantTitle":"Get"}), CliCommandFunctionsGetRequestSchemaRequestSchema.meta({"title":"cli.command.functions.get.request_schema.Request","variantTitle":"GetRequestSchema"}), CliCommandFunctionsGetResponseSchemaRequestSchema.meta({"title":"cli.command.functions.get.response_schema.Request","variantTitle":"GetResponseSchema"}), CliCommandFunctionsInventionsRequestSchema.meta({"title":"cli.command.functions.inventions.Request","variantTitle":"Inventions"}), CliCommandFunctionsListRequestSchema.meta({"title":"cli.command.functions.list.Request","variantTitle":"List"}), CliCommandFunctionsListRequestSchemaRequestSchema.meta({"title":"cli.command.functions.list.request_schema.Request","variantTitle":"ListRequestSchema"}), CliCommandFunctionsListResponseSchemaRequestSchema.meta({"title":"cli.command.functions.list.response_schema.Request","variantTitle":"ListResponseSchema"}), CliCommandFunctionsProfilesRequestSchema.meta({"title":"cli.command.functions.profiles.Request","variantTitle":"Profiles"}), CliCommandFunctionsPublishRequestSchema.meta({"title":"cli.command.functions.publish.Request","variantTitle":"Publish"}), CliCommandFunctionsPublishRequestSchemaRequestSchema.meta({"title":"cli.command.functions.publish.request_schema.Request","variantTitle":"PublishRequestSchema"}), CliCommandFunctionsPublishResponseSchemaRequestSchema.meta({"title":"cli.command.functions.publish.response_schema.Request","variantTitle":"PublishResponseSchema"})]).meta({ title: "cli.command.functions.Request" });
export type CliCommandFunctionsRequest = z.infer<typeof CliCommandFunctionsRequestSchema>;
