[package]
name = "test-upstream"
version = "2.0.3"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "test-upstream"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
axum = "0.8.8"
dashmap = "6.1.0"
dotenv = "0.15.0"
envconfig = "0.11.1"
futures = "0.3.32"
indexmap = { version = "2.13.0", features = ["serde"] }
objectiveai = { path = "../../objectiveai-rs", version = "2.0.3", default-features = false, features = ["mcp"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
tokio = { version = "1.50.0", features = ["full"] }
tokio-util = "0.7.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.22.0", features = ["v4"] }
