// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribePathSchema = z.literal("logs/agents/completions/response/messages/assistant/tool_calls/subscribe").meta({ title: "cli.command.logs.agents.completions.response.messages.assistant.tool_calls.subscribe.Path" });
export type CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribePath = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribePathSchema>;
