// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandApiConfigHttpRefererSetPathSchema = z.literal("api/config/http_referer/set").meta({ title: "cli.command.api.config.http_referer.set.Path" });
export type CliCommandApiConfigHttpRefererSetPath = z.infer<typeof CliCommandApiConfigHttpRefererSetPathSchema>;
