# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from objectiveai_sdk.cli.websocket_agents_instances_listener.part_content import PartContent


class RequestMessageUserPart(BaseModel):
    """Mirror of `logs.list.RequestMessageUserPart`: `id` + `type` → the
opened content."""
    model_config = ConfigDict(title='cli.websocket_agents_instances_listener.RequestMessageUserPart')

    content: PartContent
    delivered_at: str

