# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal, Union
from pydantic import ConfigDict, RootModel


class ReasoningEffortNone(RootModel):
    """No reasoning."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'None'})

    root: Literal['none']


class ReasoningEffortMinimal(RootModel):
    """Minimal reasoning effort."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Minimal'})

    root: Literal['minimal']


class ReasoningEffortLow(RootModel):
    """Low reasoning effort."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Low'})

    root: Literal['low']


class ReasoningEffortMedium(RootModel):
    """Medium reasoning effort."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Medium'})

    root: Literal['medium']


class ReasoningEffortHigh(RootModel):
    """High reasoning effort."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'High'})

    root: Literal['high']


class ReasoningEffortXhigh(RootModel):
    """Maximum reasoning effort."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Xhigh'})

    root: Literal['xhigh']


class ReasoningEffort(RootModel):
    """The level of effort the model should put into reasoning.

Only supported by some models."""
    model_config = ConfigDict(title='agent.openrouter.ReasoningEffort')

    root: Union[ReasoningEffortNone, ReasoningEffortMinimal, ReasoningEffortLow, ReasoningEffortMedium, ReasoningEffortHigh, ReasoningEffortXhigh]

