// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsFunctionsInventionsResponseSubscribePathSchema = z.literal("logs/functions/inventions/response/subscribe").meta({ title: "cli.command.logs.functions.inventions.response.subscribe.Path" });
export type CliCommandLogsFunctionsInventionsResponseSubscribePath = z.infer<typeof CliCommandLogsFunctionsInventionsResponseSubscribePathSchema>;
