// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsInventionsStateAlphaScalarBranchStateSchema } from "./alphaScalarBranchState";
import { FunctionsInventionsStateAlphaScalarLeafStateSchema } from "./alphaScalarLeafState";
import { FunctionsInventionsStateAlphaVectorBranchStateSchema } from "./alphaVectorBranchState";
import { FunctionsInventionsStateAlphaVectorLeafStateSchema } from "./alphaVectorLeafState";

export const FunctionsInventionsStateStateSchema = z.union([FunctionsInventionsStateAlphaScalarBranchStateSchema.and(z.object({
  type: z.literal("alpha.scalar.branch.function"),
})).meta({"variantTitle":"AlphaScalarBranch"}), FunctionsInventionsStateAlphaScalarLeafStateSchema.and(z.object({
  type: z.literal("alpha.scalar.leaf.function"),
})).meta({"variantTitle":"AlphaScalarLeaf"}), FunctionsInventionsStateAlphaVectorBranchStateSchema.and(z.object({
  type: z.literal("alpha.vector.branch.function"),
})).meta({"variantTitle":"AlphaVectorBranch"}), FunctionsInventionsStateAlphaVectorLeafStateSchema.and(z.object({
  type: z.literal("alpha.vector.leaf.function"),
})).meta({"variantTitle":"AlphaVectorLeaf"})]).meta({ title: "functions.inventions.state.State" });
export type FunctionsInventionsStateState = z.infer<typeof FunctionsInventionsStateStateSchema>;
