# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_file_tree_node():
    from objectiveai_sdk.laboratories.filetree import FileTreeNode
    schema = FileTreeNode.model_json_schema()
