// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { AgentCompletionsResponseUnaryMessageSchema } from "../../../../agent/completions/response/unary/message";
import { AgentCompletionsResponseUnaryObjectSchema } from "../../../../agent/completions/response/unary/object";
import { AgentCompletionsResponseUsageSchema } from "../../../../agent/completions/response/usage";
import { AgentUpstreamSchema } from "../../../../agent/upstream";
import { ErrorResponseErrorSchema } from "../../../../error/responseError";
import { RemotePathSchema } from "../../../../remotePath";

export const LaboratoriesExecutionsResponseUnaryBuilderSchema = z.object({
  agent_full_id: z.string().describe("WF-level id: see\n[`super::streaming::AgentCompletionChunk::agent_full_id`]."),
  agent_id: z.string().describe("Leaf agent id of the slot that produced this completion. See\n[`super::streaming::AgentCompletionChunk::agent_id`]."),
  agent_index: z.number().int().min(0).max(18446744073709552000).describe("Agent index (0-based)."),
  agent_instance_hierarchy: z.string().describe("Full agent instance hierarchy for this completion's slot. See\n[`super::streaming::AgentCompletionChunk::agent_instance_hierarchy`]."),
  agent_remote: RemotePathSchema.nullable().describe("`RemotePath` the WF was fetched from, or `None` when inline.\nSee [`super::streaming::AgentCompletionChunk::agent_remote`].").meta({ omitempty: true }).optional(),
  continuation: z.string().nullable().describe("Continuation state for multi-turn conversations.").optional(),
  created: z.number().int().min(0).max(18446744073709552000),
  error: ErrorResponseErrorSchema.nullable().describe("Error details if this completion failed.").optional(),
  id: z.string(),
  index: z.number().int().min(0).max(18446744073709552000).describe("Builder index (0-based)."),
  messages: z.array(AgentCompletionsResponseUnaryMessageSchema),
  messages_queued: z.boolean().nullable().describe("`true` when the MCP proxy holds queued messages that were not\ndelivered to the agent via a tool response on this turn. See\n[`super::streaming::AgentCompletionChunk::messages_queued`].").meta({ omitempty: true }).optional(),
  object: AgentCompletionsResponseUnaryObjectSchema.describe("The object type (always \"agent.completion\")."),
  upstream: AgentUpstreamSchema.describe("Upstream provider"),
  usage: AgentCompletionsResponseUsageSchema,
}).describe("A single builder agent completion within a laboratory execution (non-streaming).").meta({ title: "laboratories.executions.response.unary.Builder" });
export type LaboratoriesExecutionsResponseUnaryBuilder = z.infer<typeof LaboratoriesExecutionsResponseUnaryBuilderSchema>;
