// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const LaboratoriesExecutionsResponseUnaryObjectSchema = z.literal("laboratory.execution").meta({ title: "laboratories.executions.response.unary.Object" });
export type LaboratoriesExecutionsResponseUnaryObject = z.infer<typeof LaboratoriesExecutionsResponseUnaryObjectSchema>;
