// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { type CliCommandAgentsEnqueueRequest } from "../../agents/enqueue/request";
import { type CliCommandAgentsEnqueueRequestSchemaRequest } from "../../agents/enqueue/request_schema/request";
import { CliCommandAgentsEnqueueResponseSchema, type CliCommandAgentsEnqueueResponse } from "../../agents/enqueue/response";
import { type CliCommandAgentsEnqueueResponseSchemaRequest } from "../../agents/enqueue/response_schema/request";
import { CliStream } from "../../cliStream";
import { type CommandExecutor } from "../../executor";
import { CliErrorSchema, type CliError } from "../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../jsonValue";

/** `agents enqueue execute` — unary; first stream item, rest discarded. */
export async function agentsEnqueueExecute(executor: CommandExecutor, request: Omit<CliCommandAgentsEnqueueRequest, "path_type">): Promise<CliError | CliCommandAgentsEnqueueResponse> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "agents/enqueue" }), z.union([CliErrorSchema, CliCommandAgentsEnqueueResponseSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("agents enqueue: cli produced no output before the end marker");
  }
  return first;
}

/** `agents enqueue execute_transform` — unary; first stream item, rest discarded. */
export async function agentsEnqueueExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandAgentsEnqueueRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "agents/enqueue" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("agents enqueue: cli produced no output before the end marker");
  }
  return first;
}

/** `agents enqueue request_schema execute` — unary; first stream item, rest discarded. */
export async function agentsEnqueueRequestSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandAgentsEnqueueRequestSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "agents/enqueue/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("agents enqueue request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `agents enqueue request_schema execute_transform` — unary; first stream item, rest discarded. */
export async function agentsEnqueueRequestSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandAgentsEnqueueRequestSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "agents/enqueue/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("agents enqueue request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `agents enqueue response_schema execute` — unary; first stream item, rest discarded. */
export async function agentsEnqueueResponseSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandAgentsEnqueueResponseSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "agents/enqueue/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("agents enqueue response_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `agents enqueue response_schema execute_transform` — unary; first stream item, rest discarded. */
export async function agentsEnqueueResponseSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandAgentsEnqueueResponseSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "agents/enqueue/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("agents enqueue response_schema: cli produced no output before the end marker");
  }
  return first;
}
