// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { CliStream } from "../../cliStream";
import { type CommandExecutor } from "../../executor";
import { type CliCommandToolsRunRequest } from "./request";
import { CliCommandToolsRunResponseItemSchema, type CliCommandToolsRunResponseItem } from "./responseItem";
import { CliErrorSchema, type CliError } from "../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../jsonValue";

/** `tools run execute` — streaming; mirror of the Rust fn of the same path. */
export function toolsRunExecute(executor: CommandExecutor, request: Omit<CliCommandToolsRunRequest, "path_type">): CliStream<CliError | CliCommandToolsRunResponseItem> {
  return new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "tools/run" }), z.union([CliErrorSchema, CliCommandToolsRunResponseItemSchema]));
}

/** `tools run execute_transform` — streaming; mirror of the Rust fn of the same path. */
export function toolsRunExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandToolsRunRequest, "path_type">, transform: { jq: string } | { python: string }): CliStream<CliError | JsonValue> {
  return new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "tools/run" }), z.union([CliErrorSchema, JsonValueSchema]));
}
