# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_request_detach():
    from objectiveai_sdk.cli.command.laboratories import RequestDetach
    schema = RequestDetach.model_json_schema()
