[package]
name = "objectiveai-sdk-wasm-js"
version = "2.0.11"
edition = "2024"
authors = ["ObjectiveAI <admin@objectiveai.dev>"]
description = "JavaScript WebAssembly bindings for ObjectiveAI"
license = "MIT"
repository = "https://github.com/ObjectiveAI/objectiveai"
homepage = "https://objectiveai.dev"
documentation = "https://docs.rs/objectiveai-sdk-wasm-js"
readme = "README.md"
keywords = ["llm", "ai", "swarm"]
publish = true

[lib]
crate-type = ["cdylib"]

[dependencies]
objectiveai-sdk = { path = "../objectiveai-sdk-rs", version = "2.0.11", default-features = false }
wasm-bindgen = { version = "0.2.114" }
serde-wasm-bindgen = { version = "0.6.5" }
rust_decimal = { version = "1.40.0", features = ["serde-float"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
arbitrary = "1.4.2"
rand = "0.10.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }
