// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandAgentsReadAllResponseContentSchema } from "./responseContent";

export const CliCommandAgentsReadAllResponseQueueMessageSchema = z.union([z.object({
  content: CliCommandAgentsReadAllResponseContentSchema,
  name: z.string().nullable().meta({ omitempty: true }).optional(),
  type: z.literal("developer"),
}).meta({"variantTitle":"Developer"}), z.object({
  content: CliCommandAgentsReadAllResponseContentSchema,
  name: z.string().nullable().meta({ omitempty: true }).optional(),
  type: z.literal("system"),
}).meta({"variantTitle":"System"}), z.object({
  content: CliCommandAgentsReadAllResponseContentSchema,
  name: z.string().nullable().meta({ omitempty: true }).optional(),
  type: z.literal("user"),
}).meta({"variantTitle":"User"}), z.object({
  content: CliCommandAgentsReadAllResponseContentSchema.nullable().meta({ omitempty: true }).optional(),
  name: z.string().nullable().meta({ omitempty: true }).optional(),
  reasoning: z.number().int().min(-9223372036854776000).max(9223372036854776000).nullable().meta({ omitempty: true }).optional(),
  refusal: z.number().int().min(-9223372036854776000).max(9223372036854776000).nullable().meta({ omitempty: true }).optional(),
  tool_calls: z.array(z.number().int().min(-9223372036854776000).max(9223372036854776000)).nullable().meta({ omitempty: true }).optional(),
  type: z.literal("assistant"),
}).meta({"variantTitle":"Assistant"}), z.object({
  content: CliCommandAgentsReadAllResponseContentSchema,
  tool_call_id: z.string(),
  type: z.literal("tool"),
}).meta({"variantTitle":"Tool"})]).meta({ title: "cli.command.agents.read.all.ResponseQueueMessage" });
export type CliCommandAgentsReadAllResponseQueueMessage = z.infer<typeof CliCommandAgentsReadAllResponseQueueMessageSchema>;
