// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FilesystemLogsLogReferenceSchema } from "../../../filesystem/logs/logReference";

export const AgentCompletionsMessageSimpleContentLogSchema = z.union([FilesystemLogsLogReferenceSchema.meta({"title":"filesystem.logs.LogReference","variantTitle":"Reference"}), z.array(FilesystemLogsLogReferenceSchema).meta({"variantTitle":"Parts"})]).meta({ title: "agent.completions.message.SimpleContentLog" });
export type AgentCompletionsMessageSimpleContentLog = z.infer<typeof AgentCompletionsMessageSimpleContentLogSchema>;
