// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-viewer-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { type CliCommandLogsFunctionsExecutionsResponseListRequest } from "../../../../../../cli/command/logs/functions/executions/response/list/request";
import { type CliCommandLogsFunctionsExecutionsResponseListRequestSchemaRequest } from "../../../../../../cli/command/logs/functions/executions/response/list/request_schema/request";
import { CliCommandLogsFunctionsExecutionsResponseListResponseItemSchema, type CliCommandLogsFunctionsExecutionsResponseListResponseItem } from "../../../../../../cli/command/logs/functions/executions/response/list/responseItem";
import { type CliCommandLogsFunctionsExecutionsResponseListResponseSchemaRequest } from "../../../../../../cli/command/logs/functions/executions/response/list/response_schema/request";
import { CliErrorSchema, type CliError } from "../../../../../../cli/error";
import { JsonValueSchema, type JsonValue } from "../../../../../../jsonValue";
import { CliStream } from "../../../../../cliStream";
import { invokeCliRequest } from "../../../../../invoke";

/** `logs functions executions response list execute` — streaming; mirror of the Rust fn of the same path. */
export function logsFunctionsExecutionsResponseListExecute(request: Omit<CliCommandLogsFunctionsExecutionsResponseListRequest, "path_type">): CliStream<CliError | CliCommandLogsFunctionsExecutionsResponseListResponseItem> {
  return new CliStream(invokeCliRequest({ ...request, jq: undefined, path_type: "logs/functions/executions/response/list" }), z.union([CliErrorSchema, CliCommandLogsFunctionsExecutionsResponseListResponseItemSchema]));
}

/** `logs functions executions response list execute_jq` — streaming; mirror of the Rust fn of the same path. */
export function logsFunctionsExecutionsResponseListExecuteJq(request: Omit<CliCommandLogsFunctionsExecutionsResponseListRequest, "path_type">, jq: string): CliStream<CliError | JsonValue> {
  return new CliStream(invokeCliRequest({ ...request, jq, path_type: "logs/functions/executions/response/list" }), z.union([CliErrorSchema, JsonValueSchema]));
}

/** `logs functions executions response list request_schema execute` — unary; first stream item, rest discarded. */
export async function logsFunctionsExecutionsResponseListRequestSchemaExecute(request: Omit<CliCommandLogsFunctionsExecutionsResponseListRequestSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq: undefined, path_type: "logs/functions/executions/response/list/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("logs functions executions response list request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `logs functions executions response list request_schema execute_jq` — unary; first stream item, rest discarded. */
export async function logsFunctionsExecutionsResponseListRequestSchemaExecuteJq(request: Omit<CliCommandLogsFunctionsExecutionsResponseListRequestSchemaRequest, "path_type">, jq: string): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq, path_type: "logs/functions/executions/response/list/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("logs functions executions response list request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `logs functions executions response list response_schema execute` — unary; first stream item, rest discarded. */
export async function logsFunctionsExecutionsResponseListResponseSchemaExecute(request: Omit<CliCommandLogsFunctionsExecutionsResponseListResponseSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq: undefined, path_type: "logs/functions/executions/response/list/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("logs functions executions response list response_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `logs functions executions response list response_schema execute_jq` — unary; first stream item, rest discarded. */
export async function logsFunctionsExecutionsResponseListResponseSchemaExecuteJq(request: Omit<CliCommandLogsFunctionsExecutionsResponseListResponseSchemaRequest, "path_type">, jq: string): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq, path_type: "logs/functions/executions/response/list/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("logs functions executions response list response_schema: cli produced no output before the end marker");
  }
  return first;
}
