// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandApiConfigRequestSchema } from "./config/request";

export const CliCommandApiRequestSchema = CliCommandApiConfigRequestSchema.meta({ title: "cli.command.api.Request" });
export type CliCommandApiRequest = z.infer<typeof CliCommandApiRequestSchema>;
