// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsAgentsCompletionsResponseMessagesAssistantReasoningSubscribeResponseSchemaPathSchema = z.literal("logs/agents/completions/response/messages/assistant/reasoning/subscribe/response_schema").meta({ title: "cli.command.logs.agents.completions.response.messages.assistant.reasoning.subscribe.response_schema.Path" });
export type CliCommandLogsAgentsCompletionsResponseMessagesAssistantReasoningSubscribeResponseSchemaPath = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesAssistantReasoningSubscribeResponseSchemaPathSchema>;
