// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandAgentsLaboratoriesDetachResponseSchema = z.object({
  laboratory_id: z.string().describe("The laboratory id that was detached from the target."),
}).describe("Confirmation — detach succeeded; echoes the laboratory id that was\ndetached.").meta({ title: "cli.command.agents.laboratories.detach.Response" });
export type CliCommandAgentsLaboratoriesDetachResponse = z.infer<typeof CliCommandAgentsLaboratoriesDetachResponseSchema>;
