// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { type CliCommandChannelsLogsSubscribeRequest } from "./request";
import { CliCommandChannelsLogsSubscribeResponseItemSchema, type CliCommandChannelsLogsSubscribeResponseItem } from "./responseItem";
import { CliStream } from "../../../cliStream";
import { type CommandExecutor } from "../../../executor";
import { CliErrorSchema, type CliError } from "../../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../../jsonValue";

/** `channels logs subscribe execute` — streaming; mirror of the Rust fn of the same path. */
export function channelsLogsSubscribeExecute(executor: CommandExecutor, request: Omit<CliCommandChannelsLogsSubscribeRequest, "path_type">): CliStream<CliError | CliCommandChannelsLogsSubscribeResponseItem> {
  return new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "channels/logs/subscribe" }), z.union([CliErrorSchema, CliCommandChannelsLogsSubscribeResponseItemSchema]));
}

/** `channels logs subscribe execute_transform` — streaming; mirror of the Rust fn of the same path. */
export function channelsLogsSubscribeExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandChannelsLogsSubscribeRequest, "path_type">, transform: { jq: string } | { python: string }): CliStream<CliError | JsonValue> {
  return new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "channels/logs/subscribe" }), z.union([CliErrorSchema, JsonValueSchema]));
}
