// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { CliStream } from "../../cliStream";
import { type CommandExecutor } from "../../executor";
import { type CliCommandLaboratoriesListRequest } from "./request";
import { CliCommandLaboratoriesListResponseItemSchema, type CliCommandLaboratoriesListResponseItem } from "./responseItem";
import { CliErrorSchema, type CliError } from "../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../jsonValue";

/** `laboratories list execute` — streaming; mirror of the Rust fn of the same path. */
export function laboratoriesListExecute(executor: CommandExecutor, request: Omit<CliCommandLaboratoriesListRequest, "path_type">): CliStream<CliError | CliCommandLaboratoriesListResponseItem> {
  return new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "laboratories/list" }), z.union([CliErrorSchema, CliCommandLaboratoriesListResponseItemSchema]));
}

/** `laboratories list execute_transform` — streaming; mirror of the Rust fn of the same path. */
export function laboratoriesListExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandLaboratoriesListRequest, "path_type">, transform: { jq: string } | { python: string }): CliStream<CliError | JsonValue> {
  return new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "laboratories/list" }), z.union([CliErrorSchema, JsonValueSchema]));
}
