// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { type CliCommandApiConfigBackoffMaxElapsedTimeMsGetRequest } from "../../../../api/config/backoff_max_elapsed_time_ms/get/request";
import { type CliCommandApiConfigBackoffMaxElapsedTimeMsGetRequestSchemaRequest } from "../../../../api/config/backoff_max_elapsed_time_ms/get/request_schema/request";
import { CliCommandApiConfigBackoffMaxElapsedTimeMsGetResponseSchema, type CliCommandApiConfigBackoffMaxElapsedTimeMsGetResponse } from "../../../../api/config/backoff_max_elapsed_time_ms/get/response";
import { type CliCommandApiConfigBackoffMaxElapsedTimeMsGetResponseSchemaRequest } from "../../../../api/config/backoff_max_elapsed_time_ms/get/response_schema/request";
import { CliStream } from "../../../../cliStream";
import { type CommandExecutor } from "../../../../executor";
import { CliErrorSchema, type CliError } from "../../../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../../../jsonValue";

/** `api config backoff_max_elapsed_time_ms get execute` — unary; first stream item, rest discarded. */
export async function apiConfigBackoffMaxElapsedTimeMsGetExecute(executor: CommandExecutor, request: Omit<CliCommandApiConfigBackoffMaxElapsedTimeMsGetRequest, "path_type">): Promise<CliError | CliCommandApiConfigBackoffMaxElapsedTimeMsGetResponse> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "api/config/backoff_max_elapsed_time_ms/get" }), z.union([CliErrorSchema, CliCommandApiConfigBackoffMaxElapsedTimeMsGetResponseSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("api config backoff_max_elapsed_time_ms get: cli produced no output before the end marker");
  }
  return first;
}

/** `api config backoff_max_elapsed_time_ms get execute_transform` — unary; first stream item, rest discarded. */
export async function apiConfigBackoffMaxElapsedTimeMsGetExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandApiConfigBackoffMaxElapsedTimeMsGetRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "api/config/backoff_max_elapsed_time_ms/get" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("api config backoff_max_elapsed_time_ms get: cli produced no output before the end marker");
  }
  return first;
}

/** `api config backoff_max_elapsed_time_ms get request_schema execute` — unary; first stream item, rest discarded. */
export async function apiConfigBackoffMaxElapsedTimeMsGetRequestSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandApiConfigBackoffMaxElapsedTimeMsGetRequestSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "api/config/backoff_max_elapsed_time_ms/get/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("api config backoff_max_elapsed_time_ms get request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `api config backoff_max_elapsed_time_ms get request_schema execute_transform` — unary; first stream item, rest discarded. */
export async function apiConfigBackoffMaxElapsedTimeMsGetRequestSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandApiConfigBackoffMaxElapsedTimeMsGetRequestSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "api/config/backoff_max_elapsed_time_ms/get/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("api config backoff_max_elapsed_time_ms get request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `api config backoff_max_elapsed_time_ms get response_schema execute` — unary; first stream item, rest discarded. */
export async function apiConfigBackoffMaxElapsedTimeMsGetResponseSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandApiConfigBackoffMaxElapsedTimeMsGetResponseSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "api/config/backoff_max_elapsed_time_ms/get/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("api config backoff_max_elapsed_time_ms get response_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `api config backoff_max_elapsed_time_ms get response_schema execute_transform` — unary; first stream item, rest discarded. */
export async function apiConfigBackoffMaxElapsedTimeMsGetResponseSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandApiConfigBackoffMaxElapsedTimeMsGetResponseSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "api/config/backoff_max_elapsed_time_ms/get/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("api config backoff_max_elapsed_time_ms get response_schema: cli produced no output before the end marker");
  }
  return first;
}
