// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandConfigFunctionsFavoritesEditResponseSchemaPathSchema } from "./path";

export const CliCommandConfigFunctionsFavoritesEditResponseSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandConfigFunctionsFavoritesEditResponseSchemaPathSchema,
}).meta({ title: "cli.command.config.functions.favorites.edit.response_schema.Request" });
export type CliCommandConfigFunctionsFavoritesEditResponseSchemaRequest = z.infer<typeof CliCommandConfigFunctionsFavoritesEditResponseSchemaRequestSchema>;
