// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandApiConfigMcpAuthorizationDelPathSchema } from "./path";
import { CliCommandSetScopeSchema } from "../../../../setScope";

export const CliCommandApiConfigMcpAuthorizationDelRequestSchema = z.object({
  key: z.string(),
  path_type: CliCommandApiConfigMcpAuthorizationDelPathSchema,
  scope: CliCommandSetScopeSchema,
}).meta({ title: "cli.command.api.config.mcp_authorization.del.Request" });
export type CliCommandApiConfigMcpAuthorizationDelRequest = z.infer<typeof CliCommandApiConfigMcpAuthorizationDelRequestSchema>;
