// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-viewer-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { type CliCommandDbConfigPasswordSetRequest } from "../../../../../cli/command/db/config/password/set/request";
import { type CliCommandDbConfigPasswordSetRequestSchemaRequest } from "../../../../../cli/command/db/config/password/set/request_schema/request";
import { type CliCommandDbConfigPasswordSetResponseSchemaRequest } from "../../../../../cli/command/db/config/password/set/response_schema/request";
import { type CommandExecutor } from "../../../../../cli/command/executor";
import { CliCommandOkSchema, type CliCommandOk } from "../../../../../cli/command/ok";
import { CliErrorSchema, type CliError } from "../../../../../cli/error";
import { JsonValueSchema, type JsonValue } from "../../../../../jsonValue";
import { CliStream } from "../../../../cliStream";

/** `db config password set execute` — unary; first stream item, rest discarded. */
export async function dbConfigPasswordSetExecute(executor: CommandExecutor, request: Omit<CliCommandDbConfigPasswordSetRequest, "path_type">): Promise<CliError | CliCommandOk> {
  const stream = new CliStream(executor.execute({ ...request, path_type: "db/config/password/set" }), z.union([CliErrorSchema, CliCommandOkSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db config password set: cli produced no output before the end marker");
  }
  return first;
}

/** `db config password set execute_transform` — unary; first stream item, rest discarded. */
export async function dbConfigPasswordSetExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandDbConfigPasswordSetRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, path_type: "db/config/password/set" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db config password set: cli produced no output before the end marker");
  }
  return first;
}

/** `db config password set request_schema execute` — unary; first stream item, rest discarded. */
export async function dbConfigPasswordSetRequestSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandDbConfigPasswordSetRequestSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "db/config/password/set/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db config password set request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `db config password set request_schema execute_transform` — unary; first stream item, rest discarded. */
export async function dbConfigPasswordSetRequestSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandDbConfigPasswordSetRequestSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "db/config/password/set/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db config password set request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `db config password set response_schema execute` — unary; first stream item, rest discarded. */
export async function dbConfigPasswordSetResponseSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandDbConfigPasswordSetResponseSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "db/config/password/set/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db config password set response_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `db config password set response_schema execute_transform` — unary; first stream item, rest discarded. */
export async function dbConfigPasswordSetResponseSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandDbConfigPasswordSetResponseSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "db/config/password/set/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db config password set response_schema: cli produced no output before the end marker");
  }
  return first;
}
