// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsVectorCompletionsResponseItemSchema } from "./completions/responseItem";

export const CliCommandLogsVectorResponseItemSchema = z.object({
  Completions: CliCommandLogsVectorCompletionsResponseItemSchema,
}).strict().meta({ title: "cli.command.logs.vector.ResponseItem" });
export type CliCommandLogsVectorResponseItem = z.infer<typeof CliCommandLogsVectorResponseItemSchema>;
