// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const FilesystemConfigApiHeadersConfigSchema = z.object({
  http_referer: z.string().nullable().meta({ omitempty: true }).optional(),
  user_agent: z.string().nullable().meta({ omitempty: true }).optional(),
  x_commit_author_email: z.string().nullable().meta({ omitempty: true }).optional(),
  x_commit_author_name: z.string().nullable().meta({ omitempty: true }).optional(),
  x_github_authorization: z.string().nullable().meta({ omitempty: true }).optional(),
  x_mcp_authorization: z.record(z.string(), z.string()).nullable().meta({ omitempty: true }).optional(),
  x_objectiveai_authorization: z.string().nullable().meta({ omitempty: true }).optional(),
  x_openrouter_authorization: z.string().nullable().meta({ omitempty: true }).optional(),
  x_title: z.string().nullable().meta({ omitempty: true }).optional(),
  x_viewer_address: z.string().nullable().meta({ omitempty: true }).optional(),
  x_viewer_signature: z.string().nullable().meta({ omitempty: true }).optional(),
}).meta({ title: "filesystem.config.ApiHeadersConfig" });
export type FilesystemConfigApiHeadersConfig = z.infer<typeof FilesystemConfigApiHeadersConfigSchema>;
