// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-listener-execution.cjs from objectiveai-sdk-rs/src/cli/command/.
import { type ResponseItemStream } from "../../../broadcastListener";
import { type CliCommandAgentArguments } from "../../agentArguments";
import { type CliCommandPluginsRunRequest } from "./request";
import { type CliCommandPluginsRunResponseItem } from "./responseItem";
import { type CliError } from "../../../error";

/** One `/listen` broadcast run of `plugins run`: the actual request, the producer's agent arguments, and the response-item stream. */
export type CliCommandPluginsRunListenerExecution = {
  request: CliCommandPluginsRunRequest;
  agentArguments: CliCommandAgentArguments;
  response: ResponseItemStream<CliError | CliCommandPluginsRunResponseItem>;
};
