# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_manifest():
    from objectiveai_sdk.filesystem.tools import Manifest
    schema = Manifest.model_json_schema()
