// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandAgentsListAvailableRequestSchemaPathSchema = z.literal("agents/list/available/request_schema").meta({ title: "cli.command.agents.list.available.request_schema.Path" });
export type CliCommandAgentsListAvailableRequestSchemaPath = z.infer<typeof CliCommandAgentsListAvailableRequestSchemaPathSchema>;
