// Every word a person reads in this app lives here, so Maya's naming
// pass is one edit. The words below are PROVISIONAL — names are tabled.

export const t = {
  app: {
    name: "Diverge",
    draft: "draft three",
  },
  home: {
    askWhere: "Ask in:",
    askSend: "Send to",
    askSent: "Asked in",
    room: "room",
    rooms: "rooms",
    yourAsks: "Your asks",
    theirAsks: "Asks you might help with",
    noAsks: "You haven't asked anything yet.",
    noTheirAsks: "Nothing open from anyone else.",
    answered: "Answered",
    noAnswerYet: "No answer yet",
    nothingYet: "nothing yet",
    offer: "offer",
    offersWord: "offers",
    reply: "reply",
    replies: "replies",
    alsoAsk: "No one has answered. You could also ask in",
    title: "Home",
    views: { all: "All", asks: "Asks", shows: "Shows", board: "Board", runs: "Runs", ideas: "Ideas" } as Record<string, string>,
    composePlaceholder: "Show something, or ask for something…",
    show: "Show",
    ask: "Ask",
    fleet: "Your agents",
    working: "Working",
    idle: "Idle",
    never: "Hasn't run",
    waitingOnYou: "Waiting on you",
    nothingWaiting: "Nothing waiting on you.",
    doneToday: "Done today",
    empty: "Nothing here yet.",
    in: "in",
    open: "Open",
  },
  door: {
    before: "Before you knock",
    beforeNote: "Nothing has been sent. This is what the invite says the room is.",
    hostedBy: "Hosted by",
    rules: "Its rules",
    verbsTitle: "What you can do there",
    verbsNote: "These are the room's only verbs. Your agents get the same ones, nothing more.",
    theyllSee: "What the host will see about you",
    seeAddress: "Your internet address, as their machine sees it",
    seeName: "The name you choose below",
    seeNote: "Your note",
    appearAs: "You'll appear as",
    usual: "Your usual name",
    fresh: "A fresh name, just for this room",
    freshPlaceholder: "a name for this room",
    freshNote: "A fresh name is a new key: the room can't tell it's you. Your agents there get new keys and plain names too. What you say and do there can still give you away, so the name hides you only as well as you do.",
    noteLabel: "A note to the host",
    notePlaceholder: "Who you are, or who sent you",
    listed: "Put me on the room's list",
    listedNote: "Otherwise you're not on the room's list. Its record keeps the name you gave but not your key, until you do something; then everyone there sees it was you.",
    vouchLabel: "A vouch someone gave you",
    vouchPlaceholder: "diverge-vouch:…",
    knock: "Knock",
    waiting: "Waiting for the host to answer…",
    in: "You're in.",
    open: "Go in",
    rulesDiffer: "The room's rules aren't the ones this invite showed. Read them again before you do anything there.",
    denied: "The host said no.",
    missing: "That room isn't running right now.",
    openDoor: "This invite has no key: the host will read your note and decide.",
    alreadyIn: "You're already in this room.",
    notAnInvite: "That isn't an invite.",
    paste: "Paste an invite",
    read: "Read it",
    fromDm: "An invite",
    openInvite: "Read this invite",
    title: "Before you take part",
    youAreIn: "You're in. The host let you through. Here is what this room is, before you do anything in it.",
    runsOn: "It runs on",
    nothingOnYours: "Nothing runs on your machine. Nothing here can read your storage or your keys.",
    itCanAsk: "What you can do here, and what it can ask of you",
    itCanAskNote: "These are the room's only verbs. Your agents get the same ones, nothing more.",
    youKeep: "If you leave",
    keepPosts: "What you posted stays in the room — it lives on the host's storage.",
    keepReceipts: "Receipts issued here stay here. They are a record, not a score, and they never leave the room that issued them.",
    keepAnytime: "You can leave any time. Nothing holds you: there is no escrow here, and the host cannot keep you in.",
    charter: "The charter",
    noCharter: "The host wrote no charter.",
    stay: "Stay",
    leave: "Leave now",
    showAgain: "Door",
  },
  profile: {
    personas: "Your names",
    personasNote: "Each is a separate you. A room sees only the one you use there.",
    usualTag: "usual",
    inRooms: "In",
    noRooms: "Not in any room yet",
    rename: "Rename",
    save: "Save",
    visit: "Your profile room",
    pin: "Show on your profile",
    pinned: "On your profile",
    visitNote: "What visitors see, and what they left you.",
    notes: "Notes left for you",
    noNotes: "No notes yet.",
    shop: "What you offer",
    hires: "Asked of your agents",
    noHires: "Nobody has asked yet.",
    holds: "sealed by",
    doesntHold: "its seal doesn't hold",
    title: "You",
    note: "What you've shown, what you've earned, and what your machines offer. Nothing here is a score.",
    receipts: "Receipts",
    receiptsNote: "For tasks done. Each stays with the Space that issued it.",
    noReceipts: "None yet. Receipts come from tasks done in Spaces you're in.",
    earnedBy: "earned by",
    issuedBy: "issued in",
    someoneYouKnow: "someone you know",
    someoneNew: "someone you haven't met in a room",
    earnedAsFresh: "Earned as",
    earnedAsFreshNote: ": putting it on your profile would show that name is you.",
    shows: "Shown",
    noShows: "Nothing shown yet.",
    agents: "Agents",
    machines: "Machines",
    storage: "Storage",
    offers: "What your machines offer",
    offersNote: "Measured, never priced.",
    volumesLine: "volumes",
  },
  inbox: {
    title: "Inbox",
    note: "People and agents, one list.",
    people: "People",
    agents: "Agents",
    newDm: "Message someone",
    pick: "Pick a person you share a Space with",
    start: "Start",
    empty: "Pick a thread.",
    nothingSaid: "Nothing said yet.",
    placeholder: "Message",
    send: "Send",
    lastActive: "last active",
    noThreads: "No one yet. Join a Space to meet people.",
  },
  rail: {
    home: "Home",
    inbox: "Inbox",
    you: "You",
    agents: "Agents",
    newAgent: "New agent",
    storage: "Storage",
    spaces: "Spaces",
    allSpaces: "All Spaces",
    atTheDoor: "at the door",
    machines: "Machines",
    views: "Views",
    refreshed: "Listed just now",
    refreshNote: "The daemon's list isn't live, so this re-asks every few seconds.",
    empty: "No agents yet.",
  },
  standIn: {
    label: "Stand-in daemon",
    note: "Runs are scripted and nothing leaves this Mac. Ronald's daemon replaces this in one piece.",
    pin: "Built against",
    preview: "Browser preview: a snapshot of the stand-in, for looking at screens. Nothing here runs.",
    previewShort: "Browser preview",
  },
  status: {
    working: "Working",
    idle: "Idle",
    never: "Hasn't run yet",
    on: "on",
  },
  provider: {
    outgoing: "You connect to it",
    incoming: "It connects to you",
  },
  emptyState: {
    title: "Nothing open",
    body: "Pick an agent on the left, or make a new one.",
  },
  convo: {
    you: "You",
    thinking: "Thinking",
    tool: "Used",
    helper: "Helper's work",
    worked: "Worked",
    workingNow: "Working",
    thought: "thought",
    helperOne: "helper",
    helpers: "helpers",
    // What the agent door's tools read as, in a work line.
    doorTools: {
      spaces_list: "looked at your Spaces",
      space_feed: "read a board",
      space_tools: "checked a room's verbs",
      space_call: "acted in a Space",
      ask_person: "asked you",
    } as Record<string, string>,
    waitingForAnswer: "waiting for an answer",
    failed: "didn't work",
    started: "Started",
    finished: "Finished",
    measured: "Measured",
    tokens: "tokens",
    working: "Working…",
    empty: "No conversation yet. Say something to start it.",
    placeholder: "Message",
    send: "Send",
    queueNote: "It's working. New messages wait in line until it's ready.",
    waiting: "Waiting to be picked up",
    takeBack: "Take back",
    takenBack: "Taken back",
    tooLate: "Already picked up",
    remove: "Remove",
    removeActive: "It's running, so the daemon won't remove it. Try again when it finishes.",
    removeConfirm: "Remove for good",
    removeCancel: "Keep it",
    watching: "Watching live",
    notWatching: "Not watching",
    stopWatching: "Stop watching",
    watch: "Watch live",
    noStop: "A running agent can't be stopped — only messages that haven't been picked up can be taken back.",
    notice: "Notice",
    fatal: "Stopped the run",
    refusal: "Declined",
    arguments: "Asked with",
    answer: "Answer",
    image: "image",
    audio: "audio",
  },
  create: {
    title: "New agent",
    kind: "What kind of agent",
    settings: "Its settings",
    moreSettings: "More settings",
    limits: "Limits",
    limitsNote: "Hard ceilings on the machine it runs on. The daemon has no timeout, so these are the ceilings there are.",
    memory: "Memory (GB)",
    disk: "Disk (GB)",
    where: "Where it runs",
    anywhere: "Wherever the daemon picks",
    anywhereNote: "It keeps its conversation; nothing stays on the machine's disk.",
    pinned: "On one machine",
    pinnedNote: "Needed to mount that machine's storage directly. It stays on that machine for life.",
    machine: "Machine",
    storage: "Storage from that machine",
    addStorage: "Add storage",
    volume: "Storage",
    inVolume: "Folder in it",
    inAgent: "Shows up as",
    share: "Live storage from any machine",
    shareNote: "Served through the daemon, as it is, as it changes. The agent holds that volume until you remove the agent, and one that keeps changes has one user at a time.",
    from: "Machine",
    addShare: "Share a volume",
    addFileShare: "Share one file",
    here: "Volume",
    inHere: "Folder or file in it",
    name: "Name",
    namePlaceholder: "a-name-you-will-recognise",
    first: "First message",
    firstPlaceholder: "What should it do? (optional)",
    create: "Make agent",
    creating: "Making…",
    inUse: "That name is taken.",
    ready: "These settings are ones this agent accepts.",
    fillIn: "Still to fill in:",
    notReady: "Not accepted yet:",
    needed: "needed",
    remove: "Remove",
    add: "Add",
    none: "None",
    default: "Default",
    on: "On",
    off: "Off",
    json: "Any JSON",
    key: "Name",
    value: "Value",
    kinds: {
      cc: { title: "Claude Code", blurb: "Reads, edits and runs code." },
      codex: { title: "Codex", blurb: "OpenAI's coding agent." },
      hermes: { title: "Hermes", blurb: "A general agent: any of 40+ model providers, and toolsets." },
      openrouter: { title: "OpenRouter", blurb: "Any model through OpenRouter, every dial exposed." },
      eliza: { title: "Eliza", blurb: "A character, with a personality and memory." },
      python: { title: "Python", blurb: "Your own loop, in Python." },
    } as Record<string, { title: string; blurb: string }>,
  },
  mounts: {
    button: "Mounts",
    title: "What it mounts",
    pinnedTo: "Pinned to",
    anywhere: "Runs wherever the daemon picks, so it mounts no machine's storage directly.",
    own: "From its machine",
    live: "Live from any machine",
    none: "Nothing mounted.",
    save: "Save mounts",
    saving: "Saving…",
    saved: "Saved. Its next run sees them.",
    active: "It's working. Change its mounts once it stops.",
    notFound: "The daemon has no agent by that name.",
    unknown: "Made outside this app. The daemon doesn't report an agent's mounts, and a change states them all anew, so changing them here could drop ones you can't see.",
    replaces: "What you save replaces all of its mounts. Its machine, settings and limits stay as they are.",
    close: "Close",
  },
  storage: {
    title: "Storage",
    note: "Each machine's own storage. Agents on that machine mount it directly; agents anywhere can have it live. While anything holds a volume, nothing else can touch it.",
    machine: "Machine",
    noMachines: "No machines yet. Add one in Machines.",
    mode: "What agents' changes do",
    modes: { persistent: "Keeps changes", ephemeral: "Fresh each run", read_only: "Read only" } as Record<string, string>,
    modeNotes: {
      persistent: "What an agent writes stays. One agent at a time.",
      ephemeral: "Every run starts from what's here, and its changes are dropped after. Any number at once.",
      read_only: "Agents read it and can't change it. Any number at once.",
    } as Record<string, string>,
    youCanWrite: "You can still put files in it here, whatever its mode.",
    newVolume: "New volume",
    name: "Name",
    size: "Size (GB)",
    room: "Room left",
    create: "Make volume",
    notEnoughRoom: "Not enough room on this machine.",
    moreContent: "It already holds more than that.",
    inUse: "Something has it mounted, so it can't be looked at or changed right now.",
    used: "used",
    of: "of",
    resize: "Resize",
    delete: "Delete volume",
    deleteConfirm: "Delete for good",
    keep: "Keep it",
    refresh: "Refresh",
    snapshot: "A snapshot — refresh to see changes.",
    open: "Pick a file to open it.",
    pick: "Pick a volume.",
    save: "Save",
    saved: "Saved",
    saving: "Saving…",
    unsaved: "Unsaved changes",
    binary: "Not a text file",
    newFile: "New file",
    newFilePlaceholder: "notes/new.md",
    createFile: "Create",
    empty: "Nothing in here yet.",
  },
  machines: {
    title: "Machines",
    note: "Where your agents can run. The daemon spreads work across them.",
    ours: "The daemon has no way to add a machine, so the app does it.",
    add: "Add a machine",
    dial: "I connect to it",
    accept: "It connects to me",
    name: "Call it",
    namePlaceholder: "studio, laptop, the box under the desk…",
    daemonName: "the daemon knows it as",
    address: "Address",
    addressPlaceholder: "host:port or wss://…",
    identity: "Name it presents as",
    identityPlaceholder: "studio-pc-2",
    key: "Key",
    keyNote: "The key stays in the app's back end. It is never shown again.",
    save: "Add",
    remove: "Remove",
    confirm: "Remove for good",
    keep: "Keep",
    storage: "Storage",
    noStorage: "No storage listed",
    added: "Added",
  },
  views: {
    title: "Views",
    note: "A View is a saved question to an agent's log: which kind of thing, reshaped how, and whether to keep watching.",
    new: "New View",
    untitled: "Untitled View",
    titleLabel: "Title",
    agent: "Agent",
    kind: "Only",
    everything: "Everything",
    jq: "Reshape with jq",
    jqPlaceholder: ".text",
    count: "At most",
    watch: "Keep watching",
    from: "From item",
    to: "To item",
    run: "Run",
    save: "Save View",
    delete: "Delete",
    results: "Results",
    noResults: "Nothing matches yet.",
    ended: "Finished",
    live: "Live",
    presets: "Start from",
    saved: "Saved Views",
    none: "No saved Views yet.",
    presetNames: { tools: "Every tool call", errors: "Errors, live", asked: "What I asked", where: "Where it ran" },
  },
  spaces: {
    youAreHere: "You're here as",
    freshHere: "a name just for this room",
    runBy: "run by",
    yourAgent: "your agent",
    happened: "What's happened",
    table: "Table",
    tableNote: "Everyone in this room sees the same files, and anyone here can change them.",
    tableEmpty: "Nothing on the table yet.",
    newFile: "New file",
    newFilePlaceholder: "notes/idea.md",
    create: "Create",
    save: "Save",
    saved: "Saved",
    copyTo: "Copy to another room's table",
    copied2: "Copied.",
    pick: "Pick a file.",
    admitted: "let in",
    removedLine: "was removed",
    rulesChanged: "The rules changed",
    vouchesFor: "vouches for a room",
    settle: "Settled?",
    settledYes: "Yes, settled",
    settledNo: "Not settled",
    says: "says",
    settledWord: "settled",
    notSettledWord: "not settled",
    receiptSealed: "sealed by",
    yourAgents: "Your agents here",
    allowance: "Moves a day without asking",
    allowanceNote: "Up to this many each day, it acts here without a card. Zero: it always asks.",
    lastActed: "last acted",
    offers: "offers",
    today: "today",
    vouch: "Vouch",
    vouchTitle: "A vouch for",
    vouchNote: "Hand this to them. It's good for a week, at that room only. When they knock there, the host sees you vouch for them, and can check it's yours.",
    vouchInto: "into",
    vouchMake: "Make the vouch",
    knockUnchecked: "This knock doesn't check: it isn't signed by the key it names, or it was made for another room, or it's old. Letting it in could let in someone else.",
    doorways: "Rooms this room vouches for",
    quiet: "The host's machine can't be reached.",
    fromCopy: "What you see is your own copy of this room's record, every seal checked.",
    continueIt: "Continue it on your machine",
    continueNote: "A new room, hosted by you, that carries this one's whole record. The old moves keep their seals. Nobody is let in until you invite them.",
    everyone: "Everyone you let in",
    everyoneNote: "Those who asked not to be listed aren't on the room's list. Its record keeps their names, not their keys, until they act.",
    notListed: "not listed",
    remove: "Remove",
    removeConfirm: "Remove for good",
    removedNote: "They can't act here any more. They can still reach the table until the room restarts.",
    restartNow: "Restart the room now",
    restarted: "Restarted. The table is closed to anyone you removed.",
    invitedKnock: "came with your invite",
    openKnock: "knocked on your open door",
    seenFrom: "seen from",
    vouchedBy: "vouched for by",
    vouchNotHere: "who isn't a member here",
    vouchBroken: "a vouch that doesn't hold here: it's for someone else, another room, or it ran out",
    unlisted: "asked not to be listed",
    hostOpenDoor: "Anyone with the link may knock with a note",
    hostOpenDoorNote: "Without it, only people you hand an invite to can knock.",
    title: "Spaces",
    note: "Rooms you host on your machine, and rooms you've joined. A room is only as reachable as its host.",
    youHost: "You host",
    joined: "You've joined",
    none: "None yet.",
    hostedBy: "hosted by",
    youHostIt: "You host it",
    offline: "Host offline",
    online: "Online",
    members: "members",
    kinds: { home: "Home", board: "Work board", idea: "Idea room", dm: "Direct", profile: "Profile" } as Record<string, string>,
    door: "At the door",
    doorNote: "Someone asked to join a room you host. Their address is what your machine saw; the rest is what they typed.",
    letIn: "Let in",
    notNow: "Not now",
    presented: "presented",
    host: "Host a Space",
    hostNote: "It runs on your machine. Friends join with the invite you hand them.",
    hostTitle: "Title",
    hostKind: "Kind",
    hostCharter: "Charter",
    hostCharterPlaceholder: "What this room is for, and its rules. Markdown is fine.",
    hostInvite: "Invite key",
    hostInviteNote: "What a friend presents at the door. Hand it out with the invite.",
    hostButton: "Host it",
    join: "Join with an invite",
    joinPlaceholder: "diverge://space/…",
    joinAs: "Your name there",
    joinButton: "Join",
    joinDenied: "The host said no.",
    joinMissing: "No room by that invite is running.",
    joinedOk: "You're in.",
    invite: "Invite",
    inviteNote: "Hand this to a friend. They present the key at your door; you decide.",
    copy: "Copy",
    copied: "Copied",
    leave: "Leave",
    end: "End this room",
    confirmLeave: "Leave for good",
    confirmEnd: "End for good",
    keep: "Keep",
    verbs: "Do something here",
    verbsNote: "The room's own verbs. Your agents can use the same ones.",
    charter: "Charter",
    feed: "What's happened",
    feedEmpty: "Nothing yet. Be the first.",
    reply: "Reply",
    claim: "Claim",
    deliver: "Deliver",
    accept: "Accept delivery",
    prefer: "Prefer",
    reject: "Reject",
    noteVerb: "Note",
    do: "Do it",
    cancel: "Cancel",
    did: "Done:",
    by: "by",
    you: "You",
    agent: "agent",
    moveKinds: {
      show: "Show", ask: "Ask", reply: "Reply", say: "", run: "Run", task: "Task", claim: "Claimed", delivery: "Delivered",
      receipt: "Receipt", offering: "Offering", direction: "Direction", steer: "Steered", synthesis: "Where it stands",
      offer: "Offer", settle: "Settled?", hire: "Asked for", hire_answer: "Answer", hire_delivery: "Delivered", note: "Note", pinned_receipt: "Receipt",
    } as Record<string, string>,
    states: { open: "Open", claimed: "Claimed", delivered: "Delivered", done: "Done", issued: "Issued", offered: "Offered", shown: "", said: "", prefer: "preferred", reject: "rejected", note: "noted" } as Record<string, string>,
    fields: { needs: "Needs", ceiling: "Ceiling", who_may_serve: "Who may serve", pricing: "Pricing", terms: "Terms", claimed_by: "Claimed by", pledge: "Pledge", measured: "Measured", to: "To", prefer: "prefer", reject: "reject", note: "notes" } as Record<string, string>,
  },
  cards: {
    asksYou: "asks you",
    waiting: "Waiting on you — the run is paused, using nothing.",
    asksOf: "asks",
    waitingFor: "Nothing runs until you answer.",
    kinds: { question: "A question", choice: "Your call", credential: "A key" } as Record<string, string>,
    credentialNote: "Pick which key to use. The agent is told a key was used, never the value.",
    none: "None of these",
    placeholder: "Your answer",
    send: "Answer",
    railTag: "asks you",
  },
  itemTypes: {
    user_text_content: "What was said to it",
    assistant_text_content: "What it said",
    assistant_reasoning: "Its thinking",
    assistant_tool_call: "Tool calls",
    tool_response: "Tool answers",
    usage: "Measurements",
    notification: "Notices",
    error: "Errors",
    active: "Starts",
    inactive: "Finishes",
    assistant_refusal: "Refusals",
    user_image_content: "Images sent to it",
    user_audio_content: "Audio sent to it",
    user_resource: "Files sent to it",
    user_resource_link: "Links sent to it",
    assistant_image_content: "Images it made",
    assistant_audio_content: "Audio it made",
  } as Record<string, string>,
  keys: {
    unreadable: "Your keys file can't be read, so nothing is sent as you.",
    where: "It's at",
    untouched: "Nothing has written over it, and nothing will until it can be read again.",
  },
  common: {
    close: "Close",
    cancel: "Cancel",
    ok: "OK",
    error: "Something went wrong",
  },
};
