// Every word a person reads in this app lives here, so Maya's naming
// pass is one edit. The words below are PROVISIONAL — names are tabled.

export const t = {
  app: {
    name: "Diverge",
    draft: "draft one",
  },
  rail: {
    agents: "Agents",
    newAgent: "New agent",
    files: "Files",
    machines: "Machines",
    views: "Views",
    refreshed: "Listed just now",
    refreshNote: "The daemon's list isn't live, so this re-asks every few seconds.",
    empty: "No agents yet.",
  },
  standIn: {
    badge: "Stand-in daemon",
    note: "Runs are scripted and nothing leaves this Mac. Ronald's daemon replaces this in one piece.",
    pin: "Built against",
  },
  status: {
    working: "Working",
    idle: "Idle",
    never: "Hasn't run yet",
    on: "on",
  },
  provider: {
    outgoing: "You connect to it",
    incoming: "It connects to you",
  },
  home: {
    title: "Nothing open",
    body: "Pick an agent on the left, or make a new one.",
  },
  convo: {
    you: "You",
    thinking: "Thinking",
    tool: "Used",
    helper: "Helper's work",
    waitingForAnswer: "waiting for an answer",
    failed: "didn't work",
    started: "Started",
    finished: "Finished",
    measured: "Measured",
    tokens: "tokens",
    working: "Working…",
    empty: "No conversation yet. Say something to start it.",
    placeholder: "Message",
    send: "Send",
    queueNote: "It's working. New messages wait in line until it's ready.",
    waiting: "Waiting to be picked up",
    takeBack: "Take back",
    takenBack: "Taken back",
    tooLate: "Already picked up",
    remove: "Remove",
    removeActive: "It's running, so the daemon won't remove it. Try again when it finishes.",
    removeConfirm: "Remove for good",
    removeCancel: "Keep it",
    watching: "Watching live",
    notWatching: "Not watching",
    stopWatching: "Stop watching",
    watch: "Watch live",
    noStop: "A running agent can't be stopped — only messages that haven't been picked up can be taken back.",
    notice: "Notice",
    fatal: "Stopped the run",
    refusal: "Declined",
    arguments: "Asked with",
    answer: "Answer",
    image: "image",
    audio: "audio",
  },
  create: {
    title: "New agent",
    kind: "What kind of agent",
    settings: "Its settings",
    moreSettings: "More settings",
    limits: "Limits",
    limitsNote: "Hard ceilings on the machine it runs on. The daemon has no timeout, so these are the ceilings there are.",
    memory: "Memory (GB)",
    disk: "Disk (GB)",
    where: "Where it runs",
    anywhere: "Wherever the daemon picks",
    anywhereNote: "It keeps its conversation; nothing stays on the machine's disk.",
    pinned: "On one machine",
    pinnedNote: "Needed to use that machine's storage.",
    machine: "Machine",
    storage: "Storage from that machine",
    addStorage: "Add storage",
    volume: "Storage",
    inVolume: "Folder in it",
    inAgent: "Shows up as",
    share: "Share from this computer",
    shareNote: "Live: the agent sees changes as you make them, and asks before changing anything.",
    addShare: "Share a folder",
    addFileShare: "Share a file",
    here: "On this computer",
    name: "Name",
    namePlaceholder: "a-name-you-will-recognise",
    first: "First message",
    firstPlaceholder: "What should it do? (optional)",
    create: "Make agent",
    creating: "Making…",
    inUse: "That name is taken.",
    ready: "These settings are ones this agent accepts.",
    fillIn: "Still to fill in:",
    notReady: "Not accepted yet:",
    needed: "needed",
    remove: "Remove",
    add: "Add",
    none: "None",
    default: "Default",
    on: "On",
    off: "Off",
    json: "Any JSON",
    key: "Name",
    value: "Value",
    kinds: {
      cc: { title: "Claude Code", blurb: "Reads, edits and runs code." },
      codex: { title: "Codex", blurb: "OpenAI's coding agent." },
      hermes: { title: "Hermes", blurb: "A general agent: any of 40+ model providers, and toolsets." },
      openrouter: { title: "OpenRouter", blurb: "Any model through OpenRouter, every dial exposed." },
      eliza: { title: "Eliza", blurb: "A character, with a personality and memory." },
      python: { title: "Python", blurb: "Your own loop, in Python." },
    } as Record<string, { title: string; blurb: string }>,
  },
  files: {
    title: "Files",
    note: "Files on the machine the daemon runs on.",
    open: "Pick a file to open it.",
    save: "Save",
    saved: "Saved",
    saving: "Saving…",
    unsaved: "Unsaved changes",
    binary: "Not a text file",
    newFile: "New file",
    newFilePlaceholder: "/notes/new.md",
    create: "Create",
    bytes: "bytes",
    stale: "Not watched — may be out of date",
  },
  machines: {
    title: "Machines",
    note: "Where your agents can run. The daemon spreads work across them.",
    ours: "Adding machines here is ours until Ronald's daemon has a way to do it.",
    add: "Add a machine",
    dial: "I connect to it",
    accept: "It connects to me",
    address: "Address",
    addressPlaceholder: "host:port or wss://…",
    identity: "Name it presents as",
    identityPlaceholder: "studio-pc-2",
    key: "Key",
    keyNote: "The key stays in the app's back end. It is never shown again.",
    save: "Add",
    remove: "Remove",
    confirm: "Remove for good",
    keep: "Keep",
    storage: "Storage",
    noStorage: "No storage listed",
    added: "Added",
  },
  views: {
    title: "Views",
    note: "A View is a saved question to an agent's log: which kind of thing, reshaped how, and whether to keep watching.",
    new: "New View",
    untitled: "Untitled View",
    titleLabel: "Title",
    agent: "Agent",
    kind: "Only",
    everything: "Everything",
    jq: "Reshape with jq",
    jqPlaceholder: ".text",
    count: "At most",
    watch: "Keep watching",
    from: "From item",
    to: "To item",
    run: "Run",
    save: "Save View",
    delete: "Delete",
    results: "Results",
    noResults: "Nothing matches yet.",
    ended: "Finished",
    live: "Live",
    presets: "Start from",
    saved: "Saved Views",
    none: "No saved Views yet.",
    presetNames: { tools: "Every tool call", errors: "Errors, live", asked: "What I asked", where: "Where it ran" },
  },
  itemTypes: {
    user_text_content: "What was said to it",
    assistant_text_content: "What it said",
    assistant_reasoning: "Its thinking",
    assistant_tool_call: "Tool calls",
    tool_response: "Tool answers",
    usage: "Measurements",
    notification: "Notices",
    error: "Errors",
    active: "Starts",
    inactive: "Finishes",
    assistant_refusal: "Refusals",
    user_image_content: "Images sent to it",
    user_audio_content: "Audio sent to it",
    user_resource: "Files sent to it",
    user_resource_link: "Links sent to it",
    assistant_image_content: "Images it made",
    assistant_audio_content: "Audio it made",
  } as Record<string, string>,
  common: {
    close: "Close",
    ok: "OK",
    error: "Something went wrong",
  },
};
