// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandApiConfigHttpRefererSetResponseSchemaPathSchema = z.literal("api/config/http_referer/set/response_schema").meta({ title: "cli.command.api.config.http_referer.set.response_schema.Path" });
export type CliCommandApiConfigHttpRefererSetResponseSchemaPath = z.infer<typeof CliCommandApiConfigHttpRefererSetResponseSchemaPathSchema>;
