// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsResponseMessagesAudioClearRequestSchemaPathSchema } from "./path";

export const CliCommandLogsAgentsCompletionsResponseMessagesAudioClearRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandLogsAgentsCompletionsResponseMessagesAudioClearRequestSchemaPathSchema,
}).meta({ title: "cli.command.logs.agents.completions.response.messages.audio.clear.request_schema.Request" });
export type CliCommandLogsAgentsCompletionsResponseMessagesAudioClearRequestSchemaRequest = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesAudioClearRequestSchemaRequestSchema>;
