# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_response_item_all():
    from objectiveai_sdk.cli.command.agents.read import ResponseItemAll
    schema = ResponseItemAll.model_json_schema()
