# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_pair_favorite():
    from objectiveai_sdk.filesystem.config import PairFavorite
    schema = PairFavorite.model_json_schema()
