# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.mcp.shared.icon_theme import IconTheme


class Icon(BaseModel):
    """An icon that can be displayed in a user interface."""
    model_config = ConfigDict(title='mcp.shared.Icon')

    mime_type: Optional[str] = Field(None, alias='mimeType', description='MIME type for the icon.', json_schema_extra={'omitempty': True})
    sizes: Optional[list[str]] = Field(None, description='Sizes at which the icon can be used (e.g., "48x48", "96x96", "any").', json_schema_extra={'omitempty': True})
    src: str = Field(..., description='URL or data URI for the icon.')
    theme: Optional[IconTheme] = Field(None, description='Theme this icon is intended for.', json_schema_extra={'omitempty': True})

