// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandAgentsResourcesReadRequestSchemaPathSchema = z.literal("agents/resources/read/request_schema").meta({ title: "cli.command.agents.resources.read.request_schema.Path" });
export type CliCommandAgentsResourcesReadRequestSchemaPath = z.infer<typeof CliCommandAgentsResourcesReadRequestSchemaPathSchema>;
