# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_laboratory_execution_request_continue():
    from objectiveai_sdk.http.viewer import LaboratoryExecutionRequestContinue
    schema = LaboratoryExecutionRequestContinue.model_json_schema()
