# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_function_invention_recursive_request_error():
    from objectiveai_sdk.http_.viewer import FunctionInventionRecursiveRequestError
    schema = FunctionInventionRecursiveRequestError.model_json_schema()
