# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_request():
    from objectiveai_sdk.http_.viewer import Request
    schema = Request.model_json_schema()
