// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandAgentsQueueReadPendingResponseSchemaPathSchema } from "./path";

export const CliCommandAgentsQueueReadPendingResponseSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandAgentsQueueReadPendingResponseSchemaPathSchema,
}).meta({ title: "cli.command.agents.queue.read.pending.response_schema.Request" });
export type CliCommandAgentsQueueReadPendingResponseSchemaRequest = z.infer<typeof CliCommandAgentsQueueReadPendingResponseSchemaRequestSchema>;
