// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliOutputNotificationOkSchema = z.object({
  ok: z.boolean(),
}).describe("Wire shape for silent-success notifications (`config set`,\n`favorites add/del/edit`, `instructions clear`, etc.). Wire:\n`{\"type\":\"notification\",\"ok\":true}`.").meta({ title: "cli.output.notification.Ok" });
export type CliOutputNotificationOk = z.infer<typeof CliOutputNotificationOkSchema>;
