// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberView } from "./MemberView";
import type { SpaceSummary } from "./SpaceSummary";
import type { ToolView } from "./ToolView";

export type SpaceView = { summary: SpaceSummary, charter: string, members: Array<MemberView>, tools: Array<ToolView>, };
