// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every volume change's answer, in the screen's words.
 */
export type VolumeChange = { "outcome": "done" } | { "outcome": "not_enough_room" } | { "outcome": "more_content_than_that" } | { "outcome": "in_use" } | { "outcome": "error", message: string, };
