# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_request_tasks():
    from objectiveai_sdk.cli.command import RequestTasks
    schema = RequestTasks.model_json_schema()
