// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandConfigFunctionsProfilesFavoritesDelResponseSchemaPathSchema = z.literal("config/functions/profiles/favorites/del/response_schema").meta({ title: "cli.command.config.functions.profiles.favorites.del.response_schema.Path" });
export type CliCommandConfigFunctionsProfilesFavoritesDelResponseSchemaPath = z.infer<typeof CliCommandConfigFunctionsProfilesFavoritesDelResponseSchemaPathSchema>;
