# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.functions.executions.response.unary.vector_completion_task import VectorCompletionTask


class TaskFunctionExecution(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'FunctionExecution'})

    root: FunctionExecutionTask


class TaskVectorCompletion(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'VectorCompletion'})

    root: VectorCompletionTask


class Task(RootModel):
    model_config = ConfigDict(title='functions.executions.response.unary.Task')

    root: Union[TaskFunctionExecution, TaskVectorCompletion]


# Deferred imports to break circular dependencies
from objectiveai_sdk.functions.executions.response.unary.function_execution_task import FunctionExecutionTask  # noqa: E402
