// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsResponseMessagesAssistantSubscribeRequestSchemaPathSchema } from "./path";

export const CliCommandLogsAgentsCompletionsResponseMessagesAssistantSubscribeRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandLogsAgentsCompletionsResponseMessagesAssistantSubscribeRequestSchemaPathSchema,
}).meta({ title: "cli.command.logs.agents.completions.response.messages.assistant.subscribe.request_schema.Request" });
export type CliCommandLogsAgentsCompletionsResponseMessagesAssistantSubscribeRequestSchemaRequest = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesAssistantSubscribeRequestSchemaRequestSchema>;
