# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.agents.logs.list.viewer_request import ViewerRequest as CliCommandAgentsLogsListViewerRequest
from objectiveai_sdk.cli.command.agents.logs.open.viewer_request import ViewerRequest as CliCommandAgentsLogsOpenViewerRequest
from objectiveai_sdk.cli.command.agents.logs.subscribe.viewer_request import ViewerRequest as CliCommandAgentsLogsSubscribeViewerRequest
from objectiveai_sdk.cli.command.agents.logs.token_usage.viewer_request import ViewerRequest as CliCommandAgentsLogsTokenUsageViewerRequest


class ViewerRequestOpen(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Open'})

    root: CliCommandAgentsLogsOpenViewerRequest


class ViewerRequestList(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'List'})

    root: CliCommandAgentsLogsListViewerRequest


class ViewerRequestSubscribe(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Subscribe'})

    root: CliCommandAgentsLogsSubscribeViewerRequest


class ViewerRequestTokenUsage(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'TokenUsage'})

    root: CliCommandAgentsLogsTokenUsageViewerRequest


class ViewerRequest(RootModel):
    """Viewer-stream mirror of [`Request`] — the real command requests only
(schema-introspection variants are excluded; the viewer streams
actual command traffic). Untagged: each variant carries the leaf's
`path_type`, so it stays discriminable."""
    model_config = ConfigDict(title='cli.command.agents.logs.ViewerRequest')

    root: Union[ViewerRequestOpen, ViewerRequestList, ViewerRequestSubscribe, ViewerRequestTokenUsage]

