# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_viewer_route():
    from objectiveai_sdk.filesystem.plugins import ViewerRoute
    schema = ViewerRoute.model_json_schema()
