# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_request_github_authorization():
    from objectiveai_sdk.cli.command.api.config import RequestGithubAuthorization
    schema = RequestGithubAuthorization.model_json_schema()
