# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_viewer_request_x_title():
    from objectiveai_sdk.cli.command.api.config import ViewerRequestXTitle
    schema = ViewerRequestXTitle.model_json_schema()
