# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.functions.inventions.recursive.create.request import Request as CliCommandFunctionsInventionsRecursiveCreateRequest
from objectiveai_sdk.cli.command.functions.inventions.state.request import Request as CliCommandFunctionsInventionsStateRequest


class RequestRecursive(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Recursive'})

    root: CliCommandFunctionsInventionsRecursiveCreateRequest


class RequestState(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'State'})

    root: CliCommandFunctionsInventionsStateRequest


class Request(RootModel):
    model_config = ConfigDict(title='cli.command.functions.inventions.Request')

    root: Union[RequestRecursive, RequestState]

