# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.mcp.tasks_tools_capability import TasksToolsCapability


class TasksRequestsCapability(BaseModel):
    """Task creation capabilities scoped to request types."""
    model_config = ConfigDict(title='mcp.TasksRequestsCapability')

    tools: Optional[TasksToolsCapability] = Field(None, description='Task support for tool-related requests.', json_schema_extra={'omitempty': True})

