// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsResponseClearPathSchema } from "./path";

export const CliCommandLogsAgentsCompletionsResponseClearRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  nested: z.boolean(),
  path_type: CliCommandLogsAgentsCompletionsResponseClearPathSchema,
}).meta({ title: "cli.command.logs.agents.completions.response.clear.Request" });
export type CliCommandLogsAgentsCompletionsResponseClearRequest = z.infer<typeof CliCommandLogsAgentsCompletionsResponseClearRequestSchema>;
