// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandConfigViewerSecretSetRequestSchemaPathSchema } from "./path";

export const CliCommandConfigViewerSecretSetRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandConfigViewerSecretSetRequestSchemaPathSchema,
}).meta({ title: "cli.command.config.viewer.secret.set.request_schema.Request" });
export type CliCommandConfigViewerSecretSetRequestSchemaRequest = z.infer<typeof CliCommandConfigViewerSecretSetRequestSchemaRequestSchema>;
