# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from objectiveai_sdk.json_value import JsonValue
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.agent.completions.message.file import File
from objectiveai_sdk.cli.command.logs.agents.completions.response.messages.assistant.file.clear.response import Response as CliCommandLogsAgentsCompletionsResponseMessagesAssistantFileClearResponse


class ResponseClear(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Clear'})

    root: CliCommandLogsAgentsCompletionsResponseMessagesAssistantFileClearResponse


class ResponseClearRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'ClearRequestSchema'})

    root: JsonValue


class ResponseClearResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'ClearResponseSchema'})

    root: JsonValue


class ResponseGet(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Get'})

    root: File


class ResponseGetRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetRequestSchema'})

    root: JsonValue


class ResponseGetResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetResponseSchema'})

    root: JsonValue


class ResponseSubscribe(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Subscribe'})

    root: File


class ResponseSubscribeRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'SubscribeRequestSchema'})

    root: JsonValue


class ResponseSubscribeResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'SubscribeResponseSchema'})

    root: JsonValue


class Response(RootModel):
    model_config = ConfigDict(title='cli.command.logs.agents.completions.response.messages.assistant.file.Response')

    root: Union[ResponseClear, ResponseClearRequestSchema, ResponseClearResponseSchema, ResponseGet, ResponseGetRequestSchema, ResponseGetResponseSchema, ResponseSubscribe, ResponseSubscribeRequestSchema, ResponseSubscribeResponseSchema]

