// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { JsonValueSchema } from "../jsonValue";

export const McpJsonRpcNotificationSchema = z.object({
  jsonrpc: z.string(),
  method: z.string(),
  params: JsonValueSchema.meta({ omitempty: true }),
}).describe("JSON-RPC 2.0 notification (no `id` field).").meta({ title: "mcp.JsonRpcNotification" });
export type McpJsonRpcNotification = z.infer<typeof McpJsonRpcNotificationSchema>;
