// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type AgentUpstreamUnknown string

func (AgentUpstreamUnknown) SchemaVariantTitle() string { return "Unknown" }

type AgentUpstreamOpenrouter string

func (AgentUpstreamOpenrouter) SchemaVariantTitle() string { return "Openrouter" }

type AgentUpstreamClaudeAgentSdk string

func (AgentUpstreamClaudeAgentSdk) SchemaVariantTitle() string { return "ClaudeAgentSdk" }

type AgentUpstreamCodexSdk string

func (AgentUpstreamCodexSdk) SchemaVariantTitle() string { return "CodexSdk" }

type AgentUpstreamMock string

func (AgentUpstreamMock) SchemaVariantTitle() string { return "Mock" }

type AgentUpstreamScript string

func (AgentUpstreamScript) SchemaVariantTitle() string { return "Script" }

// Supported agent upstreams.
type AgentUpstream struct {
	// Unknown Upstream.
	Unknown *AgentUpstreamUnknown `validate:"omitempty,oneof=unknown"`
	// OpenRouter Upstream.
	Openrouter *AgentUpstreamOpenrouter `validate:"omitempty,oneof=openrouter"`
	// Claude Agent SDK Upstream.
	ClaudeAgentSdk *AgentUpstreamClaudeAgentSdk `validate:"omitempty,oneof=claude_agent_sdk"`
	// Codex SDK Upstream.
	CodexSdk *AgentUpstreamCodexSdk `validate:"omitempty,oneof=codex_sdk"`
	// Mock Upstream.
	Mock *AgentUpstreamMock `validate:"omitempty,oneof=mock"`
	// Script Upstream.
	Script *AgentUpstreamScript `validate:"omitempty,oneof=script"`
}

func (v AgentUpstream) MarshalJSON() ([]byte, error) {
	if v.Unknown != nil {
		return json.Marshal(v.Unknown)
	}
	if v.Openrouter != nil {
		return json.Marshal(v.Openrouter)
	}
	if v.ClaudeAgentSdk != nil {
		return json.Marshal(v.ClaudeAgentSdk)
	}
	if v.CodexSdk != nil {
		return json.Marshal(v.CodexSdk)
	}
	if v.Mock != nil {
		return json.Marshal(v.Mock)
	}
	if v.Script != nil {
		return json.Marshal(v.Script)
	}
	return []byte("null"), nil
}

func (v *AgentUpstream) UnmarshalJSON(data []byte) error {
	{
		var try AgentUpstreamUnknown
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentUpstream{}
			candidate.Unknown = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentUpstreamOpenrouter
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentUpstream{}
			candidate.Openrouter = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentUpstreamClaudeAgentSdk
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentUpstream{}
			candidate.ClaudeAgentSdk = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentUpstreamCodexSdk
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentUpstream{}
			candidate.CodexSdk = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentUpstreamMock
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentUpstream{}
			candidate.Mock = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentUpstreamScript
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentUpstream{}
			candidate.Script = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentUpstream")
}

func (v AgentUpstream) Validate() error {
	count := 0
	if v.Unknown != nil { count++ }
	if v.Openrouter != nil { count++ }
	if v.ClaudeAgentSdk != nil { count++ }
	if v.CodexSdk != nil { count++ }
	if v.Mock != nil { count++ }
	if v.Script != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentUpstream: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (AgentUpstream) SchemaTitle() string { return "agent.Upstream" }

