// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// A chunk of a streaming agent completion response.
//
// Multiple chunks are received via Server-Sent Events and can be
// accumulated into a complete [`AgentCompletion`](response::unary::AgentCompletion)
// using the [`push`](Self::push) method.
type AgentCompletionsResponseStreamingAssistantResponseChunk struct {
	Content *AgentCompletionsMessageRichContent `json:"content,omitempty"`
	Created uint64 `json:"created" validate:"min=0,max=18446744073709551615"`
	FinishReason *AgentCompletionsResponseFinishReason `json:"finish_reason"`
	Index uint64 `json:"index" validate:"min=0,max=18446744073709551615"`
	Logprobs *AgentCompletionsResponseLogprobs `json:"logprobs,omitempty"`
	Model string `json:"model"`
	Provider *string `json:"provider,omitempty"`
	Reasoning *string `json:"reasoning,omitempty"`
	Refusal *string `json:"refusal,omitempty"`
	// `message_queue_contents.id`s the API consumed to seed this
	// turn's request. Stamped onto the first assistant chunk the
	// API emits downstream — when set, the consumer owns these
	// rows. Kinds are resolved CLI-side at write time (SQL CASE
	// against `message_queue_contents.kind`), so the wire stays
	// `i64`-only. Both `None` and `Some(empty)` are skipped on
	// serialize.
	RequestMessageIds *[]int64 `json:"request_message_ids,omitempty" validate:"omitempty,dive,min=-9223372036854775808,max=9223372036854775807"`
	Role AgentCompletionsResponseAssistantRole `json:"role"`
	ServiceTier *string `json:"service_tier,omitempty"`
	SystemFingerprint *string `json:"system_fingerprint,omitempty"`
	ToolCalls *[]AgentCompletionsMessageAssistantToolCallDelta `json:"tool_calls,omitempty"`
	UpstreamID string `json:"upstream_id"`
	// Upstream usage for this assistant response (set by upstream clients).
	Usage *AgentCompletionsResponseUpstreamUsage `json:"usage,omitempty"`
}

func (AgentCompletionsResponseStreamingAssistantResponseChunk) SchemaTitle() string { return "agent.completions.response.streaming.AssistantResponseChunk" }
func (v AgentCompletionsResponseStreamingAssistantResponseChunk) Validate() error {
	return variantValidator.Struct(v)
}

func (v *AgentCompletionsResponseStreamingAssistantResponseChunk) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"created", "index", "model", "role", "upstream_id"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("AgentCompletionsResponseStreamingAssistantResponseChunk: missing required field %q", key)
		}
	}
	type Alias AgentCompletionsResponseStreamingAssistantResponseChunk
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = AgentCompletionsResponseStreamingAssistantResponseChunk(alias)
	return nil
}
