// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type AgentCompletionsResponseUnaryMessage struct {
	Assistant *AgentCompletionsResponseUnaryAssistantResponse 
	Tool *AgentCompletionsResponseToolResponse 
}

func (v AgentCompletionsResponseUnaryMessage) MarshalJSON() ([]byte, error) {
	if v.Assistant != nil {
		return json.Marshal(v.Assistant)
	}
	if v.Tool != nil {
		return json.Marshal(v.Tool)
	}
	return []byte("null"), nil
}

func (v *AgentCompletionsResponseUnaryMessage) UnmarshalJSON(data []byte) error {
	{
		var try AgentCompletionsResponseUnaryAssistantResponse
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsResponseUnaryMessage{}
			candidate.Assistant = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentCompletionsResponseToolResponse
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsResponseUnaryMessage{}
			candidate.Tool = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentCompletionsResponseUnaryMessage")
}

func (v AgentCompletionsResponseUnaryMessage) Validate() error {
	count := 0
	if v.Assistant != nil { count++ }
	if v.Tool != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentCompletionsResponseUnaryMessage: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (AgentCompletionsResponseUnaryMessage) SchemaTitle() string { return "agent.completions.response.unary.Message" }

