// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type AgentFavoritesAction struct {
	Added *string `validate:"omitempty,oneof=added"`
	Edited *string `validate:"omitempty,oneof=edited"`
	Removed *string `validate:"omitempty,oneof=removed"`
}

func (v AgentFavoritesAction) MarshalJSON() ([]byte, error) {
	if v.Added != nil {
		return json.Marshal(v.Added)
	}
	if v.Edited != nil {
		return json.Marshal(v.Edited)
	}
	if v.Removed != nil {
		return json.Marshal(v.Removed)
	}
	return []byte("null"), nil
}

func (v *AgentFavoritesAction) UnmarshalJSON(data []byte) error {
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentFavoritesAction{}
			candidate.Added = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentFavoritesAction{}
			candidate.Edited = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentFavoritesAction{}
			candidate.Removed = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentFavoritesAction")
}

func (v AgentFavoritesAction) Validate() error {
	count := 0
	if v.Added != nil { count++ }
	if v.Edited != nil { count++ }
	if v.Removed != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentFavoritesAction: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (AgentFavoritesAction) SchemaTitle() string { return "agent.favorites.Action" }

