// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// One `mcp_servers` entry on a
// [`ClientObjectiveaiMcpPluginEntry`]: the manifest-declared `name`
// the agent wants exposed, plus optional `arguments` the CLI feeds
// to the plugin alongside the name when bringing the server up. The
// arguments map is sorted by key in [`prepare`] so two equivalent
// declarations (same key/value pairs in any order) hash to the same
// canonical form.
type AgentClientObjectiveaiMcpPluginMcpServer struct {
	// Optional key→value arguments forwarded to the plugin alongside
	// `name`. `Some(value)` ⇒ `--key value` on the spawned plugin's
	// argv; `None` ⇒ a bare `--key` flag with no following token. The
	// plugin author decides how to interpret them. [`prepare`]
	// normalizes (`Some("") → None`), sorts the map by key, and
	// collapses an empty map to `None` so two equivalent declarations
	// canonicalize to byte-identical JSON.
	Arguments *OrderedMap[string, *string] `json:"arguments,omitempty"`
	// Author-chosen identifier — must match a `name` in the plugin
	// manifest's `mcp_servers` list. The CLI feeds this as the
	// first positional arg when starting the plugin.
	Name string `json:"name"`
}

func (AgentClientObjectiveaiMcpPluginMcpServer) SchemaTitle() string { return "agent.ClientObjectiveaiMcpPluginMcpServer" }
func (v AgentClientObjectiveaiMcpPluginMcpServer) Validate() error {
	return variantValidator.Struct(v)
}

func (v *AgentClientObjectiveaiMcpPluginMcpServer) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"name"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("AgentClientObjectiveaiMcpPluginMcpServer: missing required field %q", key)
		}
	}
	type Alias AgentClientObjectiveaiMcpPluginMcpServer
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = AgentClientObjectiveaiMcpPluginMcpServer(alias)
	return nil
}
