// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type CliCommandViewerConfigSecretGetResponse struct {
	Secret *string `json:"secret,omitempty"`
}

func (CliCommandViewerConfigSecretGetResponse) SchemaTitle() string { return "cli.command.viewer.config.secret.get.Response" }
func (v CliCommandViewerConfigSecretGetResponse) Validate() error {
	return variantValidator.Struct(v)
}
