// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandViewerConfigGetResponseSchemaRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandViewerConfigGetResponseSchemaPath `json:"path_type"`
}

func (CliCommandViewerConfigGetResponseSchemaRequest) SchemaTitle() string { return "cli.command.viewer.config.get.response_schema.Request" }
func (v CliCommandViewerConfigGetResponseSchemaRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandViewerConfigGetResponseSchemaRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandViewerConfigGetResponseSchemaRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandViewerConfigGetResponseSchemaRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandViewerConfigGetResponseSchemaRequest(alias)
	return nil
}
