// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandFunctionsInventionsStateGetRequestSchemaRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandFunctionsInventionsStateGetRequestSchemaPath `json:"path_type"`
}

func (CliCommandFunctionsInventionsStateGetRequestSchemaRequest) SchemaTitle() string { return "cli.command.functions.inventions.state.get.request_schema.Request" }
func (v CliCommandFunctionsInventionsStateGetRequestSchemaRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandFunctionsInventionsStateGetRequestSchemaRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandFunctionsInventionsStateGetRequestSchemaRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandFunctionsInventionsStateGetRequestSchemaRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandFunctionsInventionsStateGetRequestSchemaRequest(alias)
	return nil
}
