// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandApiKillRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandApiKillPath `json:"path_type"`
	// Always Global — api has a single machine-wide lock.
	Scope CliCommandSetScope `json:"scope"`
}

func (CliCommandApiKillRequest) SchemaTitle() string { return "cli.command.api.kill.Request" }
func (v CliCommandApiKillRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandApiKillRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type", "scope"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandApiKillRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandApiKillRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandApiKillRequest(alias)
	return nil
}
