// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// One per-task completion summary (default mode): the same schedule
// identity as [`ValueResponseItem`], with `success` in lieu of
// `value`. `success` is `false` iff the task's FINAL emitted item was
// an error (a task that emitted nothing is a success). The task's
// full output is in `tasks_logs` regardless.
type CliCommandTasksRunSuccessResponseItem struct {
	// The source schedule's `agent_instance_hierarchy`.
	AgentInstanceHierarchy string `json:"agent_instance_hierarchy"`
	// The source schedule's `--name`.
	Name string `json:"name"`
	// The plugin that registered the source schedule, if any.
	Plugin *CliCommandTasksListPlugin `json:"plugin,omitempty"`
	// Whether the task's stream completed without a trailing error.
	Success bool `json:"success"`
	// The source schedule's version (`1` on first creation,
	// incremented per `schedule --overwrite`).
	Version uint64 `json:"version" validate:"min=0,max=18446744073709551615"`
}

func (CliCommandTasksRunSuccessResponseItem) SchemaTitle() string { return "cli.command.tasks.run.SuccessResponseItem" }
func (v CliCommandTasksRunSuccessResponseItem) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandTasksRunSuccessResponseItem) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"agent_instance_hierarchy", "name", "success", "version"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandTasksRunSuccessResponseItem: missing required field %q", key)
		}
	}
	type Alias CliCommandTasksRunSuccessResponseItem
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandTasksRunSuccessResponseItem(alias)
	return nil
}
