// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandChannelsLogsSubscribeRequestSchemaPath struct {
	ChannelsLogsSubscribeRequestSchema string `validate:"omitempty,oneof=channels/logs/subscribe/request_schema" variantTitle:"Channels/logs/subscribe/requestSchema"`
}

func (v CliCommandChannelsLogsSubscribeRequestSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.ChannelsLogsSubscribeRequestSchema)
}

func (v *CliCommandChannelsLogsSubscribeRequestSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.ChannelsLogsSubscribeRequestSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandChannelsLogsSubscribeRequestSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandChannelsLogsSubscribeRequestSchemaPath) SchemaTitle() string { return "cli.command.channels.logs.subscribe.request_schema.Path" }

