// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandConfigFunctionsGetRequest struct {
	Filter *string `json:"filter"`
	Jq *string `json:"jq"`
	PathType CliCommandConfigFunctionsGetPath `json:"path_type"`
}

func (CliCommandConfigFunctionsGetRequest) SchemaTitle() string { return "cli.command.config.functions.get.Request" }
func (v CliCommandConfigFunctionsGetRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandConfigFunctionsGetRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandConfigFunctionsGetRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandConfigFunctionsGetRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandConfigFunctionsGetRequest(alias)
	return nil
}
