// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandDevelopmentPluginsMcpResetRequest struct {
	// Also delete the plugin's build CACHE directories.
	//
	// Off by default, and that default is the point: this command
	// runs after every edit, and the caches are the only reason the
	// rebuild it triggers is fast. Ask for this when a cache is
	// corrupt or a toolchain changed, not routinely.
	Caches bool `json:"caches" default:"false"`
	// jq filter applied to the JSON output. Ignored when `python`
	// is also set — python overrides jq.
	Jq *string `json:"jq"`
	// Response token budget, `>= 1` (`0` is rejected at parse
	// time — omit entirely for unlimited). Forward-compatible
	// envelope data — no leaf enforces it yet.
	MaxTokens *uint64 `json:"max_tokens,omitempty" validate:"omitempty,min=0,max=18446744073709551615"`
	// Repository segment, likewise lowercased.
	Name string `json:"name"`
	// GitHub `<owner>` segment, lowercased on arrival.
	Owner string `json:"owner"`
	PathType CliCommandDevelopmentPluginsMcpResetPath `json:"path_type"`
	// Python transform applied to the JSON output. Overrides `jq`
	// when both are provided.
	Python *string `json:"python"`
	// Wall-clock execution cap, in whole seconds. Parsed from
	// `--timeout` (humantime: `30s`, `5m`, `1h30m`), `> 0`
	// enforced at parse time. `db query` threads it to postgres
	// when set; omit for uncapped.
	TimeoutSeconds *uint64 `json:"timeout_seconds,omitempty" validate:"omitempty,min=0,max=18446744073709551615"`
	// Plugin version — with owner and name, it derives the image tag.
	Version string `json:"version"`
}

func (CliCommandDevelopmentPluginsMcpResetRequest) SchemaTitle() string { return "cli.command.development.plugins.mcp.reset.Request" }
func (v CliCommandDevelopmentPluginsMcpResetRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandDevelopmentPluginsMcpResetRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"caches", "name", "owner", "path_type", "version"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandDevelopmentPluginsMcpResetRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandDevelopmentPluginsMcpResetRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandDevelopmentPluginsMcpResetRequest(alias)
	return nil
}
