// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Result of `functions inventions state get`.
//
// Wire: `{"type":"notification","state":{...GetFunctionInventionStateResponse...}}`.
type CliOutputNotificationFunctionsInventionsState struct {
	State FunctionsInventionsStateGetFunctionInventionStateResponse `json:"state"`
}

func (CliOutputNotificationFunctionsInventionsState) SchemaTitle() string { return "cli.output.notification.functions.inventions.State" }
func (v CliOutputNotificationFunctionsInventionsState) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliOutputNotificationFunctionsInventionsState) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"state"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliOutputNotificationFunctionsInventionsState: missing required field %q", key)
		}
	}
	type Alias CliOutputNotificationFunctionsInventionsState
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliOutputNotificationFunctionsInventionsState(alias)
	return nil
}
