// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandConfigFunctionsInventionsGetRequestSchemaRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandConfigFunctionsInventionsGetRequestSchemaPath `json:"path_type"`
}

func (CliCommandConfigFunctionsInventionsGetRequestSchemaRequest) SchemaTitle() string { return "cli.command.config.functions.inventions.get.request_schema.Request" }
func (v CliCommandConfigFunctionsInventionsGetRequestSchemaRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandConfigFunctionsInventionsGetRequestSchemaRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandConfigFunctionsInventionsGetRequestSchemaRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandConfigFunctionsInventionsGetRequestSchemaRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandConfigFunctionsInventionsGetRequestSchemaRequest(alias)
	return nil
}
