// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandChannelsLogsRequestResponseSchemaPath struct {
	ChannelsLogsRequestResponseSchema string `validate:"omitempty,oneof=channels/logs/request/response_schema" variantTitle:"Channels/logs/request/responseSchema"`
}

func (v CliCommandChannelsLogsRequestResponseSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.ChannelsLogsRequestResponseSchema)
}

func (v *CliCommandChannelsLogsRequestResponseSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.ChannelsLogsRequestResponseSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandChannelsLogsRequestResponseSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandChannelsLogsRequestResponseSchemaPath) SchemaTitle() string { return "cli.command.channels.logs.request.response_schema.Path" }

