// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandConfigAgentsFavoritesGetResponseItemGithub struct {
	Commit *string `json:"commit"`
	Name string `json:"name"`
	Note string `json:"note"`
	Owner string `json:"owner"`
	Remote string `json:"remote" validate:"oneof=github"`
	Repository string `json:"repository"`
}

func (v *CliCommandConfigAgentsFavoritesGetResponseItemGithub) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"name", "note", "owner", "remote", "repository"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandConfigAgentsFavoritesGetResponseItemGithub: missing required field %q", key)
		}
	}
	type Alias CliCommandConfigAgentsFavoritesGetResponseItemGithub
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandConfigAgentsFavoritesGetResponseItemGithub(alias)
	return nil
}
func (CliCommandConfigAgentsFavoritesGetResponseItemGithub) SchemaVariantTitle() string { return "Github" }

type CliCommandConfigAgentsFavoritesGetResponseItemFilesystem struct {
	Commit *string `json:"commit"`
	Name string `json:"name"`
	Note string `json:"note"`
	Owner string `json:"owner"`
	Remote string `json:"remote" validate:"oneof=filesystem"`
	Repository string `json:"repository"`
}

func (v *CliCommandConfigAgentsFavoritesGetResponseItemFilesystem) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"name", "note", "owner", "remote", "repository"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandConfigAgentsFavoritesGetResponseItemFilesystem: missing required field %q", key)
		}
	}
	type Alias CliCommandConfigAgentsFavoritesGetResponseItemFilesystem
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandConfigAgentsFavoritesGetResponseItemFilesystem(alias)
	return nil
}
func (CliCommandConfigAgentsFavoritesGetResponseItemFilesystem) SchemaVariantTitle() string { return "Filesystem" }

type CliCommandConfigAgentsFavoritesGetResponseItemMock struct {
	Name string `json:"name"`
	Note string `json:"note"`
	Remote string `json:"remote" validate:"oneof=mock"`
}

func (v *CliCommandConfigAgentsFavoritesGetResponseItemMock) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"name", "note", "remote"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandConfigAgentsFavoritesGetResponseItemMock: missing required field %q", key)
		}
	}
	type Alias CliCommandConfigAgentsFavoritesGetResponseItemMock
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandConfigAgentsFavoritesGetResponseItemMock(alias)
	return nil
}
func (CliCommandConfigAgentsFavoritesGetResponseItemMock) SchemaVariantTitle() string { return "Mock" }

type CliCommandConfigAgentsFavoritesGetResponseItem struct {
	Github *CliCommandConfigAgentsFavoritesGetResponseItemGithub `outerObject:"true"`
	Filesystem *CliCommandConfigAgentsFavoritesGetResponseItemFilesystem `outerObject:"true"`
	Mock *CliCommandConfigAgentsFavoritesGetResponseItemMock `outerObject:"true"`
}

func (v CliCommandConfigAgentsFavoritesGetResponseItem) MarshalJSON() ([]byte, error) {
	if v.Github != nil {
		return json.Marshal(v.Github)
	}
	if v.Filesystem != nil {
		return json.Marshal(v.Filesystem)
	}
	if v.Mock != nil {
		return json.Marshal(v.Mock)
	}
	return []byte("null"), nil
}

func (v *CliCommandConfigAgentsFavoritesGetResponseItem) UnmarshalJSON(data []byte) error {
	{
		var try CliCommandConfigAgentsFavoritesGetResponseItemGithub
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigAgentsFavoritesGetResponseItem{}
			candidate.Github = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigAgentsFavoritesGetResponseItemFilesystem
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigAgentsFavoritesGetResponseItem{}
			candidate.Filesystem = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigAgentsFavoritesGetResponseItemMock
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigAgentsFavoritesGetResponseItem{}
			candidate.Mock = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of CliCommandConfigAgentsFavoritesGetResponseItem")
}

func (v CliCommandConfigAgentsFavoritesGetResponseItem) Validate() error {
	count := 0
	if v.Github != nil { count++ }
	if v.Filesystem != nil { count++ }
	if v.Mock != nil { count++ }
	if count != 1 {
		return fmt.Errorf("CliCommandConfigAgentsFavoritesGetResponseItem: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (CliCommandConfigAgentsFavoritesGetResponseItem) SchemaTitle() string { return "cli.command.config.agents.favorites.get.ResponseItem" }

