// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribeResponseSchemaRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribeResponseSchemaPath `json:"path_type"`
}

func (CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribeResponseSchemaRequest) SchemaTitle() string { return "cli.command.logs.agents.completions.response.messages.assistant.tool_calls.subscribe.response_schema.Request" }
func (v CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribeResponseSchemaRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribeResponseSchemaRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribeResponseSchemaRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribeResponseSchemaRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsSubscribeResponseSchemaRequest(alias)
	return nil
}
