// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandLogsVectorCompletionsRequestSubscribePath struct {
	LogsVectorCompletionsRequestSubscribe string `validate:"omitempty,oneof=logs/vector/completions/request/subscribe" variantTitle:"Logs/vector/completions/request/subscribe"`
}

func (v CliCommandLogsVectorCompletionsRequestSubscribePath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.LogsVectorCompletionsRequestSubscribe)
}

func (v *CliCommandLogsVectorCompletionsRequestSubscribePath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.LogsVectorCompletionsRequestSubscribe); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandLogsVectorCompletionsRequestSubscribePath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandLogsVectorCompletionsRequestSubscribePath) SchemaTitle() string { return "cli.command.logs.vector.completions.request.subscribe.Path" }

