// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandLogsAgentsCompletionsRequestGetResponseSchemaPath struct {
	LogsAgentsCompletionsRequestGetResponseSchema string `validate:"omitempty,oneof=logs/agents/completions/request/get/response_schema"`
}

func (v CliCommandLogsAgentsCompletionsRequestGetResponseSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.LogsAgentsCompletionsRequestGetResponseSchema)
}

func (v *CliCommandLogsAgentsCompletionsRequestGetResponseSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.LogsAgentsCompletionsRequestGetResponseSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandLogsAgentsCompletionsRequestGetResponseSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandLogsAgentsCompletionsRequestGetResponseSchemaPath) SchemaTitle() string { return "cli.command.logs.agents.completions.request.get.response_schema.Path" }

