// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandConfigFunctionsInventionsRemoteResponseGetRequestSchema JsonValue

func (CliCommandConfigFunctionsInventionsRemoteResponseGetRequestSchema) SchemaVariantTitle() string { return "GetRequestSchema" }

func (v CliCommandConfigFunctionsInventionsRemoteResponseGetRequestSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandConfigFunctionsInventionsRemoteResponseGetRequestSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandConfigFunctionsInventionsRemoteResponseGetResponseSchema JsonValue

func (CliCommandConfigFunctionsInventionsRemoteResponseGetResponseSchema) SchemaVariantTitle() string { return "GetResponseSchema" }

func (v CliCommandConfigFunctionsInventionsRemoteResponseGetResponseSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandConfigFunctionsInventionsRemoteResponseGetResponseSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandConfigFunctionsInventionsRemoteResponseSetRequestSchema JsonValue

func (CliCommandConfigFunctionsInventionsRemoteResponseSetRequestSchema) SchemaVariantTitle() string { return "SetRequestSchema" }

func (v CliCommandConfigFunctionsInventionsRemoteResponseSetRequestSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandConfigFunctionsInventionsRemoteResponseSetRequestSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandConfigFunctionsInventionsRemoteResponseSetResponseSchema JsonValue

func (CliCommandConfigFunctionsInventionsRemoteResponseSetResponseSchema) SchemaVariantTitle() string { return "SetResponseSchema" }

func (v CliCommandConfigFunctionsInventionsRemoteResponseSetResponseSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandConfigFunctionsInventionsRemoteResponseSetResponseSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandConfigFunctionsInventionsRemoteResponse struct {
	Get *Remote 
	GetRequestSchema *CliCommandConfigFunctionsInventionsRemoteResponseGetRequestSchema 
	GetResponseSchema *CliCommandConfigFunctionsInventionsRemoteResponseGetResponseSchema 
	Set *CliCommandOk 
	SetRequestSchema *CliCommandConfigFunctionsInventionsRemoteResponseSetRequestSchema 
	SetResponseSchema *CliCommandConfigFunctionsInventionsRemoteResponseSetResponseSchema 
}

func (v CliCommandConfigFunctionsInventionsRemoteResponse) MarshalJSON() ([]byte, error) {
	if v.Get != nil {
		return json.Marshal(v.Get)
	}
	if v.GetRequestSchema != nil {
		return json.Marshal(v.GetRequestSchema)
	}
	if v.GetResponseSchema != nil {
		return json.Marshal(v.GetResponseSchema)
	}
	if v.Set != nil {
		return json.Marshal(v.Set)
	}
	if v.SetRequestSchema != nil {
		return json.Marshal(v.SetRequestSchema)
	}
	if v.SetResponseSchema != nil {
		return json.Marshal(v.SetResponseSchema)
	}
	return []byte("null"), nil
}

func (v *CliCommandConfigFunctionsInventionsRemoteResponse) UnmarshalJSON(data []byte) error {
	{
		var try Remote
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigFunctionsInventionsRemoteResponse{}
			candidate.Get = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigFunctionsInventionsRemoteResponseGetRequestSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigFunctionsInventionsRemoteResponse{}
			candidate.GetRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigFunctionsInventionsRemoteResponseGetResponseSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigFunctionsInventionsRemoteResponse{}
			candidate.GetResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandOk
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigFunctionsInventionsRemoteResponse{}
			candidate.Set = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigFunctionsInventionsRemoteResponseSetRequestSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigFunctionsInventionsRemoteResponse{}
			candidate.SetRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigFunctionsInventionsRemoteResponseSetResponseSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigFunctionsInventionsRemoteResponse{}
			candidate.SetResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of CliCommandConfigFunctionsInventionsRemoteResponse")
}

func (v CliCommandConfigFunctionsInventionsRemoteResponse) Validate() error {
	count := 0
	if v.Get != nil { count++ }
	if v.GetRequestSchema != nil { count++ }
	if v.GetResponseSchema != nil { count++ }
	if v.Set != nil { count++ }
	if v.SetRequestSchema != nil { count++ }
	if v.SetResponseSchema != nil { count++ }
	if count != 1 {
		return fmt.Errorf("CliCommandConfigFunctionsInventionsRemoteResponse: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (CliCommandConfigFunctionsInventionsRemoteResponse) SchemaTitle() string { return "cli.command.config.functions.inventions.remote.Response" }

