// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetRequestSchema JsonValue

func (CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetRequestSchema) SchemaVariantTitle() string { return "GetRequestSchema" }

func (v CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetRequestSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetRequestSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetResponseSchema JsonValue

func (CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetResponseSchema) SchemaVariantTitle() string { return "GetResponseSchema" }

func (v CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetResponseSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetResponseSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeRequestSchema JsonValue

func (CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeRequestSchema) SchemaVariantTitle() string { return "SubscribeRequestSchema" }

func (v CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeRequestSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeRequestSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeResponseSchema JsonValue

func (CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeResponseSchema) SchemaVariantTitle() string { return "SubscribeResponseSchema" }

func (v CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeResponseSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeResponseSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandLogsFunctionsInventionsRecursiveRequestResponse struct {
	Get *FunctionsInventionsRecursiveRequestFunctionInventionRecursiveCreateParamsLog 
	GetRequestSchema *CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetRequestSchema 
	GetResponseSchema *CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetResponseSchema 
	Subscribe *FunctionsInventionsRecursiveRequestFunctionInventionRecursiveCreateParamsLog 
	SubscribeRequestSchema *CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeRequestSchema 
	SubscribeResponseSchema *CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeResponseSchema 
}

func (v CliCommandLogsFunctionsInventionsRecursiveRequestResponse) MarshalJSON() ([]byte, error) {
	if v.Get != nil {
		return json.Marshal(v.Get)
	}
	if v.GetRequestSchema != nil {
		return json.Marshal(v.GetRequestSchema)
	}
	if v.GetResponseSchema != nil {
		return json.Marshal(v.GetResponseSchema)
	}
	if v.Subscribe != nil {
		return json.Marshal(v.Subscribe)
	}
	if v.SubscribeRequestSchema != nil {
		return json.Marshal(v.SubscribeRequestSchema)
	}
	if v.SubscribeResponseSchema != nil {
		return json.Marshal(v.SubscribeResponseSchema)
	}
	return []byte("null"), nil
}

func (v *CliCommandLogsFunctionsInventionsRecursiveRequestResponse) UnmarshalJSON(data []byte) error {
	{
		var try FunctionsInventionsRecursiveRequestFunctionInventionRecursiveCreateParamsLog
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandLogsFunctionsInventionsRecursiveRequestResponse{}
			candidate.Get = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetRequestSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandLogsFunctionsInventionsRecursiveRequestResponse{}
			candidate.GetRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandLogsFunctionsInventionsRecursiveRequestResponseGetResponseSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandLogsFunctionsInventionsRecursiveRequestResponse{}
			candidate.GetResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsInventionsRecursiveRequestFunctionInventionRecursiveCreateParamsLog
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandLogsFunctionsInventionsRecursiveRequestResponse{}
			candidate.Subscribe = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeRequestSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandLogsFunctionsInventionsRecursiveRequestResponse{}
			candidate.SubscribeRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandLogsFunctionsInventionsRecursiveRequestResponseSubscribeResponseSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandLogsFunctionsInventionsRecursiveRequestResponse{}
			candidate.SubscribeResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of CliCommandLogsFunctionsInventionsRecursiveRequestResponse")
}

func (v CliCommandLogsFunctionsInventionsRecursiveRequestResponse) Validate() error {
	count := 0
	if v.Get != nil { count++ }
	if v.GetRequestSchema != nil { count++ }
	if v.GetResponseSchema != nil { count++ }
	if v.Subscribe != nil { count++ }
	if v.SubscribeRequestSchema != nil { count++ }
	if v.SubscribeResponseSchema != nil { count++ }
	if count != 1 {
		return fmt.Errorf("CliCommandLogsFunctionsInventionsRecursiveRequestResponse: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (CliCommandLogsFunctionsInventionsRecursiveRequestResponse) SchemaTitle() string { return "cli.command.logs.functions.inventions.recursive.request.Response" }

