// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandConfigApiCommitAuthorEmailGetRequestSchemaPath struct {
	ConfigAPICommitAuthorEmailGetRequestSchema string `validate:"omitempty,oneof=config/api/commit_author_email/get/request_schema" variantTitle:"Config/api/commitAuthorEmail/get/requestSchema"`
}

func (v CliCommandConfigApiCommitAuthorEmailGetRequestSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.ConfigAPICommitAuthorEmailGetRequestSchema)
}

func (v *CliCommandConfigApiCommitAuthorEmailGetRequestSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.ConfigAPICommitAuthorEmailGetRequestSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandConfigApiCommitAuthorEmailGetRequestSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandConfigApiCommitAuthorEmailGetRequestSchemaPath) SchemaTitle() string { return "cli.command.config.api.commit_author_email.get.request_schema.Path" }

