// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandAgentsLogsTokenUsageGetResponseSchemaPath struct {
	AgentsLogsTokenUsageGetResponseSchema string `validate:"omitempty,oneof=agents/logs/token-usage/get/response_schema" variantTitle:"Agents/logs/tokenUsage/get/responseSchema"`
}

func (v CliCommandAgentsLogsTokenUsageGetResponseSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.AgentsLogsTokenUsageGetResponseSchema)
}

func (v *CliCommandAgentsLogsTokenUsageGetResponseSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.AgentsLogsTokenUsageGetResponseSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandAgentsLogsTokenUsageGetResponseSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandAgentsLogsTokenUsageGetResponseSchemaPath) SchemaTitle() string { return "cli.command.agents.logs.token_usage.get.response_schema.Path" }

