// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandAgentsLogsTokenUsageSubscribePath struct {
	AgentsLogsTokenUsageSubscribe string `validate:"omitempty,oneof=agents/logs/token-usage/subscribe" variantTitle:"Agents/logs/tokenUsage/subscribe"`
}

func (v CliCommandAgentsLogsTokenUsageSubscribePath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.AgentsLogsTokenUsageSubscribe)
}

func (v *CliCommandAgentsLogsTokenUsageSubscribePath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.AgentsLogsTokenUsageSubscribe); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandAgentsLogsTokenUsageSubscribePath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandAgentsLogsTokenUsageSubscribePath) SchemaTitle() string { return "cli.command.agents.logs.token_usage.subscribe.Path" }

