// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_command_execute.go from objectiveai-sdk-rs/src/cli/command/.
package objectiveai

import (
	"context"
	"fmt"
)

// ApiConfigCommitAuthorEmailSetResponseSchemaExecute — `api config commit_author_email set response_schema execute` (unary); the first stream item, rest discarded.
func ApiConfigCommitAuthorEmailSetResponseSchemaExecute(ctx context.Context, executor CommandExecutor, request CliCommandApiConfigCommitAuthorEmailSetResponseSchemaRequest) (*JsonValue, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	wire["path_type"] = "api/config/commit_author_email/set/response_schema"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[JsonValue](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("api config commit_author_email set response_schema: cli produced no output before the end marker")
	}
	return first, nil
}

// ApiConfigCommitAuthorEmailSetResponseSchemaExecuteTransform — `api config commit_author_email set response_schema execute_transform` (unary); the first stream item, rest discarded.
func ApiConfigCommitAuthorEmailSetResponseSchemaExecuteTransform(ctx context.Context, executor CommandExecutor, request CliCommandApiConfigCommitAuthorEmailSetResponseSchemaRequest, transform map[string]string) (*JsonValue, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	for k, v := range transform {
		wire[k] = v
	}
	wire["path_type"] = "api/config/commit_author_email/set/response_schema"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[JsonValue](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("api config commit_author_email set response_schema: cli produced no output before the end marker")
	}
	return first, nil
}
