// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandChannelsPublishRequestSchemaPath struct {
	ChannelsPublishRequestSchema string `validate:"omitempty,oneof=channels/publish/request_schema" variantTitle:"Channels/publish/requestSchema"`
}

func (v CliCommandChannelsPublishRequestSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.ChannelsPublishRequestSchema)
}

func (v *CliCommandChannelsPublishRequestSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.ChannelsPublishRequestSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandChannelsPublishRequestSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandChannelsPublishRequestSchemaPath) SchemaTitle() string { return "cli.command.channels.publish.request_schema.Path" }

