// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_command_execute.go from objectiveai-sdk-rs/src/cli/command/.
package objectiveai

import (
	"context"
	"fmt"
)

// ViewerConfigSignatureGetExecute — `viewer config signature get execute` (unary); the first stream item, rest discarded.
func ViewerConfigSignatureGetExecute(ctx context.Context, executor CommandExecutor, request CliCommandViewerConfigSignatureGetRequest) (*CliCommandViewerConfigSignatureGetResponse, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	wire["path_type"] = "viewer/config/signature/get"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[CliCommandViewerConfigSignatureGetResponse](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("viewer config signature get: cli produced no output before the end marker")
	}
	return first, nil
}

// ViewerConfigSignatureGetExecuteTransform — `viewer config signature get execute_transform` (unary); the first stream item, rest discarded.
func ViewerConfigSignatureGetExecuteTransform(ctx context.Context, executor CommandExecutor, request CliCommandViewerConfigSignatureGetRequest, transform map[string]string) (*JsonValue, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	for k, v := range transform {
		wire[k] = v
	}
	wire["path_type"] = "viewer/config/signature/get"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[JsonValue](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("viewer config signature get: cli produced no output before the end marker")
	}
	return first, nil
}
