// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// One host→container bind mount. CLI wire form is the docker-style
// `host=…,container=…` (both keys required).
type CliCommandLaboratoriesCreateMount struct {
	Container string `json:"container"`
	Host string `json:"host"`
}

func (CliCommandLaboratoriesCreateMount) SchemaTitle() string { return "cli.command.laboratories.create.Mount" }
func (v CliCommandLaboratoriesCreateMount) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandLaboratoriesCreateMount) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"container", "host"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandLaboratoriesCreateMount: missing required field %q", key)
		}
	}
	type Alias CliCommandLaboratoriesCreateMount
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandLaboratoriesCreateMount(alias)
	return nil
}
