// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandConfigApiGithubAuthorizationGetRequest struct {
	Filter *string `json:"filter"`
	Jq *string `json:"jq"`
	PathType CliCommandConfigApiGithubAuthorizationGetPath `json:"path_type"`
}

func (CliCommandConfigApiGithubAuthorizationGetRequest) SchemaTitle() string { return "cli.command.config.api.github_authorization.get.Request" }
func (v CliCommandConfigApiGithubAuthorizationGetRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandConfigApiGithubAuthorizationGetRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandConfigApiGithubAuthorizationGetRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandConfigApiGithubAuthorizationGetRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandConfigApiGithubAuthorizationGetRequest(alias)
	return nil
}
