// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandConfigViewerSignatureGetResponseSchemaPath struct {
	ConfigViewerSignatureGetResponseSchema string `validate:"omitempty,oneof=config/viewer/signature/get/response_schema"`
}

func (v CliCommandConfigViewerSignatureGetResponseSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.ConfigViewerSignatureGetResponseSchema)
}

func (v *CliCommandConfigViewerSignatureGetResponseSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.ConfigViewerSignatureGetResponseSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandConfigViewerSignatureGetResponseSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandConfigViewerSignatureGetResponseSchemaPath) SchemaTitle() string { return "cli.command.config.viewer.signature.get.response_schema.Path" }

