// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliOutputNotificationTypedNotificationValueActiveAgent struct {
	CliOutputNotificationAgentsActiveAgent
	Type string `json:"type" validate:"oneof=active_agent"`
}

func (v *CliOutputNotificationTypedNotificationValueActiveAgent) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationAgentsActiveAgent); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueActiveAgent) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationAgentsActiveAgent)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueActiveAgent) SchemaVariantTitle() string { return "ActiveAgent" }

type CliOutputNotificationTypedNotificationValueAgent struct {
	CliOutputNotificationAgentsAgent
	Type string `json:"type" validate:"oneof=agent"`
}

func (v *CliOutputNotificationTypedNotificationValueAgent) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationAgentsAgent); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueAgent) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationAgentsAgent)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueAgent) SchemaVariantTitle() string { return "Agent" }

type CliOutputNotificationTypedNotificationValueAgentItems struct {
	CliOutputNotificationAgentsAgentItems
	Type string `json:"type" validate:"oneof=agent_items"`
}

func (v *CliOutputNotificationTypedNotificationValueAgentItems) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationAgentsAgentItems); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueAgentItems) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationAgentsAgentItems)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueAgentItems) SchemaVariantTitle() string { return "AgentItems" }

type CliOutputNotificationTypedNotificationValueInactive struct {
	CliOutputNotificationAgentsInactive
	Type string `json:"type" validate:"oneof=inactive"`
}

func (v *CliOutputNotificationTypedNotificationValueInactive) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationAgentsInactive); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueInactive) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationAgentsInactive)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueInactive) SchemaVariantTitle() string { return "Inactive" }

type CliOutputNotificationTypedNotificationValueMessageDelivered struct {
	CliOutputNotificationAgentsMessageDelivered
	Type string `json:"type" validate:"oneof=message_delivered"`
}

func (v *CliOutputNotificationTypedNotificationValueMessageDelivered) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationAgentsMessageDelivered); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueMessageDelivered) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationAgentsMessageDelivered)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueMessageDelivered) SchemaVariantTitle() string { return "MessageDelivered" }

type CliOutputNotificationTypedNotificationValueMessageQueued struct {
	CliOutputNotificationAgentsMessageQueued
	Type string `json:"type" validate:"oneof=message_queued"`
}

func (v *CliOutputNotificationTypedNotificationValueMessageQueued) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationAgentsMessageQueued); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueMessageQueued) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationAgentsMessageQueued)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueMessageQueued) SchemaVariantTitle() string { return "MessageQueued" }

type CliOutputNotificationTypedNotificationValueSpawned struct {
	CliOutputNotificationAgentsSpawned
	Type string `json:"type" validate:"oneof=spawned"`
}

func (v *CliOutputNotificationTypedNotificationValueSpawned) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationAgentsSpawned); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueSpawned) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationAgentsSpawned)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueSpawned) SchemaVariantTitle() string { return "Spawned" }

type CliOutputNotificationTypedNotificationValueDetached struct {
	CliOutputNotificationApiDetached
	Type string `json:"type" validate:"oneof=detached"`
}

func (v *CliOutputNotificationTypedNotificationValueDetached) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationApiDetached); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueDetached) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationApiDetached)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueDetached) SchemaVariantTitle() string { return "Detached" }

type CliOutputNotificationTypedNotificationValueExecution struct {
	CliOutputNotificationFunctionsExecutionsExecution
	Type string `json:"type" validate:"oneof=execution"`
}

func (v *CliOutputNotificationTypedNotificationValueExecution) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationFunctionsExecutionsExecution); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueExecution) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationFunctionsExecutionsExecution)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueExecution) SchemaVariantTitle() string { return "Execution" }

type CliOutputNotificationTypedNotificationValueFunction struct {
	CliOutputNotificationFunctionsFunction
	Type string `json:"type" validate:"oneof=function"`
}

func (v *CliOutputNotificationTypedNotificationValueFunction) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationFunctionsFunction); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueFunction) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationFunctionsFunction)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueFunction) SchemaVariantTitle() string { return "Function" }

type CliOutputNotificationTypedNotificationValueInventions struct {
	CliOutputNotificationFunctionsInventionsRecursiveInventions
	Type string `json:"type" validate:"oneof=inventions"`
}

func (v *CliOutputNotificationTypedNotificationValueInventions) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationFunctionsInventionsRecursiveInventions); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueInventions) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationFunctionsInventionsRecursiveInventions)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueInventions) SchemaVariantTitle() string { return "Inventions" }

type CliOutputNotificationTypedNotificationValuePair struct {
	CliOutputNotificationFunctionsProfilesPair
	Type string `json:"type" validate:"oneof=pair"`
}

func (v *CliOutputNotificationTypedNotificationValuePair) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationFunctionsProfilesPair); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValuePair) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationFunctionsProfilesPair)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValuePair) SchemaVariantTitle() string { return "Pair" }

type CliOutputNotificationTypedNotificationValueProfile struct {
	CliOutputNotificationFunctionsProfilesProfile
	Type string `json:"type" validate:"oneof=profile"`
}

func (v *CliOutputNotificationTypedNotificationValueProfile) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationFunctionsProfilesProfile); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueProfile) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationFunctionsProfilesProfile)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueProfile) SchemaVariantTitle() string { return "Profile" }

type CliOutputNotificationTypedNotificationValueState struct {
	CliOutputNotificationFunctionsInventionsState
	Type string `json:"type" validate:"oneof=state"`
}

func (v *CliOutputNotificationTypedNotificationValueState) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationFunctionsInventionsState); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueState) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationFunctionsInventionsState)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueState) SchemaVariantTitle() string { return "State" }

type CliOutputNotificationTypedNotificationValueLaboratory struct {
	CliOutputNotificationLaboratoriesExecutionsLaboratory
	Type string `json:"type" validate:"oneof=laboratory"`
}

func (v *CliOutputNotificationTypedNotificationValueLaboratory) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationLaboratoriesExecutionsLaboratory); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueLaboratory) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationLaboratoriesExecutionsLaboratory)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueLaboratory) SchemaVariantTitle() string { return "Laboratory" }

type CliOutputNotificationTypedNotificationValueSwarm struct {
	CliOutputNotificationSwarmsSwarm
	Type string `json:"type" validate:"oneof=swarm"`
}

func (v *CliOutputNotificationTypedNotificationValueSwarm) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationSwarmsSwarm); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueSwarm) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationSwarmsSwarm)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueSwarm) SchemaVariantTitle() string { return "Swarm" }

type CliOutputNotificationTypedNotificationValueCleared struct {
	CliOutputNotificationCleared
	Type string `json:"type" validate:"oneof=cleared"`
}

func (v *CliOutputNotificationTypedNotificationValueCleared) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationCleared); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueCleared) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationCleared)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueCleared) SchemaVariantTitle() string { return "Cleared" }

// Terminal marker for a plugin-dispatched command. Rides
// inside the [`crate::cli::plugins::PluginCommandResponse`]
// envelope on the plugin channel — the originating command's
// correlation id (when set) is on the envelope's `id` field,
// not on this struct. See [`CommandComplete`].
type CliOutputNotificationTypedNotificationValueCommandComplete struct {
	CliOutputNotificationCommandComplete
	Type string `json:"type" validate:"oneof=command_complete"`
}

func (v *CliOutputNotificationTypedNotificationValueCommandComplete) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationCommandComplete); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueCommandComplete) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationCommandComplete)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueCommandComplete) SchemaVariantTitle() string { return "CommandComplete" }

type CliOutputNotificationTypedNotificationValueHelp struct {
	CliOutputNotificationHelp
	Type string `json:"type" validate:"oneof=help"`
}

func (v *CliOutputNotificationTypedNotificationValueHelp) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationHelp); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueHelp) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationHelp)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueHelp) SchemaVariantTitle() string { return "Help" }

type CliOutputNotificationTypedNotificationValueInstalled struct {
	CliOutputNotificationInstalled
	Type string `json:"type" validate:"oneof=installed"`
}

func (v *CliOutputNotificationTypedNotificationValueInstalled) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationInstalled); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueInstalled) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationInstalled)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueInstalled) SchemaVariantTitle() string { return "Installed" }

type CliOutputNotificationTypedNotificationValueInstructions struct {
	CliOutputNotificationInstructions
	Type string `json:"type" validate:"oneof=instructions"`
}

func (v *CliOutputNotificationTypedNotificationValueInstructions) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationInstructions); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueInstructions) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationInstructions)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueInstructions) SchemaVariantTitle() string { return "Instructions" }

type CliOutputNotificationTypedNotificationValueJqResults struct {
	CliOutputNotificationJqResults
	Type string `json:"type" validate:"oneof=jq_results"`
}

func (v *CliOutputNotificationTypedNotificationValueJqResults) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationJqResults); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueJqResults) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationJqResults)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueJqResults) SchemaVariantTitle() string { return "JqResults" }

type CliOutputNotificationTypedNotificationValueLogContent struct {
	FilesystemLogsLogContent
	Type string `json:"type" validate:"oneof=log_content"`
}

func (v *CliOutputNotificationTypedNotificationValueLogContent) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.FilesystemLogsLogContent); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueLogContent) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.FilesystemLogsLogContent)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueLogContent) SchemaVariantTitle() string { return "LogContent" }

type CliOutputNotificationTypedNotificationValueLogStreamReady struct {
	CliOutputNotificationLogStreamReady
	Type string `json:"type" validate:"oneof=log_stream_ready"`
}

func (v *CliOutputNotificationTypedNotificationValueLogStreamReady) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationLogStreamReady); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueLogStreamReady) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationLogStreamReady)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueLogStreamReady) SchemaVariantTitle() string { return "LogStreamReady" }

type CliOutputNotificationTypedNotificationValueMCP struct {
	CliOutputNotificationMcp
	Type string `json:"type" validate:"oneof=mcp"`
}

func (v *CliOutputNotificationTypedNotificationValueMCP) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationMcp); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueMCP) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationMcp)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueMCP) SchemaVariantTitle() string { return "Mcp" }

type CliOutputNotificationTypedNotificationValueMe struct {
	CliOutputNotificationMe
	Type string `json:"type" validate:"oneof=me"`
}

func (v *CliOutputNotificationTypedNotificationValueMe) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationMe); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueMe) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationMe)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueMe) SchemaVariantTitle() string { return "Me" }

type CliOutputNotificationTypedNotificationValueOk struct {
	CliOutputNotificationOk
	Type string `json:"type" validate:"oneof=ok"`
}

func (v *CliOutputNotificationTypedNotificationValueOk) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationOk); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueOk) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationOk)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueOk) SchemaVariantTitle() string { return "Ok" }

type CliOutputNotificationTypedNotificationValuePlugin struct {
	CliOutputNotificationPlugin
	Type string `json:"type" validate:"oneof=plugin"`
}

func (v *CliOutputNotificationTypedNotificationValuePlugin) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationPlugin); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValuePlugin) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationPlugin)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValuePlugin) SchemaVariantTitle() string { return "Plugin" }

// A notification emitted by a cli plugin and forwarded by the
// host. The plugin's payload is nested under `value` as an
// arbitrary `serde_json::Value` — objects, strings, numbers,
// booleans, arrays, and null are all valid.
//
// Wire: `{"type":"plugin_notification","value":<any-json>}`.
type CliOutputNotificationTypedNotificationValuePluginNotification struct {
	Type string `json:"type" validate:"oneof=plugin_notification"`
	Value JsonValue `json:"value"`
}

func (v *CliOutputNotificationTypedNotificationValuePluginNotification) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"type", "value"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliOutputNotificationTypedNotificationValuePluginNotification: missing required field %q", key)
		}
	}
	type Alias CliOutputNotificationTypedNotificationValuePluginNotification
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliOutputNotificationTypedNotificationValuePluginNotification(alias)
	return nil
}
func (CliOutputNotificationTypedNotificationValuePluginNotification) SchemaVariantTitle() string { return "PluginNotification" }

type CliOutputNotificationTypedNotificationValuePlugins struct {
	CliOutputNotificationPlugins
	Type string `json:"type" validate:"oneof=plugins"`
}

func (v *CliOutputNotificationTypedNotificationValuePlugins) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationPlugins); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValuePlugins) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationPlugins)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValuePlugins) SchemaVariantTitle() string { return "Plugins" }

type CliOutputNotificationTypedNotificationValuePublished struct {
	CliOutputNotificationPublished
	Type string `json:"type" validate:"oneof=published"`
}

func (v *CliOutputNotificationTypedNotificationValuePublished) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationPublished); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValuePublished) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationPublished)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValuePublished) SchemaVariantTitle() string { return "Published" }

type CliOutputNotificationTypedNotificationValueSchema struct {
	CliOutputNotificationSchema
	Type string `json:"type" validate:"oneof=schema"`
}

func (v *CliOutputNotificationTypedNotificationValueSchema) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationSchema); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueSchema) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationSchema)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueSchema) SchemaVariantTitle() string { return "Schema" }

type CliOutputNotificationTypedNotificationValueSchemas struct {
	CliOutputNotificationSchemas
	Type string `json:"type" validate:"oneof=schemas"`
}

func (v *CliOutputNotificationTypedNotificationValueSchemas) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationSchemas); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueSchemas) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationSchemas)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueSchemas) SchemaVariantTitle() string { return "Schemas" }

type CliOutputNotificationTypedNotificationValueTool struct {
	CliOutputNotificationTool
	Type string `json:"type" validate:"oneof=tool"`
}

func (v *CliOutputNotificationTypedNotificationValueTool) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationTool); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueTool) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationTool)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueTool) SchemaVariantTitle() string { return "Tool" }

type CliOutputNotificationTypedNotificationValueToolLine struct {
	CliOutputNotificationToolLine
	Type string `json:"type" validate:"oneof=tool_line"`
}

func (v *CliOutputNotificationTypedNotificationValueToolLine) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationToolLine); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueToolLine) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationToolLine)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueToolLine) SchemaVariantTitle() string { return "ToolLine" }

type CliOutputNotificationTypedNotificationValueTools struct {
	CliOutputNotificationTools
	Type string `json:"type" validate:"oneof=tools"`
}

func (v *CliOutputNotificationTypedNotificationValueTools) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationTools); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueTools) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationTools)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueTools) SchemaVariantTitle() string { return "Tools" }

type CliOutputNotificationTypedNotificationValueUpdater struct {
	CliOutputNotificationUpdater
	Type string `json:"type" validate:"oneof=updater"`
}

func (v *CliOutputNotificationTypedNotificationValueUpdater) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationUpdater); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueUpdater) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationUpdater)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueUpdater) SchemaVariantTitle() string { return "Updater" }

type CliOutputNotificationTypedNotificationValueViewerSendResult struct {
	CliOutputNotificationViewerSendResult
	Type string `json:"type" validate:"oneof=viewer_send_result"`
}

func (v *CliOutputNotificationTypedNotificationValueViewerSendResult) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.CliOutputNotificationViewerSendResult); err != nil {
		return err
	}
	var local struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &local); err != nil {
		return err
	}
	v.Type = local.Type
	return nil
}

func (v CliOutputNotificationTypedNotificationValueViewerSendResult) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(v.CliOutputNotificationViewerSendResult)
	if err != nil {
		return nil, err
	}
	var merged map[string]json.RawMessage
	json.Unmarshal(base, &merged)
	if raw, err := json.Marshal(v.Type); err == nil {
		merged["type"] = raw
	}
	return json.Marshal(merged)
}
func (CliOutputNotificationTypedNotificationValueViewerSendResult) SchemaVariantTitle() string { return "ViewerSendResult" }

// The typed half of [`NotificationValue`]. Internally tagged with
// `#[serde(tag = "type")]` — variant discrimination happens on
// the `type` key.
type CliOutputNotificationTypedNotificationValue struct {
	ActiveAgent *CliOutputNotificationTypedNotificationValueActiveAgent `outerObject:"true"`
	Agent *CliOutputNotificationTypedNotificationValueAgent `outerObject:"true"`
	AgentItems *CliOutputNotificationTypedNotificationValueAgentItems `outerObject:"true"`
	Inactive *CliOutputNotificationTypedNotificationValueInactive `outerObject:"true"`
	MessageDelivered *CliOutputNotificationTypedNotificationValueMessageDelivered `outerObject:"true"`
	MessageQueued *CliOutputNotificationTypedNotificationValueMessageQueued `outerObject:"true"`
	Spawned *CliOutputNotificationTypedNotificationValueSpawned `outerObject:"true"`
	Detached *CliOutputNotificationTypedNotificationValueDetached `outerObject:"true"`
	Execution *CliOutputNotificationTypedNotificationValueExecution `outerObject:"true"`
	Function *CliOutputNotificationTypedNotificationValueFunction `outerObject:"true"`
	Inventions *CliOutputNotificationTypedNotificationValueInventions `outerObject:"true"`
	Pair *CliOutputNotificationTypedNotificationValuePair `outerObject:"true"`
	Profile *CliOutputNotificationTypedNotificationValueProfile `outerObject:"true"`
	State *CliOutputNotificationTypedNotificationValueState `outerObject:"true"`
	Laboratory *CliOutputNotificationTypedNotificationValueLaboratory `outerObject:"true"`
	Swarm *CliOutputNotificationTypedNotificationValueSwarm `outerObject:"true"`
	Cleared *CliOutputNotificationTypedNotificationValueCleared `outerObject:"true"`
	// Terminal marker for a plugin-dispatched command. Rides
	// inside the [`crate::cli::plugins::PluginCommandResponse`]
	// envelope on the plugin channel — the originating command's
	// correlation id (when set) is on the envelope's `id` field,
	// not on this struct. See [`CommandComplete`].
	CommandComplete *CliOutputNotificationTypedNotificationValueCommandComplete `outerObject:"true"`
	Help *CliOutputNotificationTypedNotificationValueHelp `outerObject:"true"`
	Installed *CliOutputNotificationTypedNotificationValueInstalled `outerObject:"true"`
	Instructions *CliOutputNotificationTypedNotificationValueInstructions `outerObject:"true"`
	JqResults *CliOutputNotificationTypedNotificationValueJqResults `outerObject:"true"`
	LogContent *CliOutputNotificationTypedNotificationValueLogContent `outerObject:"true"`
	LogStreamReady *CliOutputNotificationTypedNotificationValueLogStreamReady `outerObject:"true"`
	MCP *CliOutputNotificationTypedNotificationValueMCP `outerObject:"true"`
	Me *CliOutputNotificationTypedNotificationValueMe `outerObject:"true"`
	Ok *CliOutputNotificationTypedNotificationValueOk `outerObject:"true"`
	Plugin *CliOutputNotificationTypedNotificationValuePlugin `outerObject:"true"`
	// A notification emitted by a cli plugin and forwarded by the
	// host. The plugin's payload is nested under `value` as an
	// arbitrary `serde_json::Value` — objects, strings, numbers,
	// booleans, arrays, and null are all valid.
	//
	// Wire: `{"type":"plugin_notification","value":<any-json>}`.
	PluginNotification *CliOutputNotificationTypedNotificationValuePluginNotification `outerObject:"true"`
	Plugins *CliOutputNotificationTypedNotificationValuePlugins `outerObject:"true"`
	Published *CliOutputNotificationTypedNotificationValuePublished `outerObject:"true"`
	Schema *CliOutputNotificationTypedNotificationValueSchema `outerObject:"true"`
	Schemas *CliOutputNotificationTypedNotificationValueSchemas `outerObject:"true"`
	Tool *CliOutputNotificationTypedNotificationValueTool `outerObject:"true"`
	ToolLine *CliOutputNotificationTypedNotificationValueToolLine `outerObject:"true"`
	Tools *CliOutputNotificationTypedNotificationValueTools `outerObject:"true"`
	Updater *CliOutputNotificationTypedNotificationValueUpdater `outerObject:"true"`
	ViewerSendResult *CliOutputNotificationTypedNotificationValueViewerSendResult `outerObject:"true"`
}

func (v CliOutputNotificationTypedNotificationValue) MarshalJSON() ([]byte, error) {
	if v.ActiveAgent != nil {
		return json.Marshal(v.ActiveAgent)
	}
	if v.Agent != nil {
		return json.Marshal(v.Agent)
	}
	if v.AgentItems != nil {
		return json.Marshal(v.AgentItems)
	}
	if v.Inactive != nil {
		return json.Marshal(v.Inactive)
	}
	if v.MessageDelivered != nil {
		return json.Marshal(v.MessageDelivered)
	}
	if v.MessageQueued != nil {
		return json.Marshal(v.MessageQueued)
	}
	if v.Spawned != nil {
		return json.Marshal(v.Spawned)
	}
	if v.Detached != nil {
		return json.Marshal(v.Detached)
	}
	if v.Execution != nil {
		return json.Marshal(v.Execution)
	}
	if v.Function != nil {
		return json.Marshal(v.Function)
	}
	if v.Inventions != nil {
		return json.Marshal(v.Inventions)
	}
	if v.Pair != nil {
		return json.Marshal(v.Pair)
	}
	if v.Profile != nil {
		return json.Marshal(v.Profile)
	}
	if v.State != nil {
		return json.Marshal(v.State)
	}
	if v.Laboratory != nil {
		return json.Marshal(v.Laboratory)
	}
	if v.Swarm != nil {
		return json.Marshal(v.Swarm)
	}
	if v.Cleared != nil {
		return json.Marshal(v.Cleared)
	}
	if v.CommandComplete != nil {
		return json.Marshal(v.CommandComplete)
	}
	if v.Help != nil {
		return json.Marshal(v.Help)
	}
	if v.Installed != nil {
		return json.Marshal(v.Installed)
	}
	if v.Instructions != nil {
		return json.Marshal(v.Instructions)
	}
	if v.JqResults != nil {
		return json.Marshal(v.JqResults)
	}
	if v.LogContent != nil {
		return json.Marshal(v.LogContent)
	}
	if v.LogStreamReady != nil {
		return json.Marshal(v.LogStreamReady)
	}
	if v.MCP != nil {
		return json.Marshal(v.MCP)
	}
	if v.Me != nil {
		return json.Marshal(v.Me)
	}
	if v.Ok != nil {
		return json.Marshal(v.Ok)
	}
	if v.Plugin != nil {
		return json.Marshal(v.Plugin)
	}
	if v.PluginNotification != nil {
		return json.Marshal(v.PluginNotification)
	}
	if v.Plugins != nil {
		return json.Marshal(v.Plugins)
	}
	if v.Published != nil {
		return json.Marshal(v.Published)
	}
	if v.Schema != nil {
		return json.Marshal(v.Schema)
	}
	if v.Schemas != nil {
		return json.Marshal(v.Schemas)
	}
	if v.Tool != nil {
		return json.Marshal(v.Tool)
	}
	if v.ToolLine != nil {
		return json.Marshal(v.ToolLine)
	}
	if v.Tools != nil {
		return json.Marshal(v.Tools)
	}
	if v.Updater != nil {
		return json.Marshal(v.Updater)
	}
	if v.ViewerSendResult != nil {
		return json.Marshal(v.ViewerSendResult)
	}
	return []byte("null"), nil
}

func (v *CliOutputNotificationTypedNotificationValue) UnmarshalJSON(data []byte) error {
	{
		var try CliOutputNotificationTypedNotificationValueActiveAgent
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.ActiveAgent = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueAgent
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Agent = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueAgentItems
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.AgentItems = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueInactive
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Inactive = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueMessageDelivered
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.MessageDelivered = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueMessageQueued
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.MessageQueued = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueSpawned
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Spawned = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueDetached
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Detached = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueExecution
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Execution = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueFunction
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Function = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueInventions
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Inventions = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValuePair
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Pair = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueProfile
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Profile = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueState
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.State = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueLaboratory
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Laboratory = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueSwarm
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Swarm = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueCleared
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Cleared = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueCommandComplete
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.CommandComplete = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueHelp
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Help = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueInstalled
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Installed = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueInstructions
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Instructions = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueJqResults
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.JqResults = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueLogContent
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.LogContent = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueLogStreamReady
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.LogStreamReady = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueMCP
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.MCP = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueMe
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Me = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueOk
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Ok = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValuePlugin
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Plugin = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValuePluginNotification
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.PluginNotification = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValuePlugins
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Plugins = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValuePublished
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Published = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Schema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueSchemas
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Schemas = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueTool
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Tool = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueToolLine
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.ToolLine = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueTools
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Tools = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueUpdater
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.Updater = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliOutputNotificationTypedNotificationValueViewerSendResult
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliOutputNotificationTypedNotificationValue{}
			candidate.ViewerSendResult = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of CliOutputNotificationTypedNotificationValue")
}

func (v CliOutputNotificationTypedNotificationValue) Validate() error {
	count := 0
	if v.ActiveAgent != nil { count++ }
	if v.Agent != nil { count++ }
	if v.AgentItems != nil { count++ }
	if v.Inactive != nil { count++ }
	if v.MessageDelivered != nil { count++ }
	if v.MessageQueued != nil { count++ }
	if v.Spawned != nil { count++ }
	if v.Detached != nil { count++ }
	if v.Execution != nil { count++ }
	if v.Function != nil { count++ }
	if v.Inventions != nil { count++ }
	if v.Pair != nil { count++ }
	if v.Profile != nil { count++ }
	if v.State != nil { count++ }
	if v.Laboratory != nil { count++ }
	if v.Swarm != nil { count++ }
	if v.Cleared != nil { count++ }
	if v.CommandComplete != nil { count++ }
	if v.Help != nil { count++ }
	if v.Installed != nil { count++ }
	if v.Instructions != nil { count++ }
	if v.JqResults != nil { count++ }
	if v.LogContent != nil { count++ }
	if v.LogStreamReady != nil { count++ }
	if v.MCP != nil { count++ }
	if v.Me != nil { count++ }
	if v.Ok != nil { count++ }
	if v.Plugin != nil { count++ }
	if v.PluginNotification != nil { count++ }
	if v.Plugins != nil { count++ }
	if v.Published != nil { count++ }
	if v.Schema != nil { count++ }
	if v.Schemas != nil { count++ }
	if v.Tool != nil { count++ }
	if v.ToolLine != nil { count++ }
	if v.Tools != nil { count++ }
	if v.Updater != nil { count++ }
	if v.ViewerSendResult != nil { count++ }
	if count != 1 {
		return fmt.Errorf("CliOutputNotificationTypedNotificationValue: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (CliOutputNotificationTypedNotificationValue) SchemaTitle() string { return "cli.output.notification.TypedNotificationValue" }

