// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_command_execute.go from objectiveai-sdk-rs/src/cli/command/.
package objectiveai

import (
	"context"
	"fmt"
)

// ApiConfigAddressGetExecute — `api config address get execute` (unary); the first stream item, rest discarded.
func ApiConfigAddressGetExecute(ctx context.Context, executor CommandExecutor, request CliCommandApiConfigAddressGetRequest) (*CliCommandApiConfigAddressGetResponse, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	wire["path_type"] = "api/config/address/get"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[CliCommandApiConfigAddressGetResponse](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("api config address get: cli produced no output before the end marker")
	}
	return first, nil
}

// ApiConfigAddressGetExecuteTransform — `api config address get execute_transform` (unary); the first stream item, rest discarded.
func ApiConfigAddressGetExecuteTransform(ctx context.Context, executor CommandExecutor, request CliCommandApiConfigAddressGetRequest, transform map[string]string) (*JsonValue, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	for k, v := range transform {
		wire[k] = v
	}
	wire["path_type"] = "api/config/address/get"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[JsonValue](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("api config address get: cli produced no output before the end marker")
	}
	return first, nil
}
