// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandApiConfigHttpRefererGetResponseSchemaRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandApiConfigHttpRefererGetResponseSchemaPath `json:"path_type"`
}

func (CliCommandApiConfigHttpRefererGetResponseSchemaRequest) SchemaTitle() string { return "cli.command.api.config.http_referer.get.response_schema.Request" }
func (v CliCommandApiConfigHttpRefererGetResponseSchemaRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandApiConfigHttpRefererGetResponseSchemaRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandApiConfigHttpRefererGetResponseSchemaRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandApiConfigHttpRefererGetResponseSchemaRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandApiConfigHttpRefererGetResponseSchemaRequest(alias)
	return nil
}
