// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandAgentsMcpToolsCallRequestSchemaPath struct {
	AgentsMCPToolsCallRequestSchema string `validate:"omitempty,oneof=agents/mcp/tools/call/request_schema" variantTitle:"Agents/mcp/tools/call/requestSchema"`
}

func (v CliCommandAgentsMcpToolsCallRequestSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.AgentsMCPToolsCallRequestSchema)
}

func (v *CliCommandAgentsMcpToolsCallRequestSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.AgentsMCPToolsCallRequestSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandAgentsMcpToolsCallRequestSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandAgentsMcpToolsCallRequestSchemaPath) SchemaTitle() string { return "cli.command.agents.mcp.tools.call.request_schema.Path" }

