// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandAgentsMcpToolsListPath struct {
	AgentsMCPToolsList string `validate:"omitempty,oneof=agents/mcp/tools/list" variantTitle:"Agents/mcp/tools/list"`
}

func (v CliCommandAgentsMcpToolsListPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.AgentsMCPToolsList)
}

func (v *CliCommandAgentsMcpToolsListPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.AgentsMCPToolsList); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandAgentsMcpToolsListPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandAgentsMcpToolsListPath) SchemaTitle() string { return "cli.command.agents.mcp.tools.list.Path" }

