// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandAgentsLogsTokenUsageSubscribeRequest struct {
	// The full agent instance hierarchy to watch.
	AgentInstanceHierarchy string `json:"agent_instance_hierarchy"`
	// jq filter applied to the JSON output. Ignored when `python`
	// is also set — python overrides jq.
	Jq *string `json:"jq"`
	// Response token budget, `>= 1` (`0` is rejected at parse
	// time — omit entirely for unlimited). Forward-compatible
	// envelope data — no leaf enforces it yet.
	MaxTokens *uint64 `json:"max_tokens,omitempty" validate:"omitempty,min=0,max=18446744073709551615"`
	PathType CliCommandAgentsLogsTokenUsageSubscribePath `json:"path_type"`
	// The last-seen `total_tokens`. When set and the stored value
	// already differs, the command returns immediately instead of
	// subscribing. `None` on the wire = always subscribe.
	Previous *int64 `json:"previous,omitempty" validate:"omitempty,min=-9223372036854775808,max=9223372036854775807"`
	// Python transform applied to the JSON output. Overrides `jq`
	// when both are provided.
	Python *string `json:"python"`
	// Wall-clock execution cap, in whole seconds. Parsed from
	// `--timeout` (humantime: `30s`, `5m`, `1h30m`), `> 0`
	// enforced at parse time. `db query` threads it to postgres
	// when set; omit for uncapped.
	TimeoutSeconds *uint64 `json:"timeout_seconds,omitempty" validate:"omitempty,min=0,max=18446744073709551615"`
}

func (CliCommandAgentsLogsTokenUsageSubscribeRequest) SchemaTitle() string { return "cli.command.agents.logs.token_usage.subscribe.Request" }
func (v CliCommandAgentsLogsTokenUsageSubscribeRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandAgentsLogsTokenUsageSubscribeRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"agent_instance_hierarchy", "path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandAgentsLogsTokenUsageSubscribeRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandAgentsLogsTokenUsageSubscribeRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandAgentsLogsTokenUsageSubscribeRequest(alias)
	return nil
}
