// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandChannelsClosePath struct {
	ChannelsClose string `validate:"omitempty,oneof=channels/close" variantTitle:"Channels/close"`
}

func (v CliCommandChannelsClosePath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.ChannelsClose)
}

func (v *CliCommandChannelsClosePath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.ChannelsClose); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandChannelsClosePath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandChannelsClosePath) SchemaTitle() string { return "cli.command.channels.close.Path" }

