// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandTasksDeleteResponseSchemaPath struct {
	TasksDeleteResponseSchema string `validate:"omitempty,oneof=tasks/delete/response_schema" variantTitle:"Tasks/delete/responseSchema"`
}

func (v CliCommandTasksDeleteResponseSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.TasksDeleteResponseSchema)
}

func (v *CliCommandTasksDeleteResponseSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.TasksDeleteResponseSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandTasksDeleteResponseSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandTasksDeleteResponseSchemaPath) SchemaTitle() string { return "cli.command.tasks.delete.response_schema.Path" }

