// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandFunctionsResponseItemGetRequestSchema JsonValue

func (CliCommandFunctionsResponseItemGetRequestSchema) SchemaVariantTitle() string { return "GetRequestSchema" }

func (v CliCommandFunctionsResponseItemGetRequestSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandFunctionsResponseItemGetRequestSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandFunctionsResponseItemGetResponseSchema JsonValue

func (CliCommandFunctionsResponseItemGetResponseSchema) SchemaVariantTitle() string { return "GetResponseSchema" }

func (v CliCommandFunctionsResponseItemGetResponseSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandFunctionsResponseItemGetResponseSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandFunctionsResponseItemListRequestSchema JsonValue

func (CliCommandFunctionsResponseItemListRequestSchema) SchemaVariantTitle() string { return "ListRequestSchema" }

func (v CliCommandFunctionsResponseItemListRequestSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandFunctionsResponseItemListRequestSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandFunctionsResponseItemListResponseSchema JsonValue

func (CliCommandFunctionsResponseItemListResponseSchema) SchemaVariantTitle() string { return "ListResponseSchema" }

func (v CliCommandFunctionsResponseItemListResponseSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandFunctionsResponseItemListResponseSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandFunctionsResponseItemPublishRequestSchema JsonValue

func (CliCommandFunctionsResponseItemPublishRequestSchema) SchemaVariantTitle() string { return "PublishRequestSchema" }

func (v CliCommandFunctionsResponseItemPublishRequestSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandFunctionsResponseItemPublishRequestSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandFunctionsResponseItemPublishResponseSchema JsonValue

func (CliCommandFunctionsResponseItemPublishResponseSchema) SchemaVariantTitle() string { return "PublishResponseSchema" }

func (v CliCommandFunctionsResponseItemPublishResponseSchema) MarshalJSON() ([]byte, error) { return json.Marshal(JsonValue(v)) }
func (v *CliCommandFunctionsResponseItemPublishResponseSchema) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, (*JsonValue)(v)) }

type CliCommandFunctionsResponseItem struct {
	Executions *CliCommandFunctionsExecutionsCreateResponseItem 
	Get *FunctionsGetFunctionResponse 
	GetRequestSchema *CliCommandFunctionsResponseItemGetRequestSchema 
	GetResponseSchema *CliCommandFunctionsResponseItemGetResponseSchema 
	Inventions *CliCommandFunctionsInventionsResponseItem 
	List *CliCommandFunctionsListResponseItem 
	ListRequestSchema *CliCommandFunctionsResponseItemListRequestSchema 
	ListResponseSchema *CliCommandFunctionsResponseItemListResponseSchema 
	Profiles *CliCommandFunctionsProfilesResponseItem 
	Publish *CliCommandFunctionsPublishResponse 
	PublishRequestSchema *CliCommandFunctionsResponseItemPublishRequestSchema 
	PublishResponseSchema *CliCommandFunctionsResponseItemPublishResponseSchema 
}

func (v CliCommandFunctionsResponseItem) MarshalJSON() ([]byte, error) {
	if v.Executions != nil {
		return json.Marshal(v.Executions)
	}
	if v.Get != nil {
		return json.Marshal(v.Get)
	}
	if v.GetRequestSchema != nil {
		return json.Marshal(v.GetRequestSchema)
	}
	if v.GetResponseSchema != nil {
		return json.Marshal(v.GetResponseSchema)
	}
	if v.Inventions != nil {
		return json.Marshal(v.Inventions)
	}
	if v.List != nil {
		return json.Marshal(v.List)
	}
	if v.ListRequestSchema != nil {
		return json.Marshal(v.ListRequestSchema)
	}
	if v.ListResponseSchema != nil {
		return json.Marshal(v.ListResponseSchema)
	}
	if v.Profiles != nil {
		return json.Marshal(v.Profiles)
	}
	if v.Publish != nil {
		return json.Marshal(v.Publish)
	}
	if v.PublishRequestSchema != nil {
		return json.Marshal(v.PublishRequestSchema)
	}
	if v.PublishResponseSchema != nil {
		return json.Marshal(v.PublishResponseSchema)
	}
	return []byte("null"), nil
}

func (v *CliCommandFunctionsResponseItem) UnmarshalJSON(data []byte) error {
	{
		var try CliCommandFunctionsExecutionsCreateResponseItem
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.Executions = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsGetFunctionResponse
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.Get = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsResponseItemGetRequestSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.GetRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsResponseItemGetResponseSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.GetResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsInventionsResponseItem
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.Inventions = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsListResponseItem
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.List = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsResponseItemListRequestSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.ListRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsResponseItemListResponseSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.ListResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsProfilesResponseItem
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.Profiles = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsPublishResponse
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.Publish = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsResponseItemPublishRequestSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.PublishRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandFunctionsResponseItemPublishResponseSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandFunctionsResponseItem{}
			candidate.PublishResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of CliCommandFunctionsResponseItem")
}

func (v CliCommandFunctionsResponseItem) Validate() error {
	count := 0
	if v.Executions != nil { count++ }
	if v.Get != nil { count++ }
	if v.GetRequestSchema != nil { count++ }
	if v.GetResponseSchema != nil { count++ }
	if v.Inventions != nil { count++ }
	if v.List != nil { count++ }
	if v.ListRequestSchema != nil { count++ }
	if v.ListResponseSchema != nil { count++ }
	if v.Profiles != nil { count++ }
	if v.Publish != nil { count++ }
	if v.PublishRequestSchema != nil { count++ }
	if v.PublishResponseSchema != nil { count++ }
	if count != 1 {
		return fmt.Errorf("CliCommandFunctionsResponseItem: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (CliCommandFunctionsResponseItem) SchemaTitle() string { return "cli.command.functions.ResponseItem" }

