// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandLogsFunctionsInventionsRecursiveResponseGetRequestSchemaPath struct {
	LogsFunctionsInventionsRecursiveResponseGetRequestSchema string `validate:"omitempty,oneof=logs/functions/inventions/recursive/response/get/request_schema" variantTitle:"Logs/functions/inventions/recursive/response/get/requestSchema"`
}

func (v CliCommandLogsFunctionsInventionsRecursiveResponseGetRequestSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.LogsFunctionsInventionsRecursiveResponseGetRequestSchema)
}

func (v *CliCommandLogsFunctionsInventionsRecursiveResponseGetRequestSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.LogsFunctionsInventionsRecursiveResponseGetRequestSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandLogsFunctionsInventionsRecursiveResponseGetRequestSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandLogsFunctionsInventionsRecursiveResponseGetRequestSchemaPath) SchemaTitle() string { return "cli.command.logs.functions.inventions.recursive.response.get.request_schema.Path" }

