// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Agent identity + response routing args carried per call.
//
// When passed as `Some(&AgentArguments)` to a [`CommandExecutor`],
// subprocess-spawning executors (e.g. [`binary::BinaryExecutor`])
// apply ALL six fields to the spawned child's env atomically —
// `Some(v)` → set, `None` → `env_remove` so the parent's value for
// that var can't leak through. `None` for the whole bag means
// "inherit parent env unmodified". In-process executors (e.g.
// [`plugin::PluginExecutor`]) ignore the bag.
//
// Field ↔ env-var mapping (same as `EnvConfigBuilder` in
// `objectiveai-cli/src/run.rs`):
//
// - `agent_instance_hierarchy` ↔ `OBJECTIVEAI_AGENT_INSTANCE_HIERARCHY`
// - `agent_id` ↔ `OBJECTIVEAI_AGENT_ID`
// - `agent_full_id` ↔ `OBJECTIVEAI_AGENT_FULL_ID`
// - `agent_remote` ↔ `OBJECTIVEAI_AGENT_REMOTE`
// - `response_id` ↔ `OBJECTIVEAI_RESPONSE_ID`
// - `response_ids` ↔ `OBJECTIVEAI_RESPONSE_IDS`
// - `mcp_session_id` ↔ `MCP_SESSION_ID` (the MCP transport
//   session id minted by the MCP server, NOT an objectiveai-scoped
//   identifier — same env-var convention as
//   [`crate::mcp::MCP_SESSION_ID_ENV`])
type CliCommandAgentArguments struct {
	AgentFullID *string `json:"agent_full_id,omitempty"`
	AgentID *string `json:"agent_id,omitempty"`
	AgentInstanceHierarchy *string `json:"agent_instance_hierarchy,omitempty"`
	AgentRemote *string `json:"agent_remote,omitempty"`
	MCPSessionID *string `json:"mcp_session_id,omitempty"`
	ResponseID *string `json:"response_id,omitempty"`
	ResponseIds *string `json:"response_ids,omitempty"`
}

func (CliCommandAgentArguments) SchemaTitle() string { return "cli.command.AgentArguments" }
func (v CliCommandAgentArguments) Validate() error {
	return variantValidator.Struct(v)
}
