// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequest struct {
	Index uint64 `json:"index" validate:"min=0,max=18446744073709551615"`
	Jq *string `json:"jq"`
	MediaIndex *uint64 `json:"media_index" validate:"omitempty,min=0,max=18446744073709551615"`
	PathType CliCommandLogsAgentsCompletionsRequestNotificationsTextGetPath `json:"path_type"`
	ResponseID string `json:"response_id"`
}

func (CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequest) SchemaTitle() string { return "cli.command.logs.agents.completions.request.notifications.text.get.Request" }
func (v CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"index", "path_type", "response_id"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequest(alias)
	return nil
}
