// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandAgentsMcpResourcesReadRequest struct {
	// jq filter applied to the JSON output. Ignored when `python`
	// is also set — python overrides jq.
	Jq *string `json:"jq"`
	// Response token budget, `>= 1` (`0` is rejected at parse
	// time — omit entirely for unlimited). Forward-compatible
	// envelope data — no leaf enforces it yet.
	MaxTokens *uint64 `json:"max_tokens,omitempty" validate:"omitempty,min=0,max=18446744073709551615"`
	Params McpResourceReadResourceRequestParams `json:"params"`
	PathType CliCommandAgentsMcpResourcesReadPath `json:"path_type"`
	// Python transform applied to the JSON output. Overrides `jq`
	// when both are provided.
	Python *string `json:"python"`
	ResponseID string `json:"response_id"`
	// Wall-clock execution cap, in whole seconds. Parsed from
	// `--timeout` (humantime: `30s`, `5m`, `1h30m`), `> 0`
	// enforced at parse time. `db query` threads it to postgres
	// when set; omit for uncapped.
	TimeoutSeconds *uint64 `json:"timeout_seconds,omitempty" validate:"omitempty,min=0,max=18446744073709551615"`
}

func (CliCommandAgentsMcpResourcesReadRequest) SchemaTitle() string { return "cli.command.agents.mcp.resources.read.Request" }
func (v CliCommandAgentsMcpResourcesReadRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandAgentsMcpResourcesReadRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"params", "path_type", "response_id"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandAgentsMcpResourcesReadRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandAgentsMcpResourcesReadRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandAgentsMcpResourcesReadRequest(alias)
	return nil
}
