// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandConfigFunctionsProfilesFavoritesAddRequestSchemaPath struct {
	ConfigFunctionsProfilesFavoritesAddRequestSchema string `validate:"omitempty,oneof=config/functions/profiles/favorites/add/request_schema"`
}

func (v CliCommandConfigFunctionsProfilesFavoritesAddRequestSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.ConfigFunctionsProfilesFavoritesAddRequestSchema)
}

func (v *CliCommandConfigFunctionsProfilesFavoritesAddRequestSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.ConfigFunctionsProfilesFavoritesAddRequestSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandConfigFunctionsProfilesFavoritesAddRequestSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandConfigFunctionsProfilesFavoritesAddRequestSchemaPath) SchemaTitle() string { return "cli.command.config.functions.profiles.favorites.add.request_schema.Path" }

