// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type CliCommandConfigFunctionsProfilesPairsGetResponse struct {
	Favorites *[]CliCommandConfigFunctionsProfilesPairsFavoritesGetResponseItem `json:"favorites,omitempty"`
}

func (CliCommandConfigFunctionsProfilesPairsGetResponse) SchemaTitle() string { return "cli.command.config.functions.profiles.pairs.get.Response" }
func (v CliCommandConfigFunctionsProfilesPairsGetResponse) Validate() error {
	return variantValidator.Struct(v)
}
