// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandAgentsListAvailableResponseSchemaRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandAgentsListAvailableResponseSchemaPath `json:"path_type"`
}

func (CliCommandAgentsListAvailableResponseSchemaRequest) SchemaTitle() string { return "cli.command.agents.list.available.response_schema.Request" }
func (v CliCommandAgentsListAvailableResponseSchemaRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandAgentsListAvailableResponseSchemaRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandAgentsListAvailableResponseSchemaRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandAgentsListAvailableResponseSchemaRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandAgentsListAvailableResponseSchemaRequest(alias)
	return nil
}
