// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandConfigApiXTitleRequest struct {
	Get *CliCommandConfigApiXTitleGetRequest 
	GetRequestSchema *CliCommandConfigApiXTitleGetRequestSchemaRequest 
	GetResponseSchema *CliCommandConfigApiXTitleGetResponseSchemaRequest 
	Set *CliCommandConfigApiXTitleSetRequest 
	SetRequestSchema *CliCommandConfigApiXTitleSetRequestSchemaRequest 
	SetResponseSchema *CliCommandConfigApiXTitleSetResponseSchemaRequest 
}

func (v CliCommandConfigApiXTitleRequest) MarshalJSON() ([]byte, error) {
	if v.Get != nil {
		return json.Marshal(v.Get)
	}
	if v.GetRequestSchema != nil {
		return json.Marshal(v.GetRequestSchema)
	}
	if v.GetResponseSchema != nil {
		return json.Marshal(v.GetResponseSchema)
	}
	if v.Set != nil {
		return json.Marshal(v.Set)
	}
	if v.SetRequestSchema != nil {
		return json.Marshal(v.SetRequestSchema)
	}
	if v.SetResponseSchema != nil {
		return json.Marshal(v.SetResponseSchema)
	}
	return []byte("null"), nil
}

func (v *CliCommandConfigApiXTitleRequest) UnmarshalJSON(data []byte) error {
	{
		var try CliCommandConfigApiXTitleGetRequest
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigApiXTitleRequest{}
			candidate.Get = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigApiXTitleGetRequestSchemaRequest
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigApiXTitleRequest{}
			candidate.GetRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigApiXTitleGetResponseSchemaRequest
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigApiXTitleRequest{}
			candidate.GetResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigApiXTitleSetRequest
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigApiXTitleRequest{}
			candidate.Set = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigApiXTitleSetRequestSchemaRequest
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigApiXTitleRequest{}
			candidate.SetRequestSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandConfigApiXTitleSetResponseSchemaRequest
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandConfigApiXTitleRequest{}
			candidate.SetResponseSchema = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of CliCommandConfigApiXTitleRequest")
}

func (v CliCommandConfigApiXTitleRequest) Validate() error {
	count := 0
	if v.Get != nil { count++ }
	if v.GetRequestSchema != nil { count++ }
	if v.GetResponseSchema != nil { count++ }
	if v.Set != nil { count++ }
	if v.SetRequestSchema != nil { count++ }
	if v.SetResponseSchema != nil { count++ }
	if count != 1 {
		return fmt.Errorf("CliCommandConfigApiXTitleRequest: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (CliCommandConfigApiXTitleRequest) SchemaTitle() string { return "cli.command.config.api.x_title.Request" }

