// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoGetRequest struct {
	ID string `json:"id"`
	Jq *string `json:"jq"`
	MediaIndex uint64 `json:"media_index" validate:"min=0,max=18446744073709551615"`
	MessageIndex uint64 `json:"message_index" validate:"min=0,max=18446744073709551615"`
	PathType CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoGetPath `json:"path_type"`
}

func (CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoGetRequest) SchemaTitle() string { return "cli.command.logs.agents.completions.response.messages.assistant.video.get.Request" }
func (v CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoGetRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoGetRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"id", "media_index", "message_index", "path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoGetRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoGetRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoGetRequest(alias)
	return nil
}
