// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_command_execute.go from objectiveai-sdk-rs/src/cli/command/.
package objectiveai

import (
	"context"
	"fmt"
)

// LaboratoriesConfigAddressesGetResponseSchemaExecute — `laboratories config addresses get response_schema execute` (unary); the first stream item, rest discarded.
func LaboratoriesConfigAddressesGetResponseSchemaExecute(ctx context.Context, executor CommandExecutor, request CliCommandLaboratoriesConfigAddressesGetResponseSchemaRequest) (*JsonValue, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	wire["path_type"] = "laboratories/config/addresses/get/response_schema"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[JsonValue](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("laboratories config addresses get response_schema: cli produced no output before the end marker")
	}
	return first, nil
}

// LaboratoriesConfigAddressesGetResponseSchemaExecuteTransform — `laboratories config addresses get response_schema execute_transform` (unary); the first stream item, rest discarded.
func LaboratoriesConfigAddressesGetResponseSchemaExecuteTransform(ctx context.Context, executor CommandExecutor, request CliCommandLaboratoriesConfigAddressesGetResponseSchemaRequest, transform map[string]string) (*JsonValue, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	for k, v := range transform {
		wire[k] = v
	}
	wire["path_type"] = "laboratories/config/addresses/get/response_schema"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[JsonValue](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("laboratories config addresses get response_schema: cli produced no output before the end marker")
	}
	return first, nil
}
