// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandApiConfigHttpRefererGetRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandApiConfigHttpRefererGetPath `json:"path_type"`
	Scope CliCommandGetScope `json:"scope"`
}

func (CliCommandApiConfigHttpRefererGetRequest) SchemaTitle() string { return "cli.command.api.config.http_referer.get.Request" }
func (v CliCommandApiConfigHttpRefererGetRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandApiConfigHttpRefererGetRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type", "scope"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandApiConfigHttpRefererGetRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandApiConfigHttpRefererGetRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandApiConfigHttpRefererGetRequest(alias)
	return nil
}
