// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandFunctionsExecuteSwissSystemPath struct {
	FunctionsExecuteSwissSystem string `validate:"omitempty,oneof=functions/execute/swiss_system" variantTitle:"Functions/execute/swissSystem"`
}

func (v CliCommandFunctionsExecuteSwissSystemPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.FunctionsExecuteSwissSystem)
}

func (v *CliCommandFunctionsExecuteSwissSystemPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.FunctionsExecuteSwissSystem); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandFunctionsExecuteSwissSystemPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandFunctionsExecuteSwissSystemPath) SchemaTitle() string { return "cli.command.functions.execute.swiss_system.Path" }

