// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandFunctionsInventionsRecursiveCreateAlphaVectorRequestSchemaPath struct {
	FunctionsInventionsRecursiveCreateAlphaVectorRequestSchema string `validate:"omitempty,oneof=functions/inventions/recursive/create/alpha_vector/request_schema"`
}

func (v CliCommandFunctionsInventionsRecursiveCreateAlphaVectorRequestSchemaPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.FunctionsInventionsRecursiveCreateAlphaVectorRequestSchema)
}

func (v *CliCommandFunctionsInventionsRecursiveCreateAlphaVectorRequestSchemaPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.FunctionsInventionsRecursiveCreateAlphaVectorRequestSchema); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandFunctionsInventionsRecursiveCreateAlphaVectorRequestSchemaPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandFunctionsInventionsRecursiveCreateAlphaVectorRequestSchemaPath) SchemaTitle() string { return "cli.command.functions.inventions.recursive.create.alpha_vector.request_schema.Path" }

