// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Wire response for `tools get` — a lean projection of the on-disk
// manifest. `exec` is required (a tool always has a command). The
// on-disk-only fields (`cli_zip`, `source`) are intentionally absent;
// the CLI owns the full on-disk shape in its own `filesystem::tools`
// manifest types.
type CliCommandToolsGetResponseManifest struct {
	Description string `json:"description"`
	Exec CliCommandToolsGetExec `json:"exec"`
	Name string `json:"name"`
	Owner string `json:"owner"`
	Version string `json:"version"`
}

func (CliCommandToolsGetResponseManifest) SchemaTitle() string { return "cli.command.tools.get.ResponseManifest" }
func (v CliCommandToolsGetResponseManifest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandToolsGetResponseManifest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"description", "exec", "name", "owner", "version"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandToolsGetResponseManifest: missing required field %q", key)
		}
	}
	type Alias CliCommandToolsGetResponseManifest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandToolsGetResponseManifest(alias)
	return nil
}
