// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Viewer-stream mirror of [`Response`]: the response (nested under
// `value`) plus the broadcast stream `id` and the originating request's
// `path_type`.
type CliCommandDbConfigDatabaseGetViewerResponse struct {
	ID string `json:"id"`
	PathType CliCommandDbConfigDatabaseGetPath `json:"path_type"`
	Value CliCommandDbConfigDatabaseGetResponse `json:"value"`
}

func (CliCommandDbConfigDatabaseGetViewerResponse) SchemaTitle() string { return "cli.command.db.config.database.get.ViewerResponse" }
func (v CliCommandDbConfigDatabaseGetViewerResponse) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandDbConfigDatabaseGetViewerResponse) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"id", "path_type", "value"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandDbConfigDatabaseGetViewerResponse: missing required field %q", key)
		}
	}
	type Alias CliCommandDbConfigDatabaseGetViewerResponse
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandDbConfigDatabaseGetViewerResponse(alias)
	return nil
}
