// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// One laboratory served by a connected laboratory HOST. There is no
// local-vs-remote split — machine identity is the only provenance,
// the same logic regardless of where the host runs.
type CliCommandLaboratoriesListResponseItem struct {
	// Unix seconds when the laboratory container was created, from
	// podman's container record. `None` when the host didn't report
	// it.
	CreatedAt *int64 `json:"created_at,omitempty" validate:"omitempty,min=-9223372036854775808,max=9223372036854775807"`
	Cwd string `json:"cwd"`
	Env []CliCommandLaboratoriesCreateEnvVar `json:"env"`
	ID string `json:"id"`
	Image string `json:"image"`
	// The machine whose laboratory host serves this laboratory.
	Machine *MachineMachineIdentity `json:"machine,omitempty"`
	// The state (on that machine) the serving host serves —
	// laboratory ids are only unique per (machine, state).
	MachineState *string `json:"machine_state,omitempty"`
	Mounts []CliCommandLaboratoriesCreateMount `json:"mounts"`
}

func (CliCommandLaboratoriesListResponseItem) SchemaTitle() string { return "cli.command.laboratories.list.ResponseItem" }
func (v CliCommandLaboratoriesListResponseItem) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandLaboratoriesListResponseItem) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"cwd", "env", "id", "image", "mounts"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandLaboratoriesListResponseItem: missing required field %q", key)
		}
	}
	type Alias CliCommandLaboratoriesListResponseItem
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandLaboratoriesListResponseItem(alias)
	return nil
}
