// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type CliCommandFunctionsExecuteSwissSystemRequestDangerousAdvanced struct {
	// Deterministic seed for downstream mock agents. Forwarded
	// to every per-task `AgentCompletionCreateParams.seed`.
	Seed *int64 `json:"seed,omitempty" validate:"omitempty,min=-9223372036854775808,max=9223372036854775807"`
	Stream *bool `json:"stream,omitempty"`
}

func (CliCommandFunctionsExecuteSwissSystemRequestDangerousAdvanced) SchemaTitle() string { return "cli.command.functions.execute.swiss_system.RequestDangerousAdvanced" }
func (v CliCommandFunctionsExecuteSwissSystemRequestDangerousAdvanced) Validate() error {
	return variantValidator.Struct(v)
}
