// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandApiKillPath struct {
	APIKill string `validate:"omitempty,oneof=api/kill" variantTitle:"Api/kill"`
}

func (v CliCommandApiKillPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.APIKill)
}

func (v *CliCommandApiKillPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.APIKill); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandApiKillPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandApiKillPath) SchemaTitle() string { return "cli.command.api.kill.Path" }

