// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type CliCommandFunctionsExecutionsCreateStandardPath struct {
	FunctionsExecutionsCreateStandard string `validate:"omitempty,oneof=functions/executions/create/standard"`
}

func (v CliCommandFunctionsExecutionsCreateStandardPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.FunctionsExecutionsCreateStandard)
}

func (v *CliCommandFunctionsExecutionsCreateStandardPath) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.FunctionsExecutionsCreateStandard); err != nil {
		return err
	}
	return v.Validate()
}

func (v CliCommandFunctionsExecutionsCreateStandardPath) Validate() error {
	return variantValidator.Struct(v)
}
func (CliCommandFunctionsExecutionsCreateStandardPath) SchemaTitle() string { return "cli.command.functions.executions.create.standard.Path" }

