// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandToolsGetViewerResponse struct {
	ID string `json:"id"`
	PathType CliCommandToolsGetPath `json:"path_type"`
	Value *CliCommandToolsGetResponseManifest `json:"value"`
}

func (CliCommandToolsGetViewerResponse) SchemaTitle() string { return "cli.command.tools.get.ViewerResponse" }
func (v CliCommandToolsGetViewerResponse) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandToolsGetViewerResponse) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"id", "path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandToolsGetViewerResponse: missing required field %q", key)
		}
	}
	type Alias CliCommandToolsGetViewerResponse
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandToolsGetViewerResponse(alias)
	return nil
}
