// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Subscribe's wire shape: either a token-usage snapshot (`Item`) or
// the literal string `"agents_inactive"`. `#[serde(untagged)]` so
// `Item` passes through as a plain object and `AgentsInactive` as a
// bare string — the same convention as `agents logs subscribe`.
type CliCommandAgentsLogsTokenUsageSubscribeResponseItem struct {
	Item *CliCommandAgentsLogsTokenUsageSubscribeTokenUsage 
	AgentsInactive *CliCommandAgentsLogsTokenUsageSubscribeAgentsInactiveTag 
}

func (v CliCommandAgentsLogsTokenUsageSubscribeResponseItem) MarshalJSON() ([]byte, error) {
	if v.Item != nil {
		return json.Marshal(v.Item)
	}
	if v.AgentsInactive != nil {
		return json.Marshal(v.AgentsInactive)
	}
	return []byte("null"), nil
}

func (v *CliCommandAgentsLogsTokenUsageSubscribeResponseItem) UnmarshalJSON(data []byte) error {
	{
		var try CliCommandAgentsLogsTokenUsageSubscribeTokenUsage
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandAgentsLogsTokenUsageSubscribeResponseItem{}
			candidate.Item = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandAgentsLogsTokenUsageSubscribeAgentsInactiveTag
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandAgentsLogsTokenUsageSubscribeResponseItem{}
			candidate.AgentsInactive = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of CliCommandAgentsLogsTokenUsageSubscribeResponseItem")
}

func (v CliCommandAgentsLogsTokenUsageSubscribeResponseItem) Validate() error {
	count := 0
	if v.Item != nil { count++ }
	if v.AgentsInactive != nil { count++ }
	if count != 1 {
		return fmt.Errorf("CliCommandAgentsLogsTokenUsageSubscribeResponseItem: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (CliCommandAgentsLogsTokenUsageSubscribeResponseItem) SchemaTitle() string { return "cli.command.agents.logs.token_usage.subscribe.ResponseItem" }

