// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_command_execute.go from objectiveai-sdk-rs/src/cli/command/.
package objectiveai

import (
	"context"
	"fmt"
)

// PluginsInstallFilesystemExecute — `plugins install filesystem execute` (unary); the first stream item, rest discarded.
func PluginsInstallFilesystemExecute(ctx context.Context, executor CommandExecutor, request CliCommandPluginsInstallFilesystemRequest) (*CliCommandPluginsInstallFilesystemResponse, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	wire["path_type"] = "plugins/install/filesystem"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[CliCommandPluginsInstallFilesystemResponse](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("plugins install filesystem: cli produced no output before the end marker")
	}
	return first, nil
}

// PluginsInstallFilesystemExecuteTransform — `plugins install filesystem execute_transform` (unary); the first stream item, rest discarded.
func PluginsInstallFilesystemExecuteTransform(ctx context.Context, executor CommandExecutor, request CliCommandPluginsInstallFilesystemRequest, transform map[string]string) (*JsonValue, error) {
	wire, err := cliWire(request)
	if err != nil {
		return nil, err
	}
	delete(wire, "jq")
	delete(wire, "python")
	for k, v := range transform {
		wire[k] = v
	}
	wire["path_type"] = "plugins/install/filesystem"
	raw, err := executor.Execute(ctx, wire)
	if err != nil {
		return nil, err
	}
	first, err := NewCliStream[JsonValue](raw).First()
	if err != nil {
		return nil, err
	}
	if first == nil {
		return nil, fmt.Errorf("plugins install filesystem: cli produced no output before the end marker")
	}
	return first, nil
}
