// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandConfigAgentsFavoritesGetResponseSchemaRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandConfigAgentsFavoritesGetResponseSchemaPath `json:"path_type"`
}

func (CliCommandConfigAgentsFavoritesGetResponseSchemaRequest) SchemaTitle() string { return "cli.command.config.agents.favorites.get.response_schema.Request" }
func (v CliCommandConfigAgentsFavoritesGetResponseSchemaRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandConfigAgentsFavoritesGetResponseSchemaRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandConfigAgentsFavoritesGetResponseSchemaRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandConfigAgentsFavoritesGetResponseSchemaRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandConfigAgentsFavoritesGetResponseSchemaRequest(alias)
	return nil
}
