// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type CliCommandConfigApiGetResponseSchemaRequest struct {
	Jq *string `json:"jq"`
	PathType CliCommandConfigApiGetResponseSchemaPath `json:"path_type"`
}

func (CliCommandConfigApiGetResponseSchemaRequest) SchemaTitle() string { return "cli.command.config.api.get.response_schema.Request" }
func (v CliCommandConfigApiGetResponseSchemaRequest) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliCommandConfigApiGetResponseSchemaRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"path_type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliCommandConfigApiGetResponseSchemaRequest: missing required field %q", key)
		}
	}
	type Alias CliCommandConfigApiGetResponseSchemaRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliCommandConfigApiGetResponseSchemaRequest(alias)
	return nil
}
