// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Viewer-stream mirror of [`Request`] — the real command requests only
// (schema-introspection variants are excluded; the viewer streams
// actual command traffic). Untagged: each variant carries the leaf's
// `path_type`, so it stays discriminable.
type CliCommandDaemonViewerRequest struct {
	Spawn *CliCommandDaemonSpawnViewerRequest 
	Kill *CliCommandDaemonKillViewerRequest 
}

func (v CliCommandDaemonViewerRequest) MarshalJSON() ([]byte, error) {
	if v.Spawn != nil {
		return json.Marshal(v.Spawn)
	}
	if v.Kill != nil {
		return json.Marshal(v.Kill)
	}
	return []byte("null"), nil
}

func (v *CliCommandDaemonViewerRequest) UnmarshalJSON(data []byte) error {
	{
		var try CliCommandDaemonSpawnViewerRequest
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandDaemonViewerRequest{}
			candidate.Spawn = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try CliCommandDaemonKillViewerRequest
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := CliCommandDaemonViewerRequest{}
			candidate.Kill = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of CliCommandDaemonViewerRequest")
}

func (v CliCommandDaemonViewerRequest) Validate() error {
	count := 0
	if v.Spawn != nil { count++ }
	if v.Kill != nil { count++ }
	if count != 1 {
		return fmt.Errorf("CliCommandDaemonViewerRequest: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (CliCommandDaemonViewerRequest) SchemaTitle() string { return "cli.command.daemon.ViewerRequest" }

