// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression struct {
	Context *FunctionsExpressionExpression `json:"context,omitempty"`
	Items FunctionsExpressionExpression `json:"items"`
}

func (FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression) SchemaTitle() string { return "functions.alpha_vector.expression.VectorFunctionInputValueExpression" }
func (v FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression) Validate() error {
	return variantValidator.Struct(v)
}

func (v *FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"items"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression: missing required field %q", key)
		}
	}
	type Alias FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression(alias)
	return nil
}
