// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type FunctionsAlphaScalarPlaceholderScalarFunctionTaskExpression struct {
	Depth uint64 `json:"depth" validate:"min=0,max=18446744073709551615"`
	Input FunctionsExpressionExpression `json:"input"`
	InputSchema FunctionsExpressionObjectInputSchema `json:"input_schema"`
	MaxBranchWidth uint64 `json:"max_branch_width" validate:"min=0,max=18446744073709551615"`
	MaxLeafWidth uint64 `json:"max_leaf_width" validate:"min=0,max=18446744073709551615"`
	MinBranchWidth uint64 `json:"min_branch_width" validate:"min=0,max=18446744073709551615"`
	MinLeafWidth uint64 `json:"min_leaf_width" validate:"min=0,max=18446744073709551615"`
	Name string `json:"name"`
	Skip *FunctionsExpressionExpression `json:"skip,omitempty"`
	Spec string `json:"spec"`
}

func (FunctionsAlphaScalarPlaceholderScalarFunctionTaskExpression) SchemaTitle() string { return "functions.alpha_scalar.PlaceholderScalarFunctionTaskExpression" }
func (v FunctionsAlphaScalarPlaceholderScalarFunctionTaskExpression) Validate() error {
	return variantValidator.Struct(v)
}

func (v *FunctionsAlphaScalarPlaceholderScalarFunctionTaskExpression) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"depth", "input", "input_schema", "max_branch_width", "max_leaf_width", "min_branch_width", "min_leaf_width", "name", "spec"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("FunctionsAlphaScalarPlaceholderScalarFunctionTaskExpression: missing required field %q", key)
		}
	}
	type Alias FunctionsAlphaScalarPlaceholderScalarFunctionTaskExpression
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = FunctionsAlphaScalarPlaceholderScalarFunctionTaskExpression(alias)
	return nil
}
