// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type HttpViewerAgentCompletionRequest struct {
	Begin *HttpViewerAgentCompletionCreateParams 
	Continue *AgentCompletionsResponseStreamingAgentCompletionChunk 
	Error *HttpViewerResponseError 
}

func (v HttpViewerAgentCompletionRequest) MarshalJSON() ([]byte, error) {
	if v.Begin != nil {
		return json.Marshal(v.Begin)
	}
	if v.Continue != nil {
		return json.Marshal(v.Continue)
	}
	if v.Error != nil {
		return json.Marshal(v.Error)
	}
	return []byte("null"), nil
}

func (v *HttpViewerAgentCompletionRequest) UnmarshalJSON(data []byte) error {
	{
		var try HttpViewerAgentCompletionCreateParams
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := HttpViewerAgentCompletionRequest{}
			candidate.Begin = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentCompletionsResponseStreamingAgentCompletionChunk
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := HttpViewerAgentCompletionRequest{}
			candidate.Continue = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try HttpViewerResponseError
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := HttpViewerAgentCompletionRequest{}
			candidate.Error = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of HttpViewerAgentCompletionRequest")
}

func (v HttpViewerAgentCompletionRequest) Validate() error {
	count := 0
	if v.Begin != nil { count++ }
	if v.Continue != nil { count++ }
	if v.Error != nil { count++ }
	if count != 1 {
		return fmt.Errorf("HttpViewerAgentCompletionRequest: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (HttpViewerAgentCompletionRequest) SchemaTitle() string { return "http.viewer.AgentCompletionRequest" }

