// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// An error from a [`BuilderChunk`](super::BuilderChunk).
type LaboratoriesExecutionsResponseStreamingInnerErrorBuilder struct {
	// Agent completion index within the builder (matches `BuilderChunk::agent_index`).
	AgentCompletionIndex uint64 `json:"agent_completion_index" validate:"min=0,max=18446744073709551615"`
	// Builder index (matches `BuilderChunk::index`).
	BuilderIndex uint64 `json:"builder_index" validate:"min=0,max=18446744073709551615"`
	// The underlying error from the agent completion.
	Error ErrorResponseError `json:"error"`
	Type string `json:"type" validate:"oneof=builder"`
}

func (v *LaboratoriesExecutionsResponseStreamingInnerErrorBuilder) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"agent_completion_index", "builder_index", "error", "type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("LaboratoriesExecutionsResponseStreamingInnerErrorBuilder: missing required field %q", key)
		}
	}
	type Alias LaboratoriesExecutionsResponseStreamingInnerErrorBuilder
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = LaboratoriesExecutionsResponseStreamingInnerErrorBuilder(alias)
	return nil
}
func (LaboratoriesExecutionsResponseStreamingInnerErrorBuilder) SchemaVariantTitle() string { return "Builder" }

// An error from an [`EvaluationChunk`](super::EvaluationChunk).
type LaboratoriesExecutionsResponseStreamingInnerErrorEvaluation struct {
	// Agent completion index within the evaluation (matches `EvaluationChunk::agent_index`).
	AgentCompletionIndex uint64 `json:"agent_completion_index" validate:"min=0,max=18446744073709551615"`
	// The underlying error from the agent completion.
	Error ErrorResponseError `json:"error"`
	// Evaluation index (matches `EvaluationChunk::index`).
	EvaluationIndex uint64 `json:"evaluation_index" validate:"min=0,max=18446744073709551615"`
	Type string `json:"type" validate:"oneof=evaluation"`
}

func (v *LaboratoriesExecutionsResponseStreamingInnerErrorEvaluation) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"agent_completion_index", "error", "evaluation_index", "type"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("LaboratoriesExecutionsResponseStreamingInnerErrorEvaluation: missing required field %q", key)
		}
	}
	type Alias LaboratoriesExecutionsResponseStreamingInnerErrorEvaluation
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = LaboratoriesExecutionsResponseStreamingInnerErrorEvaluation(alias)
	return nil
}
func (LaboratoriesExecutionsResponseStreamingInnerErrorEvaluation) SchemaVariantTitle() string { return "Evaluation" }

// An inner error from a [`LaboratoryExecutionChunk`](super::LaboratoryExecutionChunk).
//
// Yielded by [`LaboratoryExecutionChunk::inner_errors`](super::LaboratoryExecutionChunk::inner_errors).
// The variant identifies which child collection the failing agent
// completion came from; fields locate it by `index` (builder or
// evaluation index) and `agent_index` (agent slot within that builder
// or evaluation), with the underlying [`ResponseError`](error::ResponseError)
// held as a `Cow` so iteration is zero-allocation while deserialization
// still produces a self-owning value.
//
// Wire shape (internally tagged on `"type"`):
// ```json
// { "type": "builder",    "builder_index": 0,    "agent_completion_index": 1, "error": { } }
// { "type": "evaluation", "evaluation_index": 2, "agent_completion_index": 0, "error": { } }
// ```
//
// Does NOT include the lab chunk's own top-level `.error` — that
// field is the chunk's own failure state and is reachable directly
// via [`LaboratoryExecutionChunk::error`](super::LaboratoryExecutionChunk::error).
type LaboratoriesExecutionsResponseStreamingInnerError struct {
	// An error from a [`BuilderChunk`](super::BuilderChunk).
	Builder *LaboratoriesExecutionsResponseStreamingInnerErrorBuilder 
	// An error from an [`EvaluationChunk`](super::EvaluationChunk).
	Evaluation *LaboratoriesExecutionsResponseStreamingInnerErrorEvaluation 
}

func (v LaboratoriesExecutionsResponseStreamingInnerError) MarshalJSON() ([]byte, error) {
	if v.Builder != nil {
		return json.Marshal(v.Builder)
	}
	if v.Evaluation != nil {
		return json.Marshal(v.Evaluation)
	}
	return []byte("null"), nil
}

func (v *LaboratoriesExecutionsResponseStreamingInnerError) UnmarshalJSON(data []byte) error {
	{
		var try LaboratoriesExecutionsResponseStreamingInnerErrorBuilder
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := LaboratoriesExecutionsResponseStreamingInnerError{}
			candidate.Builder = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try LaboratoriesExecutionsResponseStreamingInnerErrorEvaluation
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := LaboratoriesExecutionsResponseStreamingInnerError{}
			candidate.Evaluation = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of LaboratoriesExecutionsResponseStreamingInnerError")
}

func (v LaboratoriesExecutionsResponseStreamingInnerError) Validate() error {
	count := 0
	if v.Builder != nil { count++ }
	if v.Evaluation != nil { count++ }
	if count != 1 {
		return fmt.Errorf("LaboratoriesExecutionsResponseStreamingInnerError: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (LaboratoriesExecutionsResponseStreamingInnerError) SchemaTitle() string { return "laboratories.executions.response.streaming.InnerError" }

