// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { ClientObjectiveaiMcpClientRequestMcpListChangedKindSchema } from "./mcpListChangedKind";

export const ClientObjectiveaiMcpClientRequestMcpListChangedSchema = z.object({
  kind: ClientObjectiveaiMcpClientRequestMcpListChangedKindSchema.describe("Which catalog changed."),
  mcp_session_id: z.string().describe("The remote-minted `Mcp-Session-Id` of the upstream MCP\nconnection that fired the list-changed notification."),
}).describe("Payload for [`Payload::McpListChanged`].").meta({ title: "client_objectiveai_mcp.client_request.McpListChanged" });
export type ClientObjectiveaiMcpClientRequestMcpListChanged = z.infer<typeof ClientObjectiveaiMcpClientRequestMcpListChangedSchema>;
