// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandTasksRunResponseSchemaPathSchema = z.literal("tasks/run/response_schema").meta({ title: "cli.command.tasks.run.response_schema.Path" });
export type CliCommandTasksRunResponseSchemaPath = z.infer<typeof CliCommandTasksRunResponseSchemaPathSchema>;
