// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandSwarmsListRequestSchemaPathSchema } from "./path";

export const CliCommandSwarmsListRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandSwarmsListRequestSchemaPathSchema,
}).meta({ title: "cli.command.swarms.list.request_schema.Request" });
export type CliCommandSwarmsListRequestSchemaRequest = z.infer<typeof CliCommandSwarmsListRequestSchemaRequestSchema>;
