// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsResponseMessagesToolCallsSubscribeRequestSchemaPathSchema } from "./path";

export const CliCommandLogsAgentsCompletionsResponseMessagesToolCallsSubscribeRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandLogsAgentsCompletionsResponseMessagesToolCallsSubscribeRequestSchemaPathSchema,
}).meta({ title: "cli.command.logs.agents.completions.response.messages.tool_calls.subscribe.request_schema.Request" });
export type CliCommandLogsAgentsCompletionsResponseMessagesToolCallsSubscribeRequestSchemaRequest = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesToolCallsSubscribeRequestSchemaRequestSchema>;
