[package]
name = "objectiveai-pyo3"
version = "2.0.0"
edition = "2024"
authors = ["ObjectiveAI <admin@objectiveai.dev>"]
description = "Python bindings for ObjectiveAI"
license = "MIT"
repository = "https://github.com/ObjectiveAI/objectiveai"
homepage = "https://objectiveai.dev"
readme = "README.md"
keywords = ["llm", "ai", "swarm", "python"]
publish = true

[lib]
name = "objectiveai_pyo3"
crate-type = ["cdylib"]

[dependencies]
arbitrary = "1.4.2"
objectiveai = { path = "../objectiveai-rs", version = "2.0.0", default-features = false }
pyo3 = { version = "0.28", features = ["extension-module"] }
pythonize = "0.28"
rand = "0.9.2"
rust_decimal = { version = "1.40.0", features = ["serde-float"] }
serde = "1.0.228"
serde_json = { version = "1.0.149", features = ["preserve_order"] }
