// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { JsonValueSchema } from "../../../../../jsonValue";
import { CliCommandConfigViewerAddressGetResponseSchema } from "./get/response";
import { CliCommandOkSchema } from "../../../ok";

export const CliCommandConfigViewerAddressResponseSchema = z.union([z.object({
  Get: CliCommandConfigViewerAddressGetResponseSchema,
}).strict().meta({"variantTitle":"Get"}), z.object({
  GetRequestSchema: JsonValueSchema,
}).strict().meta({"variantTitle":"GetRequestSchema"}), z.object({
  GetResponseSchema: JsonValueSchema,
}).strict().meta({"variantTitle":"GetResponseSchema"}), z.object({
  Set: CliCommandOkSchema,
}).strict().meta({"variantTitle":"Set"}), z.object({
  SetRequestSchema: JsonValueSchema,
}).strict().meta({"variantTitle":"SetRequestSchema"}), z.object({
  SetResponseSchema: JsonValueSchema,
}).strict().meta({"variantTitle":"SetResponseSchema"})]).meta({ title: "cli.command.config.viewer.address.Response" });
export type CliCommandConfigViewerAddressResponse = z.infer<typeof CliCommandConfigViewerAddressResponseSchema>;
