[package]
name = "diverge-daemon-sdk"
version = "2.3.0"
edition = "2024"
authors = ["Diverge <admin@diverge.network>"]
description = "The SDK of the Diverge daemon"
license = "MIT"
repository = "https://github.com/ObjectiveAI/objectiveai"
homepage = "https://diverge.network"
publish = false

[dependencies]
