// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandFunctionsProfilesPublishRequestSchema } from "./request";

export const CliCommandFunctionsProfilesPublishViewerRequestSchema = z.object({
  id: z.string(),
  value: CliCommandFunctionsProfilesPublishRequestSchema,
}).describe("Viewer-stream mirror of [`Request`]: the request (nested under\n`value`, `path_type` and all) plus the broadcast stream `id`.").meta({ title: "cli.command.functions.profiles.publish.ViewerRequest" });
export type CliCommandFunctionsProfilesPublishViewerRequest = z.infer<typeof CliCommandFunctionsProfilesPublishViewerRequestSchema>;
