// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandApiKillRequestSchemaPathSchema = z.literal("api/kill/request_schema").meta({ title: "cli.command.api.kill.request_schema.Path" });
export type CliCommandApiKillRequestSchemaPath = z.infer<typeof CliCommandApiKillRequestSchemaPathSchema>;
