# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_viewer_request_token_usage():
    from objectiveai_sdk.cli.command.agents.logs import ViewerRequestTokenUsage
    schema = ViewerRequestTokenUsage.model_json_schema()
