# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_resource_contents_union_text():
    from objectiveai.mcp.shared import ResourceContentsUnionText
    schema = ResourceContentsUnionText.model_json_schema()
