// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const ClientObjectiveaiMcpMcpKindSchema = z.union([z.object({
  type: z.literal("objective_ai"),
}).describe("The CLI's primary `objectiveai-mcp` upstream — the local MCP\nserver bound at the CLI process's `--mcp-address`.").meta({"variantTitle":"ObjectiveAI"}), z.object({
  mcp: z.string(),
  name: z.string(),
  owner: z.string(),
  type: z.literal("other"),
  version: z.string(),
}).describe("A plugin-hosted MCP server. Identified by the plugin's\n`(owner, name, version)` tuple plus the `mcp` server name\nwithin that plugin's manifest. Mirrors the API URL\n`/{owner}/{name}/{version}/{mcp}` and the agent declaration's\n`plugins[i].{owner,name,version}.mcp_servers[j].name`.").meta({"variantTitle":"Other"})]).describe("Which CLI-hosted MCP server a frame belongs to. Stamped on every\n[`super::server_request::Request`] / [`super::server_response::Response`]\nenvelope and on every [`super::client_request::McpListChanged`]\npayload so the CLI's per-MCP dispatch table can route by enum\nrather than by parsing the proxy's URL path on every hop.\n\nWire shape: `{\"type\":\"objective_ai\"}` or\n`{\"type\":\"other\",\"owner\":\"…\",\"name\":\"…\",\"version\":\"…\",\"mcp\":\"…\"}`.\n\nThe four discriminator fields on `Other` mirror the API's\n`/{owner}/{name}/{version}/{mcp}` URL path that the proxy dials\nfor plugin-hosted MCP servers.").meta({ title: "client_objectiveai_mcp.McpKind" });
export type ClientObjectiveaiMcpMcpKind = z.infer<typeof ClientObjectiveaiMcpMcpKindSchema>;
