# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_inline_swarm_base():
    from objectiveai_sdk.swarm import InlineSwarmBase
    schema = InlineSwarmBase.model_json_schema()
