// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsGetResponseSchemaPathSchema } from "./path";

export const CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsGetResponseSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsGetResponseSchemaPathSchema,
}).meta({ title: "cli.command.logs.agents.completions.response.messages.assistant.tool_calls.get.response_schema.Request" });
export type CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsGetResponseSchemaRequest = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesAssistantToolCallsGetResponseSchemaRequestSchema>;
