# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_agent_with_fallbacks_remote():
    from objectiveai_sdk.agent import AgentWithFallbacksRemote
    schema = AgentWithFallbacksRemote.model_json_schema()
