# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_upstream_mock():
    from objectiveai_sdk.agent import UpstreamMock
    schema = UpstreamMock.model_json_schema()
