# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_remote_agent_with_fallbacks_mock():
    from objectiveai_sdk.agent import RemoteAgentWithFallbacksMock
    schema = RemoteAgentWithFallbacksMock.model_json_schema()
