# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_auth_envelope():
    from objectiveai_sdk.cli.command.command_executor import AuthEnvelope
    schema = AuthEnvelope.model_json_schema()
