// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsAgentsCompletionsResponseMessagesFileClearResponseSchema = z.object({
  count: z.number().int().min(0).max(18446744073709552000),
}).meta({ title: "cli.command.logs.agents.completions.response.messages.file.clear.Response" });
export type CliCommandLogsAgentsCompletionsResponseMessagesFileClearResponse = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesFileClearResponseSchema>;
