// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandKillAllResponseSchema = z.object({
  killed: z.number().int().min(0).max(4294967295),
}).meta({ title: "cli.command.kill_all.Response" });
export type CliCommandKillAllResponse = z.infer<typeof CliCommandKillAllResponseSchema>;
