// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { AgentCompletionsResponseStreamingMessageChunkSchema } from "./messageChunk";
import { AgentCompletionsResponseStreamingObjectSchema } from "./object";
import { AgentCompletionsResponseUsageSchema } from "../usage";
import { AgentUpstreamSchema } from "../../../upstream";
import { ErrorResponseErrorSchema } from "../../../../error/responseError";

export const AgentCompletionsResponseStreamingAgentCompletionChunkSchema = z.object({
  continuation: z.string().nullable().describe("Continuation state for multi-turn conversations (only present in the final chunk).").meta({ omitempty: true }).optional(),
  created: z.number().int().min(0).max(18446744073709552000),
  error: ErrorResponseErrorSchema.nullable().describe("Error details if this completion failed.").meta({ omitempty: true }).optional(),
  id: z.string(),
  messages: z.array(AgentCompletionsResponseStreamingMessageChunkSchema),
  object: AgentCompletionsResponseStreamingObjectSchema.describe("The object type (always \"agent.completion.chunk\")."),
  upstream: AgentUpstreamSchema.describe("Upstream provider"),
  usage: AgentCompletionsResponseUsageSchema.nullable().describe("Token usage (only present in the final chunk).").meta({ omitempty: true }).optional(),
}).describe("A chunk of a streaming agent completion response.\n\nMultiple chunks are received via Server-Sent Events and can be\naccumulated into a complete [`AgentCompletion`](response::unary::AgentCompletion)\nusing the [`push`](Self::push) method.").meta({ title: "agent.completions.response.streaming.AgentCompletionChunk" });
export type AgentCompletionsResponseStreamingAgentCompletionChunk = z.infer<typeof AgentCompletionsResponseStreamingAgentCompletionChunkSchema>;
