# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai_sdk.cli.command.plugins.get.response_binaries import ResponseBinaries
from objectiveai_sdk.cli.command.plugins.get.response_mcp_server import ResponseMcpServer
from objectiveai_sdk.cli.command.plugins.get.response_viewer_route import ResponseViewerRoute


class ResponseManifest(BaseModel):
    model_config = ConfigDict(title='cli.command.plugins.get.ResponseManifest')

    author: Optional[str] = Field(None, json_schema_extra={'omitempty': True})
    binaries: ResponseBinaries
    description: str
    homepage: Optional[str] = Field(None, json_schema_extra={'omitempty': True})
    license: Optional[str] = Field(None, json_schema_extra={'omitempty': True})
    mcp_servers: list[ResponseMcpServer]
    mobile_ready: bool
    name: str
    owner: str
    source: str
    version: str
    viewer_routes: list[ResponseViewerRoute]
    viewer_url: Optional[str] = Field(None, json_schema_extra={'omitempty': True})
    viewer_zip: Optional[str] = Field(None, json_schema_extra={'omitempty': True})

