// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { CliStream } from "../../../cliStream";
import { type CliCommandDevelopmentViewerSetRequest } from "./request";
import { CliCommandDevelopmentViewerSetResponseSchema, type CliCommandDevelopmentViewerSetResponse } from "./response";
import { type CommandExecutor } from "../../../executor";
import { CliErrorSchema, type CliError } from "../../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../../jsonValue";

/** `development viewer set execute` — unary; first stream item, rest discarded. */
export async function developmentViewerSetExecute(executor: CommandExecutor, request: Omit<CliCommandDevelopmentViewerSetRequest, "path_type">): Promise<CliError | CliCommandDevelopmentViewerSetResponse> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "development/viewer/set" }), z.union([CliErrorSchema, CliCommandDevelopmentViewerSetResponseSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("development viewer set: cli produced no output before the end marker");
  }
  return first;
}

/** `development viewer set execute_transform` — unary; first stream item, rest discarded. */
export async function developmentViewerSetExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandDevelopmentViewerSetRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "development/viewer/set" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("development viewer set: cli produced no output before the end marker");
  }
  return first;
}
