// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsRequestNotificationsTextGetPathSchema } from "./path";

export const CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequestSchema = z.object({
  index: z.number().int().min(0).max(18446744073709552000),
  jq: z.string().nullable().optional(),
  media_index: z.number().int().min(0).max(18446744073709552000).nullable().optional(),
  path_type: CliCommandLogsAgentsCompletionsRequestNotificationsTextGetPathSchema,
  response_id: z.string(),
}).meta({ title: "cli.command.logs.agents.completions.request.notifications.text.get.Request" });
export type CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequest = z.infer<typeof CliCommandLogsAgentsCompletionsRequestNotificationsTextGetRequestSchema>;
