// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsRequestNotificationsVideoGetRequestSchemaPathSchema } from "./path";

export const CliCommandLogsAgentsCompletionsRequestNotificationsVideoGetRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandLogsAgentsCompletionsRequestNotificationsVideoGetRequestSchemaPathSchema,
}).meta({ title: "cli.command.logs.agents.completions.request.notifications.video.get.request_schema.Request" });
export type CliCommandLogsAgentsCompletionsRequestNotificationsVideoGetRequestSchemaRequest = z.infer<typeof CliCommandLogsAgentsCompletionsRequestNotificationsVideoGetRequestSchemaRequestSchema>;
