// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandOkSchema } from "../../../../ok";
import { CliCommandViewerConfigAddressSetPathSchema } from "./path";

export const CliCommandViewerConfigAddressSetViewerResponseSchema = z.object({
  id: z.string(),
  path_type: CliCommandViewerConfigAddressSetPathSchema,
  value: CliCommandOkSchema,
}).describe("Viewer-stream mirror of [`Response`]: the response (nested under\n`value`) plus the broadcast stream `id` and the originating request's\n`path_type`.").meta({ title: "cli.command.viewer.config.address.set.ViewerResponse" });
export type CliCommandViewerConfigAddressSetViewerResponse = z.infer<typeof CliCommandViewerConfigAddressSetViewerResponseSchema>;
