// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandConfigApiMcpAuthorizationGetPathSchema } from "./path";

export const CliCommandConfigApiMcpAuthorizationGetRequestSchema = z.object({
  filter: z.string().nullable().optional(),
  jq: z.string().nullable().optional(),
  path_type: CliCommandConfigApiMcpAuthorizationGetPathSchema,
}).meta({ title: "cli.command.config.api.mcp_authorization.get.Request" });
export type CliCommandConfigApiMcpAuthorizationGetRequest = z.infer<typeof CliCommandConfigApiMcpAuthorizationGetRequestSchema>;
