// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLaboratoriesCreateViewerRequestSchema } from "./create/viewerRequest";
import { CliCommandLaboratoriesListViewerRequestSchema } from "./list/viewerRequest";

export const CliCommandLaboratoriesViewerRequestSchema = z.union([CliCommandLaboratoriesCreateViewerRequestSchema.meta({"title":"cli.command.laboratories.create.ViewerRequest","variantTitle":"Create"}), CliCommandLaboratoriesListViewerRequestSchema.meta({"title":"cli.command.laboratories.list.ViewerRequest","variantTitle":"List"})]).describe("Viewer-stream mirror of [`Request`] — the real command requests only\n(schema-introspection variants are excluded; the viewer streams\nactual command traffic). Untagged: each variant carries the leaf's\n`path_type`, so it stays discriminable.").meta({ title: "cli.command.laboratories.ViewerRequest" });
export type CliCommandLaboratoriesViewerRequest = z.infer<typeof CliCommandLaboratoriesViewerRequestSchema>;
