// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandConfigAgentsFavoritesEditPathSchema = z.literal("config/agents/favorites/edit").meta({ title: "cli.command.config.agents.favorites.edit.Path" });
export type CliCommandConfigAgentsFavoritesEditPath = z.infer<typeof CliCommandConfigAgentsFavoritesEditPathSchema>;
