// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-listener-execution.cjs from objectiveai-sdk-rs/src/cli/command/.
import { type CliCommandDevelopmentPluginsMcpListRequest } from "./request";
import { type CliCommandDevelopmentPluginsMcpListResponseItem } from "./responseItem";
import { type CliError } from "../../../../../error";
import { type ResponseItemStream } from "../../../../../../daemon/commandListener";
import { type Identity } from "../../../../../../identity";

/** One `/listen` broadcast run of `development plugins mcp list`: the actual request, the producer's identity, and the response-item stream. */
export type CliCommandDevelopmentPluginsMcpListListenerExecution = {
  request: CliCommandDevelopmentPluginsMcpListRequest;
  identity: Identity;
  response: ResponseItemStream<CliError | CliCommandDevelopmentPluginsMcpListResponseItem>;
};
