[package]
name = "objectiveai-mcp-filesystem"
version = "2.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = "0.8.8"
base64 = "0.22"
dotenv = "0.15.0"
envconfig = "0.11.1"
glob = "0.3"
indexmap = { version = "2.13.0", features = ["serde"] }
pathdiff = "0.2"
regex = "1"
rmcp = { version = "0.16.0", features = ["server", "transport-streamable-http-server"] }
schemars = "1.2.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
tokio = { version = "1.50.0", features = ["full"] }
tokio-util = "0.7.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
walkdir = "2"
