// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by objectiveai-cli-builder from objectiveai-json-schema/.

pub mod alpha_scalar;
pub mod alpha_vector;
pub mod check;
pub mod executions;
pub mod expression;
pub mod inventions;
pub mod profiles;

use clap::Subcommand;

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum GetCommand {
    #[command(name = "get")]
    Get,
}

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum Commands {
    #[command(name = "list")]
    List,
    #[command(name = "alpha_scalar")]
    AlphaScalar {
        #[command(subcommand)]
        command: alpha_scalar::Commands,
    },
    #[command(name = "alpha_vector")]
    AlphaVector {
        #[command(subcommand)]
        command: alpha_vector::Commands,
    },
    #[command(name = "check")]
    Check {
        #[command(subcommand)]
        command: check::Commands,
    },
    #[command(name = "executions")]
    Executions {
        #[command(subcommand)]
        command: executions::Commands,
    },
    #[command(name = "expression")]
    Expression {
        #[command(subcommand)]
        command: expression::Commands,
    },
    #[command(name = "inventions")]
    Inventions {
        #[command(subcommand)]
        command: inventions::Commands,
    },
    #[command(name = "profiles")]
    Profiles {
        #[command(subcommand)]
        command: profiles::Commands,
    },
    AlphaInlineFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    AlphaRemoteFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    CompiledTask {
        #[command(subcommand)]
        command: GetCommand,
    },
    FullFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    FullInlineFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    FullInlineFunctionOrRemoteCommitOptional {
        #[command(subcommand)]
        command: GetCommand,
    },
    FullRemoteFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    Function {
        #[command(subcommand)]
        command: GetCommand,
    },
    FunctionType {
        #[command(subcommand)]
        command: GetCommand,
    },
    GetFunctionProfilePairResponse {
        #[command(subcommand)]
        command: GetCommand,
    },
    GetFunctionProfilePairUsageRequest {
        #[command(subcommand)]
        command: GetCommand,
    },
    GetFunctionResponse {
        #[command(subcommand)]
        command: GetCommand,
    },
    InlineFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    InlineProfile {
        #[command(subcommand)]
        command: GetCommand,
    },
    InlineProfileOrRemoteCommitOptional {
        #[command(subcommand)]
        command: GetCommand,
    },
    InlineTasksProfile {
        #[command(subcommand)]
        command: GetCommand,
    },
    ListFunctionProfilePairItem {
        #[command(subcommand)]
        command: GetCommand,
    },
    ListFunctionProfilePairResponse {
        #[command(subcommand)]
        command: GetCommand,
    },
    ListFunctionProfilePairsRequest {
        #[command(subcommand)]
        command: GetCommand,
    },
    ListFunctionProfilePairsSource {
        #[command(subcommand)]
        command: GetCommand,
    },
    ListFunctionResponse {
        #[command(subcommand)]
        command: GetCommand,
    },
    ListFunctionsRequest {
        #[command(subcommand)]
        command: GetCommand,
    },
    ListFunctionsSource {
        #[command(subcommand)]
        command: GetCommand,
    },
    PlaceholderScalarFunctionTask {
        #[command(subcommand)]
        command: GetCommand,
    },
    PlaceholderScalarFunctionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    PlaceholderVectorFunctionTask {
        #[command(subcommand)]
        command: GetCommand,
    },
    PlaceholderVectorFunctionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    Profile {
        #[command(subcommand)]
        command: GetCommand,
    },
    RemoteFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    RemoteProfile {
        #[command(subcommand)]
        command: GetCommand,
    },
    RemoteTasksProfile {
        #[command(subcommand)]
        command: GetCommand,
    },
    ScalarFunctionTask {
        #[command(subcommand)]
        command: GetCommand,
    },
    ScalarFunctionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    Task {
        #[command(subcommand)]
        command: GetCommand,
    },
    TaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    TaskProfile {
        #[command(subcommand)]
        command: GetCommand,
    },
    UsageFunctionProfilePairResponse {
        #[command(subcommand)]
        command: GetCommand,
    },
    UsageFunctionResponse {
        #[command(subcommand)]
        command: GetCommand,
    },
    VectorCompletionTask {
        #[command(subcommand)]
        command: GetCommand,
    },
    VectorCompletionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    VectorFunctionTask {
        #[command(subcommand)]
        command: GetCommand,
    },
    VectorFunctionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
}

impl Commands {
    pub async fn handle(self, handle: &objectiveai_sdk::cli::output::Handle) -> Result<(), crate::error::Error> {
        match self {
            Commands::List => {
                const NAMES: &[&str] = &["alpha_scalar", "alpha_vector", "check", "executions", "expression", "inventions", "profiles", "AlphaInlineFunction", "AlphaRemoteFunction", "CompiledTask", "FullFunction", "FullInlineFunction", "FullInlineFunctionOrRemoteCommitOptional", "FullRemoteFunction", "Function", "FunctionType", "GetFunctionProfilePairResponse", "GetFunctionProfilePairUsageRequest", "GetFunctionResponse", "InlineFunction", "InlineProfile", "InlineProfileOrRemoteCommitOptional", "InlineTasksProfile", "ListFunctionProfilePairItem", "ListFunctionProfilePairResponse", "ListFunctionProfilePairsRequest", "ListFunctionProfilePairsSource", "ListFunctionResponse", "ListFunctionsRequest", "ListFunctionsSource", "PlaceholderScalarFunctionTask", "PlaceholderScalarFunctionTaskExpression", "PlaceholderVectorFunctionTask", "PlaceholderVectorFunctionTaskExpression", "Profile", "RemoteFunction", "RemoteProfile", "RemoteTasksProfile", "ScalarFunctionTask", "ScalarFunctionTaskExpression", "Task", "TaskExpression", "TaskProfile", "UsageFunctionProfilePairResponse", "UsageFunctionResponse", "VectorCompletionTask", "VectorCompletionTaskExpression", "VectorFunctionTask", "VectorFunctionTaskExpression"];
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schemas>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schemas {
                            schemas: NAMES.iter().map(|s| s.to_string()).collect(),
                        },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::AlphaScalar { command } => command.handle(handle).await,
            Commands::AlphaVector { command } => command.handle(handle).await,
            Commands::Check { command } => command.handle(handle).await,
            Commands::Executions { command } => command.handle(handle).await,
            Commands::Expression { command } => command.handle(handle).await,
            Commands::Inventions { command } => command.handle(handle).await,
            Commands::Profiles { command } => command.handle(handle).await,
            Commands::AlphaInlineFunction { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.AlphaInlineFunction.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::AlphaRemoteFunction { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.AlphaRemoteFunction.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::CompiledTask { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.CompiledTask.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::FullFunction { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.FullFunction.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::FullInlineFunction { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.FullInlineFunction.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::FullInlineFunctionOrRemoteCommitOptional { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.FullInlineFunctionOrRemoteCommitOptional.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::FullRemoteFunction { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.FullRemoteFunction.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::Function { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.Function.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::FunctionType { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.FunctionType.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::GetFunctionProfilePairResponse { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.GetFunctionProfilePairResponse.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::GetFunctionProfilePairUsageRequest { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.GetFunctionProfilePairUsageRequest.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::GetFunctionResponse { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.GetFunctionResponse.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::InlineFunction { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.InlineFunction.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::InlineProfile { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.InlineProfile.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::InlineProfileOrRemoteCommitOptional { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.InlineProfileOrRemoteCommitOptional.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::InlineTasksProfile { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.InlineTasksProfile.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ListFunctionProfilePairItem { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ListFunctionProfilePairItem.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ListFunctionProfilePairResponse { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ListFunctionProfilePairResponse.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ListFunctionProfilePairsRequest { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ListFunctionProfilePairsRequest.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ListFunctionProfilePairsSource { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ListFunctionProfilePairsSource.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ListFunctionResponse { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ListFunctionResponse.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ListFunctionsRequest { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ListFunctionsRequest.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ListFunctionsSource { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ListFunctionsSource.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::PlaceholderScalarFunctionTask { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.PlaceholderScalarFunctionTask.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::PlaceholderScalarFunctionTaskExpression { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.PlaceholderScalarFunctionTaskExpression.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::PlaceholderVectorFunctionTask { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.PlaceholderVectorFunctionTask.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::PlaceholderVectorFunctionTaskExpression { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.PlaceholderVectorFunctionTaskExpression.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::Profile { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.Profile.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::RemoteFunction { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.RemoteFunction.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::RemoteProfile { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.RemoteProfile.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::RemoteTasksProfile { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.RemoteTasksProfile.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ScalarFunctionTask { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ScalarFunctionTask.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::ScalarFunctionTaskExpression { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.ScalarFunctionTaskExpression.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::Task { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.Task.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::TaskExpression { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.TaskExpression.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::TaskProfile { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.TaskProfile.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::UsageFunctionProfilePairResponse { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.UsageFunctionProfilePairResponse.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::UsageFunctionResponse { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.UsageFunctionResponse.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::VectorCompletionTask { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.VectorCompletionTask.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::VectorCompletionTaskExpression { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.VectorCompletionTaskExpression.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::VectorFunctionTask { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.VectorFunctionTask.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::VectorFunctionTaskExpression { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../objectiveai-json-schema/functions.VectorFunctionTaskExpression.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        agent_id: None,
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
        }
    }
}
