// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandDbConfigGetResponseSchema = z.object({
  address: z.string().nullable().meta({ omitempty: true }).optional(),
  database: z.string().nullable().meta({ omitempty: true }).optional(),
  password: z.string().nullable().meta({ omitempty: true }).optional(),
  user: z.string().nullable().meta({ omitempty: true }).optional(),
}).meta({ title: "cli.command.db.config.get.Response" });
export type CliCommandDbConfigGetResponse = z.infer<typeof CliCommandDbConfigGetResponseSchema>;
