# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_request_list():
    from objectiveai_sdk.cli.command.agents.mcp.resources import RequestList
    schema = RequestList.model_json_schema()
