# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal
from pydantic import ConfigDict, RootModel


class Path(RootModel):
    model_config = ConfigDict(title='cli.command.config.mcp.address.get.response_schema.Path')

    root: Literal['config/mcp/address/get/response_schema']

