# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.logs.agents.completions.request.messages.file.get.request import Request as CliCommandLogsAgentsCompletionsRequestMessagesFileGetRequest
from objectiveai_sdk.cli.command.logs.agents.completions.request.messages.file.get.request_schema.request import Request as CliCommandLogsAgentsCompletionsRequestMessagesFileGetRequestSchemaRequest
from objectiveai_sdk.cli.command.logs.agents.completions.request.messages.file.get.response_schema.request import Request as CliCommandLogsAgentsCompletionsRequestMessagesFileGetResponseSchemaRequest


class RequestGet(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Get'})

    root: CliCommandLogsAgentsCompletionsRequestMessagesFileGetRequest


class RequestGetRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetRequestSchema'})

    root: CliCommandLogsAgentsCompletionsRequestMessagesFileGetRequestSchemaRequest


class RequestGetResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetResponseSchema'})

    root: CliCommandLogsAgentsCompletionsRequestMessagesFileGetResponseSchemaRequest


class Request(RootModel):
    model_config = ConfigDict(title='cli.command.logs.agents.completions.request.messages.file.Request')

    root: Union[RequestGet, RequestGetRequestSchema, RequestGetResponseSchema]

