# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.logs.agents.completions.response.messages.tool.video.get.request import Request as CliCommandLogsAgentsCompletionsResponseMessagesToolVideoGetRequest
from objectiveai_sdk.cli.command.logs.agents.completions.response.messages.tool.video.get.request_schema.request import Request as CliCommandLogsAgentsCompletionsResponseMessagesToolVideoGetRequestSchemaRequest
from objectiveai_sdk.cli.command.logs.agents.completions.response.messages.tool.video.get.response_schema.request import Request as CliCommandLogsAgentsCompletionsResponseMessagesToolVideoGetResponseSchemaRequest


class RequestGet(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Get'})

    root: CliCommandLogsAgentsCompletionsResponseMessagesToolVideoGetRequest


class RequestGetRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetRequestSchema'})

    root: CliCommandLogsAgentsCompletionsResponseMessagesToolVideoGetRequestSchemaRequest


class RequestGetResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetResponseSchema'})

    root: CliCommandLogsAgentsCompletionsResponseMessagesToolVideoGetResponseSchemaRequest


class Request(RootModel):
    model_config = ConfigDict(title='cli.command.logs.agents.completions.response.messages.tool.video.Request')

    root: Union[RequestGet, RequestGetRequestSchema, RequestGetResponseSchema]

