# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_message_user():
    from objectiveai_sdk.agent.gemini import MessageUser
    schema = MessageUser.model_json_schema()
