// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-listener-execution.cjs from objectiveai-sdk-rs/src/cli/command/.
import { type CliCommandApiConfigUserAgentGetRequest } from "./request";
import { type CliCommandApiConfigUserAgentGetResponse } from "./response";
import { type CliError } from "../../../../../error";
import { type Identity } from "../../../../../../identity";

/** One `/listen` broadcast run of `api config user_agent get`: the actual request, the producer's identity, and the unary response future. */
export type CliCommandApiConfigUserAgentGetListenerExecution = {
  request: CliCommandApiConfigUserAgentGetRequest;
  identity: Identity;
  response: Promise<CliError | CliCommandApiConfigUserAgentGetResponse>;
};
