# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_request_get_request_schema():
    from objectiveai_sdk.cli.command.config.functions.favorites import RequestGetRequestSchema
    schema = RequestGetRequestSchema.model_json_schema()
