// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { CliStream } from "../../../../../cliStream";
import { type CliCommandDbConfigAddressGetRequestSchemaRequest } from "./request";
import { type CommandExecutor } from "../../../../../executor";
import { CliErrorSchema, type CliError } from "../../../../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../../../../jsonValue";

/** `db config address get request_schema execute` — unary; first stream item, rest discarded. */
export async function dbConfigAddressGetRequestSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandDbConfigAddressGetRequestSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "db/config/address/get/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db config address get request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `db config address get request_schema execute_transform` — unary; first stream item, rest discarded. */
export async function dbConfigAddressGetRequestSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandDbConfigAddressGetRequestSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "db/config/address/get/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db config address get request_schema: cli produced no output before the end marker");
  }
  return first;
}
