# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class AgentRecord(BaseModel):
    """One agent's record on the `/agents/instances/list` endpoint: identity, spawn /
last-active timestamps, and whether its per-instance lock is currently
held. Mirrors `agents instances list`'s `ResponseItem` plus the live
`active` flag."""
    model_config = ConfigDict(title='cli.websocket_agents_listener.AgentRecord')

    active: bool = Field(..., description="Whether the agent's per-instance lock is currently held — i.e. a\nlive process owns this agent right now.")
    agent_instance_hierarchy: str = Field(..., description='Full hierarchy of this agent instance.')
    last_active_at: Optional[str] = Field(None, description='RFC3339 timestamp the agent was last active. Meaningful only when\n`active` is `false` — a live agent\'s last-active is implicitly\n"now", so it is left `None` while active and stamped at the moment\nthe lock releases.', json_schema_extra={'omitempty': True})
    logged: int = Field(..., description='Total `objectiveai.messages` rows for this agent over all time.', ge=0, le=18446744073709551615)
    queued: int = Field(..., description='Active `message_queue` rows targeting this agent.', ge=0, le=18446744073709551615)
    spawned_at: Optional[str] = Field(None, description='RFC3339 timestamp of the first `objectiveai.messages` row for this\nagent (spawn time). `None` for an agent with no logs yet.', json_schema_extra={'omitempty': True})
    tags: list[str] = Field(..., description='Tag names currently bound to this AIH, newest-bound first.')

