// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-command-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { CliStream } from "../../cliStream";
import { type CliCommandDbQueryRequest } from "./request";
import { CliCommandDbQueryResponseSchema, type CliCommandDbQueryResponse } from "./response";
import { type CommandExecutor } from "../../executor";
import { CliErrorSchema, type CliError } from "../../../error";
import { JsonValueSchema, type JsonValue } from "../../../../jsonValue";

/** `db query execute` — unary; first stream item, rest discarded. */
export async function dbQueryExecute(executor: CommandExecutor, request: Omit<CliCommandDbQueryRequest, "path_type">): Promise<CliError | CliCommandDbQueryResponse> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "db/query" }), z.union([CliErrorSchema, CliCommandDbQueryResponseSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db query: cli produced no output before the end marker");
  }
  return first;
}

/** `db query execute_transform` — unary; first stream item, rest discarded. */
export async function dbQueryExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandDbQueryRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "db/query" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("db query: cli produced no output before the end marker");
  }
  return first;
}
