// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-viewer-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { type CliCommandMcpConfigPortGetRequest } from "../../../../../cli/command/mcp/config/port/get/request";
import { type CliCommandMcpConfigPortGetRequestSchemaRequest } from "../../../../../cli/command/mcp/config/port/get/request_schema/request";
import { CliCommandMcpConfigPortGetResponseSchema, type CliCommandMcpConfigPortGetResponse } from "../../../../../cli/command/mcp/config/port/get/response";
import { type CliCommandMcpConfigPortGetResponseSchemaRequest } from "../../../../../cli/command/mcp/config/port/get/response_schema/request";
import { CliErrorSchema, type CliError } from "../../../../../cli/error";
import { JsonValueSchema, type JsonValue } from "../../../../../jsonValue";
import { CliStream } from "../../../../cliStream";
import { invokeCliRequest } from "../../../../invoke";

/** `mcp config port get execute` — unary; first stream item, rest discarded. */
export async function mcpConfigPortGetExecute(request: Omit<CliCommandMcpConfigPortGetRequest, "path_type">): Promise<CliError | CliCommandMcpConfigPortGetResponse> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq: undefined, python: undefined, path_type: "mcp/config/port/get" }), z.union([CliErrorSchema, CliCommandMcpConfigPortGetResponseSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port get: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port get execute_transform` — unary; first stream item, rest discarded. */
export async function mcpConfigPortGetExecuteTransform(request: Omit<CliCommandMcpConfigPortGetRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq: undefined, python: undefined, ...transform, path_type: "mcp/config/port/get" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port get: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port get request_schema execute` — unary; first stream item, rest discarded. */
export async function mcpConfigPortGetRequestSchemaExecute(request: Omit<CliCommandMcpConfigPortGetRequestSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq: undefined, python: undefined, path_type: "mcp/config/port/get/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port get request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port get request_schema execute_transform` — unary; first stream item, rest discarded. */
export async function mcpConfigPortGetRequestSchemaExecuteTransform(request: Omit<CliCommandMcpConfigPortGetRequestSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq: undefined, python: undefined, ...transform, path_type: "mcp/config/port/get/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port get request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port get response_schema execute` — unary; first stream item, rest discarded. */
export async function mcpConfigPortGetResponseSchemaExecute(request: Omit<CliCommandMcpConfigPortGetResponseSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq: undefined, python: undefined, path_type: "mcp/config/port/get/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port get response_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port get response_schema execute_transform` — unary; first stream item, rest discarded. */
export async function mcpConfigPortGetResponseSchemaExecuteTransform(request: Omit<CliCommandMcpConfigPortGetResponseSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(invokeCliRequest({ ...request, jq: undefined, python: undefined, ...transform, path_type: "mcp/config/port/get/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port get response_schema: cli produced no output before the end marker");
  }
  return first;
}
