// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-viewer-execute.cjs from objectiveai-sdk-rs/src/cli/command/.
import { z } from "zod";
import { type CommandExecutor } from "../../../../../cli/command/executor";
import { type CliCommandMcpConfigPortSetRequest } from "../../../../../cli/command/mcp/config/port/set/request";
import { type CliCommandMcpConfigPortSetRequestSchemaRequest } from "../../../../../cli/command/mcp/config/port/set/request_schema/request";
import { type CliCommandMcpConfigPortSetResponseSchemaRequest } from "../../../../../cli/command/mcp/config/port/set/response_schema/request";
import { CliCommandOkSchema, type CliCommandOk } from "../../../../../cli/command/ok";
import { CliErrorSchema, type CliError } from "../../../../../cli/error";
import { JsonValueSchema, type JsonValue } from "../../../../../jsonValue";
import { CliStream } from "../../../../cliStream";

/** `mcp config port set execute` — unary; first stream item, rest discarded. */
export async function mcpConfigPortSetExecute(executor: CommandExecutor, request: Omit<CliCommandMcpConfigPortSetRequest, "path_type">): Promise<CliError | CliCommandOk> {
  const stream = new CliStream(executor.execute({ ...request, path_type: "mcp/config/port/set" }), z.union([CliErrorSchema, CliCommandOkSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port set: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port set execute_transform` — unary; first stream item, rest discarded. */
export async function mcpConfigPortSetExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandMcpConfigPortSetRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, path_type: "mcp/config/port/set" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port set: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port set request_schema execute` — unary; first stream item, rest discarded. */
export async function mcpConfigPortSetRequestSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandMcpConfigPortSetRequestSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "mcp/config/port/set/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port set request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port set request_schema execute_transform` — unary; first stream item, rest discarded. */
export async function mcpConfigPortSetRequestSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandMcpConfigPortSetRequestSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "mcp/config/port/set/request_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port set request_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port set response_schema execute` — unary; first stream item, rest discarded. */
export async function mcpConfigPortSetResponseSchemaExecute(executor: CommandExecutor, request: Omit<CliCommandMcpConfigPortSetResponseSchemaRequest, "path_type">): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, path_type: "mcp/config/port/set/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port set response_schema: cli produced no output before the end marker");
  }
  return first;
}

/** `mcp config port set response_schema execute_transform` — unary; first stream item, rest discarded. */
export async function mcpConfigPortSetResponseSchemaExecuteTransform(executor: CommandExecutor, request: Omit<CliCommandMcpConfigPortSetResponseSchemaRequest, "path_type">, transform: { jq: string } | { python: string }): Promise<CliError | JsonValue> {
  const stream = new CliStream(executor.execute({ ...request, jq: undefined, python: undefined, ...transform, path_type: "mcp/config/port/set/response_schema" }), z.union([CliErrorSchema, JsonValueSchema]));
  const first = await stream.first();
  if (first === undefined) {
    throw new Error("mcp config port set response_schema: cli produced no output before the end marker");
  }
  return first;
}
