# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.agents.message_queue.add.request import Request as CliCommandAgentsMessageQueueAddRequest
from objectiveai_sdk.cli.command.agents.message_queue.add.request_schema.request import Request as CliCommandAgentsMessageQueueAddRequestSchemaRequest
from objectiveai_sdk.cli.command.agents.message_queue.add.response_schema.request import Request as CliCommandAgentsMessageQueueAddResponseSchemaRequest
from objectiveai_sdk.cli.command.agents.message_queue.delete.request import Request as CliCommandAgentsMessageQueueDeleteRequest
from objectiveai_sdk.cli.command.agents.message_queue.delete.request_schema.request import Request as CliCommandAgentsMessageQueueDeleteRequestSchemaRequest
from objectiveai_sdk.cli.command.agents.message_queue.delete.response_schema.request import Request as CliCommandAgentsMessageQueueDeleteResponseSchemaRequest
from objectiveai_sdk.cli.command.agents.message_queue.deliver.request import Request as CliCommandAgentsMessageQueueDeliverRequest
from objectiveai_sdk.cli.command.agents.message_queue.deliver.request_schema.request import Request as CliCommandAgentsMessageQueueDeliverRequestSchemaRequest
from objectiveai_sdk.cli.command.agents.message_queue.deliver.response_schema.request import Request as CliCommandAgentsMessageQueueDeliverResponseSchemaRequest
from objectiveai_sdk.cli.command.agents.message_queue.read.request import Request as CliCommandAgentsMessageQueueReadRequest


class RequestAdd(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Add'})

    root: CliCommandAgentsMessageQueueAddRequest


class RequestAddRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'AddRequestSchema'})

    root: CliCommandAgentsMessageQueueAddRequestSchemaRequest


class RequestAddResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'AddResponseSchema'})

    root: CliCommandAgentsMessageQueueAddResponseSchemaRequest


class RequestDelete(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Delete'})

    root: CliCommandAgentsMessageQueueDeleteRequest


class RequestDeleteRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'DeleteRequestSchema'})

    root: CliCommandAgentsMessageQueueDeleteRequestSchemaRequest


class RequestDeleteResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'DeleteResponseSchema'})

    root: CliCommandAgentsMessageQueueDeleteResponseSchemaRequest


class RequestDeliver(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Deliver'})

    root: CliCommandAgentsMessageQueueDeliverRequest


class RequestDeliverRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'DeliverRequestSchema'})

    root: CliCommandAgentsMessageQueueDeliverRequestSchemaRequest


class RequestDeliverResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'DeliverResponseSchema'})

    root: CliCommandAgentsMessageQueueDeliverResponseSchemaRequest


class RequestRead(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Read'})

    root: CliCommandAgentsMessageQueueReadRequest


class Request(RootModel):
    model_config = ConfigDict(title='cli.command.agents.message_queue.Request')

    root: Union[RequestAdd, RequestAddRequestSchema, RequestAddResponseSchema, RequestDelete, RequestDeleteRequestSchema, RequestDeleteResponseSchema, RequestDeliver, RequestDeliverRequestSchema, RequestDeliverResponseSchema, RequestRead]

