// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by objectiveai-cli-builder from objectiveai-json-schema/.

use clap::Subcommand;

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum GetCommand {
    #[command(name = "get")]
    Get,
}

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum Commands {
    #[command(name = "list")]
    List,
    VectorFunctionInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    VectorFunctionInputValue {
        #[command(subcommand)]
        command: GetCommand,
    },
    VectorFunctionInputValueExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
}

impl Commands {
    pub async fn handle(self, handle: &objectiveai_sdk::cli::output::Handle) -> Result<(), crate::error::Error> {
        match self {
            Commands::List => {
                const NAMES: &[&str] = &["VectorFunctionInputSchema", "VectorFunctionInputValue", "VectorFunctionInputValueExpression"];
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schemas>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        value: objectiveai_sdk::cli::output::Schemas {
                            schemas: NAMES.iter().map(|s| s.to_string()).collect(),
                        },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::VectorFunctionInputSchema { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../../../objectiveai-json-schema/functions.alpha_vector.expression.VectorFunctionInputSchema.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::VectorFunctionInputValue { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../../../objectiveai-json-schema/functions.alpha_vector.expression.VectorFunctionInputValue.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::VectorFunctionInputValueExpression { .. } => {
                let schema: serde_json::Value = serde_json::from_str(
                    include_str!("../../../../../../objectiveai-json-schema/functions.alpha_vector.expression.VectorFunctionInputValueExpression.json"),
                ).expect("embedded JSON Schema must parse");
                objectiveai_sdk::cli::output::Output::<objectiveai_sdk::cli::output::Schema>::Notification(
                    objectiveai_sdk::cli::output::Notification {
                        value: objectiveai_sdk::cli::output::Schema { schema },
                    },
                ).emit(handle).await;
                Ok(())
            }
        }
    }
}
