// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandToolsInstallGithubPathSchema } from "./path";
import { CliCommandToolsInstallGithubResponseSchema } from "./response";

export const CliCommandToolsInstallGithubViewerResponseSchema = z.object({
  id: z.string(),
  path_type: CliCommandToolsInstallGithubPathSchema,
  value: CliCommandToolsInstallGithubResponseSchema,
}).meta({ title: "cli.command.tools.install.github.ViewerResponse" });
export type CliCommandToolsInstallGithubViewerResponse = z.infer<typeof CliCommandToolsInstallGithubViewerResponseSchema>;
