// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandMcpConfigAddressGetRequestSchema } from "./request";

export const CliCommandMcpConfigAddressGetViewerRequestSchema = z.object({
  agent_full_id: z.string().nullable().meta({ omitempty: true }).optional(),
  agent_id: z.string().nullable().meta({ omitempty: true }).optional(),
  agent_instance_hierarchy: z.string().nullable().meta({ omitempty: true }).optional(),
  agent_remote: z.string().nullable().meta({ omitempty: true }).optional(),
  id: z.string(),
  plugin_owner: z.string().nullable().meta({ omitempty: true }).optional(),
  plugin_repository: z.string().nullable().meta({ omitempty: true }).optional(),
  plugin_version: z.string().nullable().meta({ omitempty: true }).optional(),
  response_id: z.string().nullable().meta({ omitempty: true }).optional(),
  response_ids: z.string().nullable().meta({ omitempty: true }).optional(),
  value: CliCommandMcpConfigAddressGetRequestSchema,
}).describe("Viewer-stream mirror of [`Request`]: the request (nested under\n`value`, `path_type` and all) plus the broadcast stream `id`.").meta({ title: "cli.command.mcp.config.address.get.ViewerRequest" });
export type CliCommandMcpConfigAddressGetViewerRequest = z.infer<typeof CliCommandMcpConfigAddressGetViewerRequestSchema>;
