// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandMcpConfigAddressGetPathSchema } from "./path";
import { CliCommandMcpConfigAddressGetResponseSchema } from "./response";

export const CliCommandMcpConfigAddressGetViewerResponseSchema = z.object({
  id: z.string(),
  path_type: CliCommandMcpConfigAddressGetPathSchema,
  value: CliCommandMcpConfigAddressGetResponseSchema,
}).describe("Viewer-stream mirror of [`Response`]: the response (nested under\n`value`) plus the broadcast stream `id` and the originating request's\n`path_type`.").meta({ title: "cli.command.mcp.config.address.get.ViewerResponse" });
export type CliCommandMcpConfigAddressGetViewerResponse = z.infer<typeof CliCommandMcpConfigAddressGetViewerResponseSchema>;
