// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandDbConfigRequestSchema } from "./config/request";
import { CliCommandDbKillRequestSchema } from "./kill/request";
import { CliCommandDbKillRequestSchemaRequestSchema } from "./kill/request_schema/request";
import { CliCommandDbKillResponseSchemaRequestSchema } from "./kill/response_schema/request";
import { CliCommandDbQueryRequestSchema } from "./query/request";
import { CliCommandDbQueryRequestSchemaRequestSchema } from "./query/request_schema/request";
import { CliCommandDbQueryResponseSchemaRequestSchema } from "./query/response_schema/request";
import { CliCommandDbSpawnRequestSchema } from "./spawn/request";
import { CliCommandDbSpawnRequestSchemaRequestSchema } from "./spawn/request_schema/request";
import { CliCommandDbSpawnResponseSchemaRequestSchema } from "./spawn/response_schema/request";

export const CliCommandDbRequestSchema = z.union([CliCommandDbConfigRequestSchema.meta({"title":"cli.command.db.config.Request","variantTitle":"Config"}), CliCommandDbKillRequestSchema.meta({"title":"cli.command.db.kill.Request","variantTitle":"Kill"}), CliCommandDbKillRequestSchemaRequestSchema.meta({"title":"cli.command.db.kill.request_schema.Request","variantTitle":"KillRequestSchema"}), CliCommandDbKillResponseSchemaRequestSchema.meta({"title":"cli.command.db.kill.response_schema.Request","variantTitle":"KillResponseSchema"}), CliCommandDbQueryRequestSchema.meta({"title":"cli.command.db.query.Request","variantTitle":"Query"}), CliCommandDbQueryRequestSchemaRequestSchema.meta({"title":"cli.command.db.query.request_schema.Request","variantTitle":"QueryRequestSchema"}), CliCommandDbQueryResponseSchemaRequestSchema.meta({"title":"cli.command.db.query.response_schema.Request","variantTitle":"QueryResponseSchema"}), CliCommandDbSpawnRequestSchema.meta({"title":"cli.command.db.spawn.Request","variantTitle":"Spawn"}), CliCommandDbSpawnRequestSchemaRequestSchema.meta({"title":"cli.command.db.spawn.request_schema.Request","variantTitle":"SpawnRequestSchema"}), CliCommandDbSpawnResponseSchemaRequestSchema.meta({"title":"cli.command.db.spawn.response_schema.Request","variantTitle":"SpawnResponseSchema"})]).meta({ title: "cli.command.db.Request" });
export type CliCommandDbRequest = z.infer<typeof CliCommandDbRequestSchema>;
