// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsAgentsCompletionsRequestNotificationsVideoGetPathSchema = z.literal("logs/agents/completions/request/notifications/video/get").meta({ title: "cli.command.logs.agents.completions.request.notifications.video.get.Path" });
export type CliCommandLogsAgentsCompletionsRequestNotificationsVideoGetPath = z.infer<typeof CliCommandLogsAgentsCompletionsRequestNotificationsVideoGetPathSchema>;
