# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal, Union
from pydantic import ConfigDict, RootModel


class RemoteGithub(RootModel):
    """GitHub repository."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Github'})

    root: Literal['github']


class RemoteClient(RootModel):
    """The connected client (resolved over the websocket reverse-channel)."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Client'})

    root: Literal['client']


class RemoteMock(RootModel):
    """Mock (for testing)."""
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Mock'})

    root: Literal['mock']


class Remote(RootModel):
    """The remote source where a function, profile, or agent is hosted."""
    model_config = ConfigDict(title='Remote')

    root: Union[RemoteGithub, RemoteClient, RemoteMock]

