// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandApiConfigCommitAuthorNameGetRequestSchemaPathSchema } from "./path";

export const CliCommandApiConfigCommitAuthorNameGetRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandApiConfigCommitAuthorNameGetRequestSchemaPathSchema,
}).meta({ title: "cli.command.api.config.commit_author_name.get.request_schema.Request" });
export type CliCommandApiConfigCommitAuthorNameGetRequestSchemaRequest = z.infer<typeof CliCommandApiConfigCommitAuthorNameGetRequestSchemaRequestSchema>;
