# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class Plugin(BaseModel):
    """The plugin that registered a schedule. All three fields are present
together or the whole object is absent (the `schedules` table
enforces all-or-nothing on its `plugin_*` columns)."""
    model_config = ConfigDict(title='cli.command.tasks.list.Plugin')

    owner: str
    repository: str
    version: str

