// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandApiConfigObjectiveaiAuthorizationGetPathSchema } from "./path";
import { CliCommandApiConfigObjectiveaiAuthorizationGetResponseSchema } from "./response";

export const CliCommandApiConfigObjectiveaiAuthorizationGetViewerResponseSchema = z.object({
  id: z.string(),
  path_type: CliCommandApiConfigObjectiveaiAuthorizationGetPathSchema,
  value: CliCommandApiConfigObjectiveaiAuthorizationGetResponseSchema,
}).describe("Viewer-stream mirror of [`Response`]: the response (nested under\n`value`) plus the broadcast stream `id` and the originating request's\n`path_type`.").meta({ title: "cli.command.api.config.objectiveai_authorization.get.ViewerResponse" });
export type CliCommandApiConfigObjectiveaiAuthorizationGetViewerResponse = z.infer<typeof CliCommandApiConfigObjectiveaiAuthorizationGetViewerResponseSchema>;
