// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsResponseMessagesRefusalSubscribePathSchema } from "./path";

export const CliCommandLogsAgentsCompletionsResponseMessagesRefusalSubscribeRequestSchema = z.object({
  id: z.string(),
  jq: z.string().nullable().optional(),
  message_index: z.number().int().min(0).max(18446744073709552000),
  path_type: CliCommandLogsAgentsCompletionsResponseMessagesRefusalSubscribePathSchema,
  require_modification: z.boolean(),
  timeout_ms: z.number().int().min(0).max(18446744073709552000),
}).meta({ title: "cli.command.logs.agents.completions.response.messages.refusal.subscribe.Request" });
export type CliCommandLogsAgentsCompletionsResponseMessagesRefusalSubscribeRequest = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesRefusalSubscribeRequestSchema>;
