# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_request_open_request_schema():
    from objectiveai_sdk.cli.command.channels.logs import RequestOpenRequestSchema
    schema = RequestOpenRequestSchema.model_json_schema()
