// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-listener-execution.cjs from objectiveai-sdk-rs/src/cli/command/.
import { type CliCommandApiConfigOpenrouterAuthorizationGetRequestSchemaRequest } from "./request";
import { type CliError } from "../../../../../../error";
import { type Identity } from "../../../../../../../identity";
import { type JsonValue } from "../../../../../../../jsonValue";

/** One `/listen` broadcast run of `api config openrouter_authorization get request_schema`: the actual request, the producer's identity, and the unary response future. */
export type CliCommandApiConfigOpenrouterAuthorizationGetRequestSchemaListenerExecution = {
  request: CliCommandApiConfigOpenrouterAuthorizationGetRequestSchemaRequest;
  identity: Identity;
  response: Promise<CliError | JsonValue>;
};
