// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandPythonPathSchema = z.literal("python").meta({ title: "cli.command.python.Path" });
export type CliCommandPythonPath = z.infer<typeof CliCommandPythonPathSchema>;
