// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const SwarmUsageSwarmResponseSchema = z.object({
  completion_tokens: z.number().int().min(0).max(18446744073709552000).describe("Total completion tokens generated across all agents."),
  prompt_tokens: z.number().int().min(0).max(18446744073709552000).describe("Total prompt tokens processed across all agents."),
  requests: z.number().int().min(0).max(18446744073709552000).describe("Total number of requests made with this Swarm."),
  total_cost: z.number().min(-3.4028234663852886e+38).max(3.4028234663852886e+38).describe("Total cost incurred."),
}).describe("Usage statistics for a Swarm.").meta({ title: "swarm.UsageSwarmResponse" });
export type SwarmUsageSwarmResponse = z.infer<typeof SwarmUsageSwarmResponseSchema>;
