# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_viewer_request_attach():
    from objectiveai_sdk.cli.command.agents.laboratories import ViewerRequestAttach
    schema = ViewerRequestAttach.model_json_schema()
