// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandConfigApiMcpAuthorizationDelResponseSchemaPathSchema } from "./path";

export const CliCommandConfigApiMcpAuthorizationDelResponseSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandConfigApiMcpAuthorizationDelResponseSchemaPathSchema,
}).meta({ title: "cli.command.config.api.mcp_authorization.del.response_schema.Request" });
export type CliCommandConfigApiMcpAuthorizationDelResponseSchemaRequest = z.infer<typeof CliCommandConfigApiMcpAuthorizationDelResponseSchemaRequestSchema>;
