// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandAgentsAgentRefSchema } from "./agentRef";

export const CliCommandAgentsAgentSelectorSchema = z.union([z.object({
  agent: CliCommandAgentsAgentRefSchema,
  by: z.literal("ref"),
}).meta({"variantTitle":"Ref"}), z.object({
  agent_tag: z.string(),
  by: z.literal("tag"),
}).meta({"variantTitle":"Tag"}), z.object({
  agent_instance: z.string().describe("Leaf id of the target agent instance."),
  by: z.literal("instance"),
  parent_agent_instance_hierarchy: z.string().nullable().describe("Lineage prefix to prepend to `agent_instance`. When\n`None`, the CLI substitutes its own\n`Config.agent_instance_hierarchy`.").meta({ omitempty: true }).optional(),
}).meta({"variantTitle":"Instance"})]).meta({ title: "cli.command.agents.AgentSelector" });
export type CliCommandAgentsAgentSelector = z.infer<typeof CliCommandAgentsAgentSelectorSchema>;
