// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandConfigViewerAddressSetPathSchema } from "./path";

export const CliCommandConfigViewerAddressSetRequestSchema = z.object({
  path_type: CliCommandConfigViewerAddressSetPathSchema,
  value: z.string(),
}).meta({ title: "cli.command.config.viewer.address.set.Request" });
export type CliCommandConfigViewerAddressSetRequest = z.infer<typeof CliCommandConfigViewerAddressSetRequestSchema>;
