# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_get_prompt_response():
    from objectiveai_sdk.functions.inventions.prompts import GetPromptResponse
    schema = GetPromptResponse.model_json_schema()
