# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.config.swarms.favorites.add.request import Request as CliCommandConfigSwarmsFavoritesAddRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.add.request_schema.request import Request as CliCommandConfigSwarmsFavoritesAddRequestSchemaRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.add.response_schema.request import Request as CliCommandConfigSwarmsFavoritesAddResponseSchemaRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.del_.request import Request as CliCommandConfigSwarmsFavoritesDelRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.del_.request_schema.request import Request as CliCommandConfigSwarmsFavoritesDelRequestSchemaRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.del_.response_schema.request import Request as CliCommandConfigSwarmsFavoritesDelResponseSchemaRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.edit.request import Request as CliCommandConfigSwarmsFavoritesEditRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.edit.request_schema.request import Request as CliCommandConfigSwarmsFavoritesEditRequestSchemaRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.edit.response_schema.request import Request as CliCommandConfigSwarmsFavoritesEditResponseSchemaRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.get.request import Request as CliCommandConfigSwarmsFavoritesGetRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.get.request_schema.request import Request as CliCommandConfigSwarmsFavoritesGetRequestSchemaRequest
from objectiveai_sdk.cli.command.config.swarms.favorites.get.response_schema.request import Request as CliCommandConfigSwarmsFavoritesGetResponseSchemaRequest


class RequestAdd(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Add'})

    root: CliCommandConfigSwarmsFavoritesAddRequest


class RequestAddRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'AddRequestSchema'})

    root: CliCommandConfigSwarmsFavoritesAddRequestSchemaRequest


class RequestAddResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'AddResponseSchema'})

    root: CliCommandConfigSwarmsFavoritesAddResponseSchemaRequest


class RequestDel(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Del'})

    root: CliCommandConfigSwarmsFavoritesDelRequest


class RequestDelRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'DelRequestSchema'})

    root: CliCommandConfigSwarmsFavoritesDelRequestSchemaRequest


class RequestDelResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'DelResponseSchema'})

    root: CliCommandConfigSwarmsFavoritesDelResponseSchemaRequest


class RequestEdit(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Edit'})

    root: CliCommandConfigSwarmsFavoritesEditRequest


class RequestEditRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'EditRequestSchema'})

    root: CliCommandConfigSwarmsFavoritesEditRequestSchemaRequest


class RequestEditResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'EditResponseSchema'})

    root: CliCommandConfigSwarmsFavoritesEditResponseSchemaRequest


class RequestGet(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Get'})

    root: CliCommandConfigSwarmsFavoritesGetRequest


class RequestGetRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetRequestSchema'})

    root: CliCommandConfigSwarmsFavoritesGetRequestSchemaRequest


class RequestGetResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetResponseSchema'})

    root: CliCommandConfigSwarmsFavoritesGetResponseSchemaRequest


class Request(RootModel):
    model_config = ConfigDict(title='cli.command.config.swarms.favorites.Request')

    root: Union[RequestAdd, RequestAddRequestSchema, RequestAddResponseSchema, RequestDel, RequestDelRequestSchema, RequestDelResponseSchema, RequestEdit, RequestEditRequestSchema, RequestEditResponseSchema, RequestGet, RequestGetRequestSchema, RequestGetResponseSchema]

