// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { JsonValueSchema } from "../../../../../jsonValue";
import { FilesystemLogsLogReferenceTagSchema } from "../../../../../filesystem/logs/logReferenceTag";

export const FunctionsExecutionsResponseStreamingReasoningSummaryLogReferenceLogReferenceSchema = z.object({
  error: JsonValueSchema.meta({ omitempty: true }),
  path: z.string().meta({ omitempty: true }),
  type: FilesystemLogsLogReferenceTagSchema,
}).meta({ title: "functions.executions.response.streaming.reasoning_summary_log_reference.LogReference" });
export type FunctionsExecutionsResponseStreamingReasoningSummaryLogReferenceLogReference = z.infer<typeof FunctionsExecutionsResponseStreamingReasoningSummaryLogReferenceLogReferenceSchema>;
