// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandAgentsLogsTokenUsageSubscribePathSchema = z.literal("agents/logs/token-usage/subscribe").meta({ title: "cli.command.agents.logs.token_usage.subscribe.Path" });
export type CliCommandAgentsLogsTokenUsageSubscribePath = z.infer<typeof CliCommandAgentsLogsTokenUsageSubscribePathSchema>;
