# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_image_input_schema_type():
    from objectiveai_sdk.functions.expression import ImageInputSchemaType
    schema = ImageInputSchemaType.model_json_schema()
