// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliWebsocketAgentsInstancesListenerVectorRequestChoicePartSchema } from "./vectorRequestChoicePart";

export const CliWebsocketAgentsInstancesListenerVectorRequestChoiceSchema = z.object({
  key: z.string().describe("The prefix-tree voting key this agent assigned to the choice."),
  parts: z.array(CliWebsocketAgentsInstancesListenerVectorRequestChoicePartSchema),
}).describe("Mirror of `logs.list.VectorRequestChoice`: this agent's inline\nvoting `key` for the choice plus the choice's content parts in\nrequest order.").meta({ title: "cli.websocket_agents_instances_listener.VectorRequestChoice" });
export type CliWebsocketAgentsInstancesListenerVectorRequestChoice = z.infer<typeof CliWebsocketAgentsInstancesListenerVectorRequestChoiceSchema>;
