# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field


class VideoUrl(BaseModel):
    """A video URL for multimodal input."""
    model_config = ConfigDict(title='agent.completions.message.VideoUrl')

    url: str = Field(..., description='The URL of the video.')

