// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandConfigApiXTitleGetPathSchema = z.literal("config/api/x_title/get").meta({ title: "cli.command.config.api.x_title.get.Path" });
export type CliCommandConfigApiXTitleGetPath = z.infer<typeof CliCommandConfigApiXTitleGetPathSchema>;
