# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_agent_instance_event_assistant_response_part():
    from objectiveai_sdk.cli.agents_instances_listener import AgentInstanceEventAssistantResponsePart
    schema = AgentInstanceEventAssistantResponsePart.model_json_schema()
