// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandConfigViewerPortGetResponseSchemaPathSchema = z.literal("config/viewer/port/get/response_schema").meta({ title: "cli.command.config.viewer.port.get.response_schema.Path" });
export type CliCommandConfigViewerPortGetResponseSchemaPath = z.infer<typeof CliCommandConfigViewerPortGetResponseSchemaPathSchema>;
