# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class RequestDangerousAdvanced(BaseModel):
    """Advanced knobs gated behind `--dangerous-advanced` because they are
easy to misuse. Modelled on `agents spawn`'s
`RequestDangerousAdvanced`."""
    model_config = ConfigDict(title='cli.command.tasks.run.RequestDangerousAdvanced')

    stream_all: Optional[bool] = Field(None, description="Stream every item every fired task emits (each a\n[`ValueResponseItem`]). When unset/false — the default — each\ntask yields exactly one [`SuccessResponseItem`] summary instead;\nthe full output still lands in `tasks_logs` either way. DANGER:\nstreaming every item of every fired task can bloat the caller's\ncontext astronomically — hence the gate.", json_schema_extra={'omitempty': True})

