# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_continuation_codex_sdk():
    from objectiveai.agent import ContinuationCodexSdk
    schema = ContinuationCodexSdk.model_json_schema()
