// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoSubscribeRequestSchemaPathSchema = z.literal("logs/agents/completions/response/messages/assistant/video/subscribe/request_schema").meta({ title: "cli.command.logs.agents.completions.response.messages.assistant.video.subscribe.request_schema.Path" });
export type CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoSubscribeRequestSchemaPath = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesAssistantVideoSubscribeRequestSchemaPathSchema>;
