# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_reasoning_effort_low():
    from objectiveai_sdk.agent.openrouter import ReasoningEffortLow
    schema = ReasoningEffortLow.model_json_schema()
