// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandFunctionsProfilesGetPathSchema } from "./path";
import { CliCommandRemotePathCommitOptionalOrFavoriteSchema } from "../../../remotePathCommitOptionalOrFavorite";

export const CliCommandFunctionsProfilesGetRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path: CliCommandRemotePathCommitOptionalOrFavoriteSchema,
  path_type: CliCommandFunctionsProfilesGetPathSchema,
}).meta({ title: "cli.command.functions.profiles.get.Request" });
export type CliCommandFunctionsProfilesGetRequest = z.infer<typeof CliCommandFunctionsProfilesGetRequestSchema>;
