# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_tool_annotations():
    from objectiveai.mcp.tool import ToolAnnotations
    schema = ToolAnnotations.model_json_schema()
