# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.laboratories.config.addresses.request import Request as CliCommandLaboratoriesConfigAddressesRequest
from objectiveai_sdk.cli.command.laboratories.config.local.request import Request as CliCommandLaboratoriesConfigLocalRequest


class RequestAddresses(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Addresses'})

    root: CliCommandLaboratoriesConfigAddressesRequest


class RequestLocal(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Local'})

    root: CliCommandLaboratoriesConfigLocalRequest


class Request(RootModel):
    model_config = ConfigDict(title='cli.command.laboratories.config.Request')

    root: Union[RequestAddresses, RequestLocal]

