// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-listener-execution.cjs from objectiveai-sdk-rs/src/cli/command/.
import { type CliCommandAgentArguments } from "../../../../agentArguments";
import { type CliCommandApiConfigCommitAuthorEmailSetRequest } from "./request";
import { type CliCommandOk } from "../../../../ok";
import { type CliError } from "../../../../../error";

/** One `/listen` broadcast run of `api config commit_author_email set`: the actual request, the producer's agent arguments, and the unary response future. */
export type CliCommandApiConfigCommitAuthorEmailSetListenerExecution = {
  request: CliCommandApiConfigCommitAuthorEmailSetRequest;
  agentArguments: CliCommandAgentArguments;
  response: Promise<CliError | CliCommandOk>;
};
