// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandAgentsMcpToolsListRequestSchema } from "./request";

export const CliCommandAgentsMcpToolsListViewerRequestSchema = z.object({
  id: z.string(),
  value: CliCommandAgentsMcpToolsListRequestSchema,
}).describe("Viewer-stream mirror of [`Request`]: the request (nested under\n`value`, `path_type` and all) plus the broadcast stream `id`.").meta({ title: "cli.command.agents.mcp.tools.list.ViewerRequest" });
export type CliCommandAgentsMcpToolsListViewerRequest = z.infer<typeof CliCommandAgentsMcpToolsListViewerRequestSchema>;
