# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_viewer_script():
    from objectiveai_sdk.cli.plugins import ViewerScript
    schema = ViewerScript.model_json_schema()
