// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsAgentsCompletionsRequestResponseSchema } from "./request/response";
import { CliCommandLogsAgentsCompletionsResponseResponseItemSchema } from "./response/responseItem";

export const CliCommandLogsAgentsCompletionsResponseItemSchema = z.union([z.object({
  Request: CliCommandLogsAgentsCompletionsRequestResponseSchema,
}).strict().meta({"variantTitle":"Request"}), z.object({
  Response: CliCommandLogsAgentsCompletionsResponseResponseItemSchema,
}).strict().meta({"variantTitle":"Response"})]).meta({ title: "cli.command.logs.agents.completions.ResponseItem" });
export type CliCommandLogsAgentsCompletionsResponseItem = z.infer<typeof CliCommandLogsAgentsCompletionsResponseItemSchema>;
