// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandConfigViewerPortSetPathSchema = z.literal("config/viewer/port/set").meta({ title: "cli.command.config.viewer.port.set.Path" });
export type CliCommandConfigViewerPortSetPath = z.infer<typeof CliCommandConfigViewerPortSetPathSchema>;
