# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import BaseModel, ConfigDict, RootModel
from objectiveai_sdk.agent.completions.response.streaming.agent_completion_chunk import AgentCompletionChunk


class ResponseItemChunk(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Chunk'})

    root: AgentCompletionChunk


class ResponseItemQueued(BaseModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Queued'})

    agent_instance_hierarchy: str
    response_id: str


class ResponseItemDelivered(BaseModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Delivered'})

    agent_instance_hierarchy: str


class ResponseItem(RootModel):
    """Streamed-mode wire shape for `agents message`. Emitted as one
JSON-line per item on the cli's stdout when
`Request::dangerous_advanced.stream = Some(true)`. Untagged shape
is forward-compatible with [`Response`]: in stream mode, item 0 is
always a `Queued` or `Delivered` variant carrying the same fields
as the unary `Response::Queued` / `Response::Delivered`. Under the
`Queued` path with streaming on, item 0 is followed by zero or
more `Chunk` items until the spawned instance-runner's stdout
EOFs."""
    model_config = ConfigDict(title='cli.command.agents.message.ResponseItem')

    root: Union[ResponseItemChunk, ResponseItemQueued, ResponseItemDelivered]

