# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_message_system():
    from objectiveai_sdk.agent.completions.message import MessageSystem
    schema = MessageSystem.model_json_schema()
