// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandDaemonSpawnRequestSchema } from "./request";

export const CliCommandDaemonSpawnViewerRequestSchema = z.object({
  id: z.string(),
  value: CliCommandDaemonSpawnRequestSchema,
}).describe("Viewer-stream mirror of [`Request`]: the request (nested under\n`value`, `path_type` and all) plus the broadcast stream `id`.").meta({ title: "cli.command.daemon.spawn.ViewerRequest" });
export type CliCommandDaemonSpawnViewerRequest = z.infer<typeof CliCommandDaemonSpawnViewerRequestSchema>;
