// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandLogsFunctionsInventionsRecursiveRequestSubscribeRequestSchemaPathSchema } from "./path";

export const CliCommandLogsFunctionsInventionsRecursiveRequestSubscribeRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandLogsFunctionsInventionsRecursiveRequestSubscribeRequestSchemaPathSchema,
}).meta({ title: "cli.command.logs.functions.inventions.recursive.request.subscribe.request_schema.Request" });
export type CliCommandLogsFunctionsInventionsRecursiveRequestSubscribeRequestSchemaRequest = z.infer<typeof CliCommandLogsFunctionsInventionsRecursiveRequestSubscribeRequestSchemaRequestSchema>;
