// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandConfigSwarmsFavoritesGetPathSchema = z.literal("config/swarms/favorites/get").meta({ title: "cli.command.config.swarms.favorites.get.Path" });
export type CliCommandConfigSwarmsFavoritesGetPath = z.infer<typeof CliCommandConfigSwarmsFavoritesGetPathSchema>;
