// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { AgentInlineAgentSchema } from "./inlineAgent";
import { AgentRemoteAgentSchema } from "./remoteAgent";

export const AgentAgentSchema = z.union([AgentRemoteAgentSchema.meta({"title":"agent.RemoteAgent","variantTitle":"Remote"}), AgentInlineAgentSchema.meta({"title":"agent.InlineAgent","variantTitle":"Inline"})]).describe("A validated Agent, either remote (with metadata) or inline.").meta({ title: "agent.Agent" });
export type AgentAgent = z.infer<typeof AgentAgentSchema>;
