// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { AgentInlineAgentSchema } from "./inlineAgent";

export const AgentRemoteAgentSchema = AgentInlineAgentSchema.and(z.object({
  description: z.string(),
})).describe("A validated remote Agent with metadata and computed content-addressed ID.").meta({ title: "agent.RemoteAgent" });
export type AgentRemoteAgent = z.infer<typeof AgentRemoteAgentSchema>;
