// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandApiConfigMcpCallTimeoutMsSetPathSchema = z.literal("api/config/mcp_call_timeout_ms/set").meta({ title: "cli.command.api.config.mcp_call_timeout_ms.set.Path" });
export type CliCommandApiConfigMcpCallTimeoutMsSetPath = z.infer<typeof CliCommandApiConfigMcpCallTimeoutMsSetPathSchema>;
