// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandPluginsGetRequestSchema } from "./request";

export const CliCommandPluginsGetViewerRequestSchema = z.object({
  id: z.string(),
  value: CliCommandPluginsGetRequestSchema,
}).meta({ title: "cli.command.plugins.get.ViewerRequest" });
export type CliCommandPluginsGetViewerRequest = z.infer<typeof CliCommandPluginsGetViewerRequestSchema>;
