# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from objectiveai_sdk.cli.command.tools.get.response_manifest import ResponseManifest
from objectiveai_sdk.cli.command.tools.list.path import Path


class ViewerResponseItem(BaseModel):
    model_config = ConfigDict(title='cli.command.tools.list.ViewerResponseItem')

    id: str
    path_type: Path
    value: ResponseManifest

