# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_inline_profile_or_remote_commit_optional():
    from objectiveai_sdk.functions import InlineProfileOrRemoteCommitOptional
    schema = InlineProfileOrRemoteCommitOptional.model_json_schema()
