# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_task_expression_vector_function_client():
    from objectiveai_sdk.functions import TaskExpressionVectorFunctionClient
    schema = TaskExpressionVectorFunctionClient.model_json_schema()
