# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_task_expression_vector_function_client_input_expression():
    from objectiveai_sdk.functions import TaskExpressionVectorFunctionClientInputExpression
    schema = TaskExpressionVectorFunctionClientInputExpression.model_json_schema()
