# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from objectiveai_sdk.cli.command.agents.logs.list.vector_request_choice_part import VectorRequestChoicePart


class VectorRequestChoice(BaseModel):
    """One choice in a `VectorRequestChoices` block: this agent's inline
voting `key` for the choice plus the choice's content parts (in
request order). The key is returned inline — no `read id` needed."""
    model_config = ConfigDict(title='cli.command.agents.logs.list.VectorRequestChoice')

    key: str = Field(..., description='The prefix-tree voting key this agent assigned to the choice.')
    parts: list[VectorRequestChoicePart]

