// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandConfigSwarmsFavoritesDelRequestSchemaPathSchema } from "./path";

export const CliCommandConfigSwarmsFavoritesDelRequestSchemaRequestSchema = z.object({
  jq: z.string().nullable().optional(),
  path_type: CliCommandConfigSwarmsFavoritesDelRequestSchemaPathSchema,
}).meta({ title: "cli.command.config.swarms.favorites.del.request_schema.Request" });
export type CliCommandConfigSwarmsFavoritesDelRequestSchemaRequest = z.infer<typeof CliCommandConfigSwarmsFavoritesDelRequestSchemaRequestSchema>;
