// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsVectorCompletionsResponseListResponseSchemaPathSchema = z.literal("logs/vector/completions/response/list/response_schema").meta({ title: "cli.command.logs.vector.completions.response.list.response_schema.Path" });
export type CliCommandLogsVectorCompletionsResponseListResponseSchemaPath = z.infer<typeof CliCommandLogsVectorCompletionsResponseListResponseSchemaPathSchema>;
