//! What a client's body frame carries.

use rmcp::model::ServerJsonRpcMessage;

/// The payload of a [`ClientFrame::Body`](crate::frame::client::ClientFrame::Body).
///
/// A body frame's bytes mean different things on different channels,
/// and this is the set of things they can mean. Which one applies is
/// not carried in the frame: it was settled when the channel opened,
/// by the type of the server request that opened it. A reader knows
/// before the body arrives, so the body does not repeat it.
///
/// Every variant carries its channel. A client only ever sends bodies
/// on channels the SERVER opened — its own request rides in a request
/// frame, not a body — so there is no channel `0` case to leave
/// implicit the way the server's has.
/// No `PartialEq`: rmcp's `JsonRpcMessage` does not implement it, its
/// result types being generated by a macro that derives only `Debug`
/// and `Clone`. Comparing two of these means comparing their
/// serialized forms.
#[derive(Debug, Clone)]
pub enum ClientBodyFrame<'a> {
    /// An MCP message back to the server.
    ///
    /// A `ServerJsonRpcMessage` despite travelling client to server:
    /// the roles invert here. The provider's model is what calls
    /// tools, so the client is the MCP server and this is what it
    /// answers with.
    Mcp {
        /// The channel the server opened for this exchange.
        channel: u32,
        /// The message.
        message: ServerJsonRpcMessage,
    },
    /// Postgres bytes, from the database.
    ///
    /// OPAQUE, exactly as the db-proxy conduit keeps them. See
    /// [`ServerBodyFrame::Postgres`](super::super::server::ServerBodyFrame::Postgres).
    Postgres {
        /// The channel the server opened for this connection.
        channel: u32,
        /// The bytes, borrowed from the frame they arrived in.
        payload: &'a [u8],
    },
}
