# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from objectiveai_sdk.json_value import JsonValue
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.config.viewer.address.response import Response as CliCommandConfigViewerAddressResponse
from objectiveai_sdk.cli.command.config.viewer.get.response import Response as CliCommandConfigViewerGetResponse
from objectiveai_sdk.cli.command.config.viewer.port.response import Response as CliCommandConfigViewerPortResponse
from objectiveai_sdk.cli.command.config.viewer.secret.response import Response as CliCommandConfigViewerSecretResponse
from objectiveai_sdk.cli.command.config.viewer.signature.response import Response as CliCommandConfigViewerSignatureResponse


class ResponseGet(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Get'})

    root: CliCommandConfigViewerGetResponse


class ResponseGetRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetRequestSchema'})

    root: JsonValue


class ResponseGetResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetResponseSchema'})

    root: JsonValue


class ResponseAddress(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Address'})

    root: CliCommandConfigViewerAddressResponse


class ResponsePort(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Port'})

    root: CliCommandConfigViewerPortResponse


class ResponseSecret(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Secret'})

    root: CliCommandConfigViewerSecretResponse


class ResponseSignature(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Signature'})

    root: CliCommandConfigViewerSignatureResponse


class Response(RootModel):
    model_config = ConfigDict(title='cli.command.config.viewer.Response')

    root: Union[ResponseGet, ResponseGetRequestSchema, ResponseGetResponseSchema, ResponseAddress, ResponsePort, ResponseSecret, ResponseSignature]

