# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_plugin():
    from objectiveai_sdk.mcp import Plugin
    schema = Plugin.model_json_schema()
