// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const AgentCompletionsRequestProviderSortSchema = z.union([z.literal("price").describe("Prioritize by price (cheapest first).").meta({"variantTitle":"Price"}), z.literal("throughput").describe("Prioritize by throughput (fastest first).").meta({"variantTitle":"Throughput"}), z.literal("latency").describe("Prioritize by latency (lowest first).").meta({"variantTitle":"Latency"})]).describe("How to sort/prioritize providers.").meta({ title: "agent.completions.request.ProviderSort" });
export type AgentCompletionsRequestProviderSort = z.infer<typeof AgentCompletionsRequestProviderSortSchema>;
