// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsAgentsCompletionsResponseMessagesVideoGetPathSchema = z.literal("logs/agents/completions/response/messages/video/get").meta({ title: "cli.command.logs.agents.completions.response.messages.video.get.Path" });
export type CliCommandLogsAgentsCompletionsResponseMessagesVideoGetPath = z.infer<typeof CliCommandLogsAgentsCompletionsResponseMessagesVideoGetPathSchema>;
