// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { CliCommandDevelopmentPluginsMcpRequestSchema } from "./mcp/request";
import { CliCommandDevelopmentPluginsViewerRequestSchema } from "./viewer/request";

export const CliCommandDevelopmentPluginsRequestSchema = z.union([CliCommandDevelopmentPluginsMcpRequestSchema.meta({"title":"cli.command.development.plugins.mcp.Request","variantTitle":"Mcp"}), CliCommandDevelopmentPluginsViewerRequestSchema.meta({"title":"cli.command.development.plugins.viewer.Request","variantTitle":"Viewer"})]).meta({ title: "cli.command.development.plugins.Request" });
export type CliCommandDevelopmentPluginsRequest = z.infer<typeof CliCommandDevelopmentPluginsRequestSchema>;
