# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.user.request.request import Request as CliCommandUserRequestRequest
from objectiveai_sdk.cli.command.user.request.request_schema.request import Request as CliCommandUserRequestRequestSchemaRequest
from objectiveai_sdk.cli.command.user.request.response_schema.request import Request as CliCommandUserRequestResponseSchemaRequest


class RequestRequest(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Request'})

    root: CliCommandUserRequestRequest


class RequestRequestRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'RequestRequestSchema'})

    root: CliCommandUserRequestRequestSchemaRequest


class RequestRequestResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'RequestResponseSchema'})

    root: CliCommandUserRequestResponseSchemaRequest


class Request(RootModel):
    model_config = ConfigDict(title='cli.command.user.Request')

    root: Union[RequestRequest, RequestRequestRequestSchema, RequestRequestResponseSchema]

