# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai_sdk.cli.command.daemon.config.address.request import Request as CliCommandDaemonConfigAddressRequest
from objectiveai_sdk.cli.command.daemon.config.get.request import Request as CliCommandDaemonConfigGetRequest
from objectiveai_sdk.cli.command.daemon.config.get.request_schema.request import Request as CliCommandDaemonConfigGetRequestSchemaRequest
from objectiveai_sdk.cli.command.daemon.config.get.response_schema.request import Request as CliCommandDaemonConfigGetResponseSchemaRequest
from objectiveai_sdk.cli.command.daemon.config.refresh_secret_signature_pair.request import Request as CliCommandDaemonConfigRefreshSecretSignaturePairRequest
from objectiveai_sdk.cli.command.daemon.config.refresh_secret_signature_pair.request_schema.request import Request as CliCommandDaemonConfigRefreshSecretSignaturePairRequestSchemaRequest
from objectiveai_sdk.cli.command.daemon.config.refresh_secret_signature_pair.response_schema.request import Request as CliCommandDaemonConfigRefreshSecretSignaturePairResponseSchemaRequest
from objectiveai_sdk.cli.command.daemon.config.secret.request import Request as CliCommandDaemonConfigSecretRequest
from objectiveai_sdk.cli.command.daemon.config.set.request import Request as CliCommandDaemonConfigSetRequest
from objectiveai_sdk.cli.command.daemon.config.set.request_schema.request import Request as CliCommandDaemonConfigSetRequestSchemaRequest
from objectiveai_sdk.cli.command.daemon.config.set.response_schema.request import Request as CliCommandDaemonConfigSetResponseSchemaRequest
from objectiveai_sdk.cli.command.daemon.config.signature.request import Request as CliCommandDaemonConfigSignatureRequest


class RequestGet(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Get'})

    root: CliCommandDaemonConfigGetRequest


class RequestGetRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetRequestSchema'})

    root: CliCommandDaemonConfigGetRequestSchemaRequest


class RequestGetResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'GetResponseSchema'})

    root: CliCommandDaemonConfigGetResponseSchemaRequest


class RequestSet(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Set'})

    root: CliCommandDaemonConfigSetRequest


class RequestSetRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'SetRequestSchema'})

    root: CliCommandDaemonConfigSetRequestSchemaRequest


class RequestSetResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'SetResponseSchema'})

    root: CliCommandDaemonConfigSetResponseSchemaRequest


class RequestAddress(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Address'})

    root: CliCommandDaemonConfigAddressRequest


class RequestRefreshSecretSignaturePair(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'RefreshSecretSignaturePair'})

    root: CliCommandDaemonConfigRefreshSecretSignaturePairRequest


class RequestRefreshSecretSignaturePairRequestSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'RefreshSecretSignaturePairRequestSchema'})

    root: CliCommandDaemonConfigRefreshSecretSignaturePairRequestSchemaRequest


class RequestRefreshSecretSignaturePairResponseSchema(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'RefreshSecretSignaturePairResponseSchema'})

    root: CliCommandDaemonConfigRefreshSecretSignaturePairResponseSchemaRequest


class RequestSecret(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Secret'})

    root: CliCommandDaemonConfigSecretRequest


class RequestSignature(RootModel):
    model_config = ConfigDict(json_schema_extra={'_variant_title': 'Signature'})

    root: CliCommandDaemonConfigSignatureRequest


class Request(RootModel):
    model_config = ConfigDict(title='cli.command.daemon.config.Request')

    root: Union[RequestGet, RequestGetRequestSchema, RequestGetResponseSchema, RequestSet, RequestSetRequestSchema, RequestSetResponseSchema, RequestAddress, RequestRefreshSecretSignaturePair, RequestRefreshSecretSignaturePairRequestSchema, RequestRefreshSecretSignaturePairResponseSchema, RequestSecret, RequestSignature]

