# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_inactive():
    from objectiveai_sdk.cli.output.notification.agents import Inactive
    schema = Inactive.model_json_schema()
