# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class LaboratoryAttachment(BaseModel):
    """One laboratory attachment on an agent, as surfaced by
`agents instances get`."""
    model_config = ConfigDict(title='cli.command.agents.instances.list.LaboratoryAttachment')

    attached_at: str = Field(..., description='RFC3339 — when it was attached.')
    attached_by: Optional[str] = Field(None, description='The AIH that ran the attach. `None` on attachments predating\nattacher tracking.', json_schema_extra={'omitempty': True})
    id: str = Field(..., description="The attached laboratory's id.")

