use super::*;
use crate::tests::stream_push::stream_push_test;

stream_push_test!(
    single_chunk_unchanged,
    vec![FunctionProfileComputationChunk {
        id: "fpcc-1".into(),
        executions: vec![],
        executions_errors: None,
        profile: None,
        fitting_stats: None,
        retry_token: None,
        created: 100,
        function: None,
        object: Object::FunctionProfileComputationChunk,
        usage: None,
    }],
    FunctionProfileComputationChunk {
        id: "fpcc-1".into(),
        executions: vec![],
        executions_errors: None,
        profile: None,
        fitting_stats: None,
        retry_token: None,
        created: 100,
        function: None,
        object: Object::FunctionProfileComputationChunk,
        usage: None,
    }
);

stream_push_test!(
    fitting_stats_set_from_later_chunk,
    vec![
        FunctionProfileComputationChunk {
            id: "fpcc-2".into(),
            executions: vec![],
            executions_errors: None,
            profile: None,
            fitting_stats: None,
            retry_token: None,
            created: 100,
            function: None,
            object: Object::FunctionProfileComputationChunk,
            usage: None,
        },
        FunctionProfileComputationChunk {
            id: "fpcc-2".into(),
            executions: vec![],
            executions_errors: None,
            profile: None,
            fitting_stats: Some(crate::functions::profiles::computations::response::FittingStats {
                loss: rust_decimal::Decimal::new(5, 2),
                executions: 10,
                starts: 3,
                rounds: 5,
                errors: 0,
            }),
            retry_token: None,
            created: 100,
            function: None,
            object: Object::FunctionProfileComputationChunk,
            usage: None,
        },
    ],
    FunctionProfileComputationChunk {
        id: "fpcc-2".into(),
        executions: vec![],
        executions_errors: None,
        profile: None,
        fitting_stats: Some(crate::functions::profiles::computations::response::FittingStats {
            loss: rust_decimal::Decimal::new(5, 2),
            executions: 10,
            starts: 3,
            rounds: 5,
            errors: 0,
        }),
        retry_token: None,
        created: 100,
        function: None,
        object: Object::FunctionProfileComputationChunk,
        usage: None,
    }
);

stream_push_test!(
    executions_merged_by_index,
    vec![
        FunctionProfileComputationChunk {
            id: "fpcc-3".into(),
            executions: vec![FunctionExecutionChunk {
                index: 0,
                dataset: 0,
                n: 0,
                retry: 0,
                inner: crate::functions::executions::response::streaming::FunctionExecutionChunk {
                    id: "fec-1".into(),
                    tasks: vec![],
                    tasks_errors: None,
                    reasoning: None,
                    output: None,
                    error: None,
                    retry_token: None,
                    created: 100,
                    function: None,
                    profile: None,
                    object: crate::functions::executions::response::streaming::Object::ScalarFunctionExecutionChunk,
                    usage: None,
                },
            }],
            executions_errors: None,
            profile: None,
            fitting_stats: None,
            retry_token: None,
            created: 100,
            function: Some(crate::RemotePath::Github { owner: "owner".into(), repository: "repo".into(), commit: "abc123".into() }),
            object: Object::FunctionProfileComputationChunk,
            usage: None,
        },
        FunctionProfileComputationChunk {
            id: "fpcc-3".into(),
            executions: vec![FunctionExecutionChunk {
                index: 1,
                dataset: 1,
                n: 0,
                retry: 0,
                inner: crate::functions::executions::response::streaming::FunctionExecutionChunk {
                    id: "fec-2".into(),
                    tasks: vec![],
                    tasks_errors: None,
                    reasoning: None,
                    output: None,
                    error: None,
                    retry_token: None,
                    created: 100,
                    function: None,
                    profile: None,
                    object: crate::functions::executions::response::streaming::Object::ScalarFunctionExecutionChunk,
                    usage: None,
                },
            }],
            executions_errors: None,
            profile: None,
            fitting_stats: None,
            retry_token: None,
            created: 100,
            function: Some(crate::RemotePath::Github { owner: "owner".into(), repository: "repo".into(), commit: "abc123".into() }),
            object: Object::FunctionProfileComputationChunk,
            usage: None,
        },
    ],
    FunctionProfileComputationChunk {
        id: "fpcc-3".into(),
        executions: vec![
            FunctionExecutionChunk {
                index: 0,
                dataset: 0,
                n: 0,
                retry: 0,
                inner: crate::functions::executions::response::streaming::FunctionExecutionChunk {
                    id: "fec-1".into(),
                    tasks: vec![],
                    tasks_errors: None,
                    reasoning: None,
                    output: None,
                    error: None,
                    retry_token: None,
                    created: 100,
                    function: None,
                    profile: None,
                    object: crate::functions::executions::response::streaming::Object::ScalarFunctionExecutionChunk,
                    usage: None,
                },
            },
            FunctionExecutionChunk {
                index: 1,
                dataset: 1,
                n: 0,
                retry: 0,
                inner: crate::functions::executions::response::streaming::FunctionExecutionChunk {
                    id: "fec-2".into(),
                    tasks: vec![],
                    tasks_errors: None,
                    reasoning: None,
                    output: None,
                    error: None,
                    retry_token: None,
                    created: 100,
                    function: None,
                    profile: None,
                    object: crate::functions::executions::response::streaming::Object::ScalarFunctionExecutionChunk,
                    usage: None,
                },
            },
        ],
        executions_errors: None,
        profile: None,
        fitting_stats: None,
        retry_token: None,
        created: 100,
        function: Some(crate::RemotePath::Github { owner: "owner".into(), repository: "repo".into(), commit: "abc123".into() }),
        object: Object::FunctionProfileComputationChunk,
        usage: None,
    }
);

stream_push_test!(
    usage_set_from_later_chunk,
    vec![
        FunctionProfileComputationChunk {
            id: "fpcc-4".into(),
            executions: vec![],
            executions_errors: None,
            profile: None,
            fitting_stats: None,
            retry_token: None,
            created: 100,
            function: None,
            object: Object::FunctionProfileComputationChunk,
            usage: None,
        },
        FunctionProfileComputationChunk {
            id: "fpcc-4".into(),
            executions: vec![],
            executions_errors: None,
            profile: None,
            fitting_stats: None,
            retry_token: None,
            created: 100,
            function: None,
            object: Object::FunctionProfileComputationChunk,
            usage: Some(crate::agent::completions::response::Usage {
                prompt_tokens: 50,
                completion_tokens: 20,
                total_tokens: 70,
                completion_tokens_details: None,
                prompt_tokens_details: None,
                cost: rust_decimal::Decimal::new(5, 3),
                cost_details: None,
                total_cost: rust_decimal::Decimal::new(5, 3),
            }),
        },
    ],
    FunctionProfileComputationChunk {
        id: "fpcc-4".into(),
        executions: vec![],
        executions_errors: None,
        profile: None,
        fitting_stats: None,
        retry_token: None,
        created: 100,
        function: None,
        object: Object::FunctionProfileComputationChunk,
        usage: Some(crate::agent::completions::response::Usage {
            prompt_tokens: 50,
            completion_tokens: 20,
            total_tokens: 70,
            completion_tokens_details: None,
            prompt_tokens_details: None,
            cost: rust_decimal::Decimal::new(5, 3),
            cost_details: None,
            total_cost: rust_decimal::Decimal::new(5, 3),
        }),
    }
);

stream_push_test!(
    executions_errors_set,
    vec![
        FunctionProfileComputationChunk {
            id: "fpcc-5".into(),
            executions: vec![],
            executions_errors: None,
            profile: None,
            fitting_stats: None,
            retry_token: None,
            created: 100,
            function: None,
            object: Object::FunctionProfileComputationChunk,
            usage: None,
        },
        FunctionProfileComputationChunk {
            id: "fpcc-5".into(),
            executions: vec![],
            executions_errors: Some(true),
            profile: None,
            fitting_stats: None,
            retry_token: None,
            created: 100,
            function: None,
            object: Object::FunctionProfileComputationChunk,
            usage: None,
        },
    ],
    FunctionProfileComputationChunk {
        id: "fpcc-5".into(),
        executions: vec![],
        executions_errors: Some(true),
        profile: None,
        fitting_stats: None,
        retry_token: None,
        created: 100,
        function: None,
        object: Object::FunctionProfileComputationChunk,
        usage: None,
    }
);
