# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Annotated, Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai_sdk.cli.command.agents.logs.read.all.path import Path
from objectiveai_sdk.cli.command.agents.logs.read.all.target import Target


class Request(BaseModel):
    model_config = ConfigDict(title='cli.command.agents.logs.read.all.Request')

    after_id: Optional[Annotated[int, Field(ge=-9223372036854775808, le=9223372036854775807)]] = Field(None, description='Skip rows with `logs.messages."index" <= after_id`. Use the\nhighest `id` from a previous page to paginate forward.', json_schema_extra={'omitempty': True})
    jq: Optional[str] = None
    limit: Optional[Annotated[int, Field(ge=-9223372036854775808, le=9223372036854775807)]] = Field(None, description='Cap on rows scanned per target. `None` = unlimited.', json_schema_extra={'omitempty': True})
    path_type: Path
    targets: list[Target]

