// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandFunctionsInventionsRecursiveCreateRemoteRequestDangerousAdvancedSchema = z.object({
  stream: z.boolean().nullable().meta({ omitempty: true }).optional(),
}).meta({ title: "cli.command.functions.inventions.recursive.create.remote.RequestDangerousAdvanced" });
export type CliCommandFunctionsInventionsRecursiveCreateRemoteRequestDangerousAdvanced = z.infer<typeof CliCommandFunctionsInventionsRecursiveCreateRemoteRequestDangerousAdvancedSchema>;
