// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const CliCommandLogsFunctionsExecutionsResponseGetRequestSchemaPathSchema = z.literal("logs/functions/executions/response/get/request_schema").meta({ title: "cli.command.logs.functions.executions.response.get.request_schema.Path" });
export type CliCommandLogsFunctionsExecutionsResponseGetRequestSchemaPath = z.infer<typeof CliCommandLogsFunctionsExecutionsResponseGetRequestSchemaPathSchema>;
